### ISSUE TITLE
How does everyone access a uiInputPicklist?

### ISSUE THREAD

**Issue by EthanKing96** [SFDO-Tooling/CumulusCI#1006]
Right now I am using this method to access a picklist in the new opportunity modal

Click Link    //*[contains(text(),'--None--')]
Click Link    ${STAGE}

but this doesn't work well when there are other picklists and they all have the same default option of
 '--None--'

Picklists also don't have other unique identifiers other than their label.

**Comment by vish4444** [comment]
1. I have created a list to pass the XPath for options in my picklist and hence do not depend on labels.
2. I keep accessing the Xpaths in the list to select my desired option.
3. I select values based on the number of options in my picklist, starting option[1]=--None--, option[2]=Value1, option[3]=Value2 and so on.
4. This works on my VisualForce pages.

`Click Element  ${LevelPickList}  
#here is the xpath: ${LevelPickList}  //form[@name='mainPage:mainForm']//div[@id='yourcustomvalue']/div/div[2]/table/tbody/tr[3]/td[2]/span/span/div/div/div/select
`Click Element  ${SelectLevelsList}[0]  
#here is the xpath: @{SelectLevelsList}  //form[@name='mainPage:mainForm']//div[@id='yourcustomvalue']/div/div[2]/table/tbody/tr[3]/td[2]/span/span/div/div/div/select/option[2]  //form[@name='mainPage:mainForm']//div[@id='yourcustomvalue']/div/div[2]/table/tbody/tr[3]/td[2]/span/span/div/div/div/select/option[3]
