### ISSUE TITLE
Salesforce Keyword page is down

### ISSUE THREAD

**Issue by EthanKing96** [SFDO-Tooling/CumulusCI#1011]
https://cumulusci.readthedocs.io/en/latest/_downloads/Salesforce_Library.html#Click%20Object%20Button

Did the keyword page get moved? Or is the link just broken atm?

Any help would be great!

Thanks!

**Comment by boakley** [comment]
We're revamping our keyword documentation and didn't catch this. Thanks for letting us know, we'll take a look!

**Comment by EthanKing96** [comment]
Thanks!

**Comment by boakley** [comment]
Until we have a more permanent fix, you can use the following link to get to the keyword documentation:

https://cumulusci.readthedocs.io/en/latest/_downloads/Keywords.html

**Comment by EthanKing96** [comment]
Wow! Thank you so much! Way better than the old one.
