### ISSUE TITLE
Support "checkOnly" option for Deploy task

### ISSUE THREAD

**Issue by e02d96ec16** [SFDO-Tooling/CumulusCI#1066]
I see it is currently hard-coded to `false` in the soap envelope in `cumulusci.salesforce_api.metadata.ApiDeploy`. Could it be exposed as a parameter instead, and eventually made as an option for the `deploy` task?

**Comment by davisagli** [comment]
This sounds like a reasonable idea to me.

**Comment by e02d96ec16** [comment]
I think this is something CCI lost in the migration to Python, as the SF ANT lib back then supported this property for deployments.
