### ISSUE TITLE
No support for multiple windows in robot

### ISSUE THREAD

**Issue by moloman** [SFDO-Tooling/CumulusCI#1068]
When running a robot test where a user has to open two windows (for example to test a live chat functionality), the keyword "Open Test Browser" fails. You can run the keyword once to open a window but attempting to open a second window using the same keyword fails with this error:

The custom locator 'text' cannot be registered. A locator of that name already exists.

The error is being caused by the "Add Location Strategy" keyword in "Open Test Browser".
Any solution to this that still allows the user to select which browser to use when running the task?

**Comment by boakley** [comment]
Thank you for reporting this. A simple work around until we've fixed this is to make your own version of the `Open Test Browser` keyword which opens the browser but doesn't call the `Add Location Strategy` keyword.

For example:

```
*** Keywords ***
Open Secondary Test Browser
    ${login_url} =  Login Url
    Run Keyword If  '${BROWSER}' == 'chrome'  Open Test Browser Chrome  ${login_url}
    ...    ELSE IF  '${BROWSER}' == 'firefox'  Open Test Browser Firefox  ${login_url}
    ...    ELSE IF  '${BROWSER}' == 'headlesschrome'  Open Test Browser Chrome  ${login_url}
    ...    ELSE IF  '${BROWSER}' == 'headlessfirefox'  Open Test Browser Headless Firefox  ${login_url}
    ...    ELSE  Open Browser  ${login_url}  ${BROWSER}
```

As you can see, this keyword is really nothing more than a simple front-end which calls one of the more specialized keywords. If you're only ever testing with one browser, you can call one of these other keywords  directly (`Open Test Browser Chrome`, `Open Test Browser Firefox`, `Open Test Browser Headless Firefox`) without creating your own keyword.

**Comment by davisagli** [comment]
This should now work in cumulusci 2.5.0
