### ISSUE TITLE
Communities Creation through Chatter API

### ISSUE THREAD

**Issue by MatthewBlanski** [SFDO-Tooling/CumulusCI#1091]
The Summer 19 release has new features for creating and publishing communities. Hooking this into Cumulus CI would be a welcome enhancement as a number of test scenarios require spinning up a community, and even deploying metadata for it.

[Summer 19 release chatter API changes](https://releasenotes.docs.salesforce.com/en-us/summer19/release-notes/rn_chatter_api.htm#rn_chatter_api_resources)

**Comment by jstvz** [comment]
Nice!
