### ISSUE TITLE
Smarter step overrides: replace flow with task or vice versa

### ISSUE THREAD

**Issue by davisagli** [SFDO-Tooling/CumulusCI#1098]
If there's a flow defined like this:

    steps:
        1:
            task: foo

And an overriding config wants to replace that step with a flow, that currently must be done like this:

    steps:
        1:
            task: None
        2:
            flow: bar

It would be nice if it could be done like this:

    steps:
        1:
            flow: bar

and CCI would be smart enough to know that flows replace tasks and vice versa when merging flow configs.

**Comment by davidmreed** [comment]
Created W-8889877.

**Comment by davidmreed** [comment]
This was fixed in https://github.com/SFDO-Tooling/CumulusCI/pull/3043
