### ISSUE TITLE
Allow connection to GitHub Enterprise

### ISSUE THREAD

**Issue by jdominiczak** [SFDO-Tooling/CumulusCI#1129]
The task `cci service connect github` does not allow a user to enter their GitHub enterprise server's address

**Comment by umeditor** [comment]
This is also an issue for us. Any workaround?

**Comment by adesotamn** [comment]
I work in SF and would like to see this implemented. :/

**Comment by LoneWolfPR** [comment]
I see a feature for this was built then closed. Does this mean this will not be supported? I am also a SF employee, and our team would really like to use cumulusci, but we can't without the ability to tie it to our github enterprise server.

**Comment by davisagli** [comment]
@LoneWolfPR We still intend to add support for this but I am not certain of timeframe.

**Comment by mpeddycord** [comment]
@davisagli I realize this was last commented on in July 2020, but are there plans to support GitHub Enterprise with CumulusCI? It's a much needed part of our enterprise workflow.

**Comment by davisagli** [comment]
@mpeddycord We'd like to at some point, but it is not currently a priority in our roadmap.

**Comment by prashant-prasannakumaran** [comment]
The lack of this feature is making Cumulus un-usable in Enterprise projects. Are there any workarounds?

**Comment by davidmreed** [comment]
Tracking as W-11279304
