### ISSUE TITLE
Example Robot Contact Test failing

### ISSUE THREAD

**Issue by mtetlow** [SFDO-Tooling/CumulusCI#1131]
[log.html.log](https://github.com/SFDO-Tooling/CumulusCI/files/3332032/log.html.log)
[output.xml.log](https://github.com/SFDO-Tooling/CumulusCI/files/3332033/output.xml.log)
[report.html.log](https://github.com/SFDO-Tooling/CumulusCI/files/3332034/report.html.log)

Just installed cci and I am having issues with the example robot test.

`cci task run robot -o suites robot/TaskRay/tests/create_contact.robot -o vars BROWSER:chrome`

outputs 
```2019-06-26 15:31:20: Getting scratch org info from Salesforce DX
2019-06-26 15:31:22: Beginning task: Robot
2019-06-26 15:31:22:        As user: test-aaams4e3t4vf@example.com
2019-06-26 15:31:22:         In org: 00D2a000000D57h
2019-06-26 15:31:22:
==============================================================================
Create Contact
==============================================================================
Via API                                                               | FAIL |
SalesforceResourceNotFound: Resource Contact Not Found. Response content: [{'errorCode': 'NOT_FOUND', 'message': 'The requested resource does not exist'}]
------------------------------------------------------------------------------
Via UI                                                                | FAIL |
SalesforceResourceNotFound: Resource Contact Not Found. Response content: [{'errorCode': 'NOT_FOUND', 'message': 'The requested resource does not exist'}]
------------------------------------------------------------------------------
Create Contact                                                        | FAIL |
2 critical tests, 0 passed, 2 failed
2 tests total, 0 passed, 2 failed
==============================================================================
Output:  /Users/mikename/dev/salesforce/sfdx/taskray/robot/TaskRay/results/output.xml
Log:     /Users/mikename/dev/salesforce/sfdx/taskray/robot/TaskRay/results/log.html
Report:  /Users/mikename/dev/salesforce/sfdx/taskray/robot/TaskRay/results/report.html

Error: 2 tests failed.```

I've attached the log, output, and report as files. 

What seems to happen in the org is that the api record create fails, the ui record create works (and does not get cleaned up), then both the ui and api verifications fail.

I have followed the project setup guide found here: https://cumulusci.readthedocs.io/en/latest/tutorial.html . Does anyone have suggestions on where I can start troubleshooting this?

**Comment by davisagli** [comment]
Not sure what's wrong here, but it looks like this user does not have API access to the Contact object for some reason.

Here are some things to check:
- make sure the org is an edition that supports the API (Enterprise, Unlimited or Developer Edition)
- make sure the user's profile has API access enabled and permissions to the Contact object
- check if you can access the Contact object via the REST API in another tool such as Workbench

**Comment by mtetlow** [comment]
1) I started with scratch orgs but also tried using a ee trial org spun from environment hub, both have the same error
2) The user does have api access and perms to create and read the contact object. It's successfully creating them during the ui test even.
3) I can successfully query Contact Id,Name from workbench as the user running the test

Any ideas on how I can dig deeper into what could be wrong?

**Comment by davisagli** [comment]
@mtetlow ok, certainly sounds like a lack of API access for this user is not the problem. I wonder if the URL for the API call is not being constructed correctly for some reason. Try running the task with the `--debug` flag at the end, which should print extra log lines for each HTTP request.

On my machine this includes output like this:

    2019-06-27 14:13:44,566 DEBUG https://power-platform-735-dev-ed.cs1.my.salesforce.com:443 "POST /services/data/v46.0/sobjects/Contact/ HTTP/1.1" 201 None
    .2019-06-27 14:13:44,720 DEBUG https://power-platform-735-dev-ed.cs1.my.salesforce.com:443 "GET /services/data/v46.0/sobjects/Contact/003S0000018E5oVIAS HTTP/1.1" 200 None

and I'm curious how that compares in your case.

**Comment by mtetlow** [comment]
huzzah!

`2019-06-27 13:42:34,854 DEBUG https://dendugtdxgg19.my.salesforce.com:443 "POST /services/data/v45/sobjects/Contact/ HTTP/1.1" 404 None
Via API                                                               | FAIL |
SalesforceResourceNotFound: Resource Contact Not Found. Response content: [{'errorCode': 'NOT_FOUND', 'message': 'The requested resource does not exist'}]`

it should be hitting `/services/data/v45.0/sobjects/Contact/`

I was able to fix this by changing the api_version in the cumulusci.yml from '45' to '45.0'.

Thanks for your help with this issue!

**Comment by davisagli** [comment]
@mtetlow that makes complete sense and I've seen this before. I'll open an issue to make CumulusCI validate the format of the api_version. glad you're unstuck.
