### ISSUE TITLE
getting error : cumulusci.core.exceptions.KeychainKeyNotFound: The keychain key was not found.

### ISSUE THREAD

**Issue by prashant-22** [SFDO-Tooling/CumulusCI#1140]
Hi, 
I followed all steps but getting error while adding metaci site add
cumulusci.core.exceptions.KeychainKeyNotFound: The keychain key was not found.
let me know how to create this file?

Thanks in adavance

**Comment by davisagli** [comment]
It sounds like you are trying to use MetaCI-CLI, not CumulusCI. MetaCI-CLI is currently very out of date and not expected to work.
