### ISSUE TITLE
Mapping table validations

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/CumulusCI#1160]
Validations we could do with SF introspection:

Can we introspect that a "field" should actually be a lookup?
That every listed field/object actually corresponds to an SF field? (do we want this?)

Validations that don't require introspection:

No "lookups" and "fields" with the same name?
That the referents of lookups appear in the mapping file before the lookups.

**Comment by davisagli** [comment]
Could you put these in our internal "Bulk Data Enhancement Stories" doc so that we can consider them alongside all the other bulk data task improvements that @davidmreed has been brainstorming?

**Comment by prescod** [comment]
Done. I'll leave it to you whether to close this ticket or leave it as an externally-facing record of the fact that we're considering this work.

**Comment by davisagli** [comment]
We added validation "That every listed field/object actually corresponds to an SF field" and are tracking the others internally.
