### ISSUE TITLE
Create a share-able link to track the builds/flows for troubleshooting from CLI

### ISSUE THREAD

**Issue by annejackson** [SFDO-Tooling/CumulusCI#1166]
A couple of use cases:
1. When running a build or flow via CLI there is a failure. Sharing the build/flow history is a manual process right now as you have to copy and paste it from your CLI into a chat or create a gist to share it as a link.
2. When testing a flow (like regression flow) and is completes successfully and you want to see and share all the flows and packages that have been installed/upgrades in a friendlier UI for easy searching- and then be able to share that quickly if there is an issue.

MetaCI does this well as it's automatically shared/available while the flow is being run and it shows the build history and identifies the flows run in a very UI friendly way, example:
https://mrbelvedereci.herokuapp.com/builds/100446/flows (with screenshot below)
![meta ci flow history](https://user-images.githubusercontent.com/35311289/62378870-be1ba680-b513-11e9-9cf9-174f8c336ece.png)

Via CCI if you want to share you have to manually create a gist and share. Example:
https://gist.github.com/jstvz/2038ccccb16ad8e655ce352014972304

It would be nice if there was some automation behind it being created automatically for you for easy sharing on github or somewhere similar. (not just for errors)

**Comment by annejackson** [comment]
@davisagli  and @jstvz  fyi. :)

**Comment by davisagli** [comment]
We added the `cci error gist` command a while ago.
