### ISSUE TITLE
Add revised CircleCI instructions to the cookbook

### ISSUE THREAD

**Issue by jstvz** [SFDO-Tooling/CumulusCI#1173]
The [CircleCI section](https://github.com/SFDO-Tooling/CumulusCI/blob/master/docs/cookbook.rst#circleci) of the cookbook references several commands and SFDC pilots that no longer exist. We removed it in #1500, but it should be re-added with up to date instructions.

**Comment by Br4nd0R** [comment]
@jstvz - Would you advocate to take this section out completely since we should probably be advocating for setup with MetaCI?

**Comment by jstvz** [comment]
@Br4nd0R I'm not entirely in agreement with that. I think that we should probably be adding instructions for _more_ CI systems, even if they're not actively supported. 

As far as this section is concerned, I self-assigned this, but my documentation writing has halting at best. I'm okay with temporarily removing it to avoid wasting users' time until we can get up-to-date instructions written.

**Comment by Br4nd0R** [comment]
Sounds good.

**Comment by davisagli** [comment]
I updated this section a little while ago; it now covers Github Actions rather than CircleCI. https://cumulusci.readthedocs.io/en/latest/cookbook.html#continuous-integration-with-cumulusci-and-github-actions
