### ISSUE TITLE
Trailing "0" on Version for Managed Package Dependencies in cumulusci.yml Not Recognized on Install

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#1175]
**Issue**
When running a flow/task which performs an install of dependencies (e.g. `cci flow run dev_org --org dev`), if the package version ends in a "0" (e.g. 6.5220), zero is not recognized during flow run producing an error:

`Error: InstalledPackage version number :  6.522 does not exist!`

**Steps to Reproduce**
1. Add a Managed Package Dependency to cumulusci.yml with a trailing "0":
>dependencies: 
        - namespace: stayclassy
          version: 6.5220
2. Run a flow/task that installs dependencies (e.g. `cci flow run dev_org --org dev`)

**Results**
- Task fails with error: `Error: InstalledPackage version number :  6.522 does not exist!`

**Expected Results**
- Package is successfully installed
- No errors

**Comment by davisagli** [comment]
It should work if you put quotes around the version:

    version: "6.5220"

That'll convince the yaml parser to read it as a string rather than a number.

**Comment by Julian88Tex** [comment]
Ah makes sense!

**Comment by Julian88Tex** [comment]
Probably just a matter of updating documentation then: https://cumulusci.readthedocs.io/en/latest/features.html#managing-dependencies

**Comment by Julian88Tex** [comment]
@davisagli although looking back at the yaml, nothing else has "" so it seems a bit out of place to do it in this one place. Seems more consistent to actually have interpreter read it as a string.

**Comment by davisagli** [comment]
@Julian88Tex that'd be nice but I don't think we have that level of control over the parsing. We use a generic YAML parser and using the quotes is how you tell it that something that looks like a decimal number should actually be read as a string.

**Comment by Julian88Tex** [comment]
@davisagli makes sense thanks for clarifying!

**Comment by jstvz** [comment]
Fixed by 5a5b526
