### ISSUE TITLE
Modify Required url_path_prefix for task create_community

### ISSUE THREAD

**Issue by MatthewBlanski** [SFDO-Tooling/CumulusCI#1207]
The option url_path_prefix is only `Required if you already have a community that doesn’t have a urlPathPrefix` per the documentation at [Chatter API Documentation](https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/connect_resources_communities_list.htm)

Updating the task to perform a dynamic check on existing communities to enforce this mid-flight would be ideal.

**Comment by davisagli** [comment]
No longer required in cumulusci 2.5.9
