### ISSUE TITLE
Will Second-Generation Managed Packages be supported in CumulusCI?

### ISSUE THREAD

**Issue by alexanderyhapcv** [SFDO-Tooling/CumulusCI#1264]

**Comment by davisagli** [comment]
cumulusci 3.20.0 added an experimental create_package_version task, which uploads a 2gp package (managed or unlocked) with the dependencies from your CumulusCI project.

At present, it has some limitations that we intend to work on in the future:
- It is not yet integrated with the release_beta/release_production flows.
- It does not yet provide a way to specify an ancestor for a managed package version.
- You still have to use an sfdx command to promote a package version to released status.
