### ISSUE TITLE
Make generate mappings task record-type aware

### ISSUE THREAD

**Issue by MatthewBlanski** [SFDO-Tooling/CumulusCI#1270]
EDA and other managed packages rely heavily on record types. Generate Mappings is not currently record-type aware, which eliminates a strong and necessary datapoint for data flows.

**Comment by davisagli** [comment]
@davidmreed is this easy to add to #1252 or does it make more sense to do it separately?

**Comment by davidmreed** [comment]
I would like to do it in #1252. (@MatthewBlanski Functionality in progress, just adding tests and integration to generator task).
