### ISSUE TITLE
Python 3.8 deprecation warning

### ISSUE THREAD

**Issue by acrosman** [SFDO-Tooling/CumulusCI#1273]
While setting up a local development environment I noticed a few deprecation warnings related to Python 8.3 and the collections package. There are a couple in upstream packages, but one from CumulusCI itself:
```
cumulusci\core\tests\utils.py:46
  [project-path]\CumulusCI\cumulusci\core\tests\utils.py:46: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    class EnvironmentVarGuard(collections.MutableMapping):
```

**Comment by davisagli** [comment]
This got fixed in the midst of other cleanup.
