### ISSUE TITLE
Flow install_prod and install_beta give confusing error when no successful build has been created

### ISSUE THREAD

**Issue by jofsky** [SFDO-Tooling/CumulusCI#1281]
When calling cci flow run install_prod --org <your org here> a 404 error is thrown. The same happens for cci flow run install_beta --org <your org here> when no successful build has succeeded in MetaCI. Attached is a log showing this error message.

<img width="1002" alt="Screen Shot 2019-10-24 at 11 14 31 AM" src="https://user-images.githubusercontent.com/28512644/67513456-b7eb2100-f64f-11e9-8842-8f8e31c0a8e1.png">

**Comment by davisagli** [comment]
The actual problem is that there isn't a release yet. The InstallPackageVersion task should print a more helpful message in this case rather than a generic 404.

**Comment by davisagli** [comment]
Fixed in #1621
