### ISSUE TITLE
CCI org list falsely displays scratch orgs as persistent orgs 

### ISSUE THREAD

**Issue by jofsky** [SFDO-Tooling/CumulusCI#1282]
When executing the cci org connect --sandbox <username> is used, cci org list falsely displays sandbox and scratch orgs as persistent orgs.

<img width="1187" alt="Screen Shot 2019-10-24 at 11 27 13 AM" src="https://user-images.githubusercontent.com/28512644/67514600-d9e5a300-f651-11e9-8849-96576868306c.png">

**Comment by davisagli** [comment]
Sandboxes are persistent orgs; the issue is that we aren't recognizing scratch orgs and setting the org config's `scratch` setting to true.
