### ISSUE TITLE
Documentation for adding fields to managed (npsp) objects within an unmanaged package

### ISSUE THREAD

**Issue by allisonletts** [SFDO-Tooling/CumulusCI#1303]
I heard from @jlantz that this is possible, but I can't find any documentation around it.
My typical (pre-cci) workflow as a consulting partner is this:

1. Get access to an NPSP-based org
2. Add fields to NPSP objects, like Affiliations and Relationships (as well as adding new fields to standard objects and adding new custom objects)
3. Deploy as needed

Here's my problem. Using CCI or regular SFDX, I can't figure out how to push the source for the fields where the object is namespaced. Example error message: 
`force-app\main\default\objects\npsp__Address__c\fields\Chapter_Code__c.field-meta.xml`
                 `Entity 'npsp__Address__c' not found. (3:13)`

What's the best way to manage this?

EDIT: to be clear, I get this error after installing dependencies and checking them in the org.

**Comment by jlantz** [comment]
I'm not quite sure why this error would be occurring.  I just tested and was able to accomplish this with the following steps:

1. Create a new git repository and change directory into it.  On OS X the commands are:
```
mkdir NPSP_Address_Field
cd NPSP_Address_Field
git init
```
2. Initialize the repository for CumulusCI using sfdx source format and select to extend NPSP
```
cci project init
```
3. Create the scratch org with NPSP installed and log into the org
```
cci flow run dev_org --org dev
cci org browser dev
```
4. Create a Chapter_Code__c field on the Address object.  I didn't select to add it to layouts or grant permissions in profiles just to keep it simple
5. Pull changes from the org using either cci or sfdx
```
cci task run dx_pull --org dev
OR
sfdx force:source:pull -u NPSP_Address_Field__dev
```
6. Try to deploy using either cci or sfdx
```
cci task run dx_push --org dev
OR
sfdx force:source:push -u NPSP_Address_Field__dev
```
7. Delete the scratch org and try with a fresh scratch org using cci
```
cci org scratch_delete dev
cci flow run dev_org --org dev
```

**Comment by allisonletts** [comment]
Yeah, so the issue I've come across is in step 7. Is that working for you?

**Comment by allisonletts** [comment]
also, I'm using the SFDX model, if that matters.

**Comment by allisonletts** [comment]
I found the source of my bug (github service not set up correctly). I'm going to close this and open a new issue if I'm still having trouble later. Thanks, @jlantz !
