### ISSUE TITLE
Trial Template - 400 Bad Request when accessing Advanced Mapping

### ISSUE THREAD

**Issue by mbeaty-sf** [SFDO-Tooling/CumulusCI#1307]
Immediately after creating a Trial org, from the Trial definition file, in NPSP Settings > System Tools > Data Import Advanced Mapping > Configure Advanced Mapping button causes error:

_400 Bad Request
You do not have access to the Apex class named 'BDI_ManageAdvancedMappingCtrl'._

and none of the Object mappings load.

![image](https://user-images.githubusercontent.com/53280203/68048256-6e2cb700-fc9d-11e9-996d-102804ac5f37.png)

**Steps to Create**

1. Create a scratch org from the _Trial_ definition
2. Once created go to _NPSP Settings > System Tools > Dat Import Advanced Mapping > Configure Advanced Mapping_  and toggle the feature **ON**
3. Once activated, click on the _Configure Advanced Mapping_ button
4. Encounter error

**Comment by davisagli** [comment]
@mbeaty-sf Can you report this to the NPSP team? I don't think it's a CumulusCI issue.

**Comment by mbeaty-sf** [comment]
@davisagli will do, but the reason I thought this was possible a CCI issues before, was because creating a trail org through the NPSP sign-up https://www.salesforce.org/trial/npsp/ did not exhibit the same behaviour.
