### ISSUE TITLE
Do not overwrite existing project files during init

### ISSUE THREAD

**Issue by acrosman** [SFDO-Tooling/CumulusCI#1325]
Currently when you run `cci project init` it generates `README.md` and `.gitignore` files, which is great if you are setting CCI for the first time in a new project.  But if you are trying to add CCI as tooling for an existing project it may overwrite wanted files.
It would be better if these files were only generated when missing, or probably better still to be a question during init that checks for existing files, and when found, asks if the user wants to replace, ignore, or append the content.

**Comment by jlantz** [comment]
This makes sense to me.  We do something like you're requesting with the sfdx-project.json where we only generate the file if it's not there.

**Comment by jlantz** [comment]
Relevant code to be changed:
https://github.com/SFDO-Tooling/CumulusCI/blob/master/cumulusci/cli/cci.py#L487-L491
