### ISSUE TITLE
Hitting sqlite3 variable limit on extract_dataset

### ISSUE THREAD

**Issue by acrosman** [SFDO-Tooling/CumulusCI#1355]
While trying to build a demo dataset from an org that has ~600 records in a custom object, CCI exceeds the sqlite3 variable limit of 999.

After building connecting cci to the org with sample records we ran the following pair of commands (Using cci 3.1.2):

```
cci task run generate_dataset_mapping --org demo
cci task run extract_dataset --org demo
```

The object that triggers the error has 10 fields in the generated mapping file, and the soql query returns 611 records (but any combination of [field count] X [record count] > 999 should reproduce this).  For the insert query generated for the import into the sqlite database that will generate a query with roughly 6110 variables, well over the hard coded limit.

The error is triggered by the CSV handler here: https://github.com/SFDO-Tooling/CumulusCI/blob/master/cumulusci/tasks/bulkdata/utils.py#L117

Instead of loading all the rows of the data file and dumping them into the insert statement, some care needs to be taken to break it up. Arguably sqlalchemy should protect against this better, but clearly they don't.

**Comment by davidmreed** [comment]
@acrosman Paul and I did a lot of work on the data loader over the last someodd months and this issue might or might not have been fixed along the way. I tried repeatedly to reproduce it and couldn't do so. Any chance you can repro it on the latest CumulusCI?

**Comment by acrosman** [comment]
I've noticed that you all have been busy with the data.  Thanks!

I'll see if I can find an org that matches the conditions I can use to re-test.  Not even sure anymore which project I was pulling that from.  But I need to learn SnowFakery a bit more anyway, so maybe I'll spin something up that way.

**Comment by davisagli** [comment]
Closing this for now -- if someone runs into this again, feel free to re-open.
