### ISSUE TITLE
New command proposal: cci org history

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/CumulusCI#1448]
It would be useful to have a command to list what commands have been run against an org on this computer. Helps the user to remember whether they've created the org but not configured it, or if they've configured it, have they uploaded test data? etc.

I envision it as simple:

cci org history dev

And it would output something similar to bash history.

**Comment by Br4nd0R** [comment]
@prescod - I'd love to look into the possibility of doing this. Would make sense to store some sort of .json file under `~/.cumulusci/`.

**Comment by prescod** [comment]
I realized after a day or so that it may also be important to store some indication of whether the command succeeded or failed. The user's goal is to understand the state of the org more than the specific commands that were run against it.

I do think it would add a lot of value to have at least a 1-word or 1-line summary of whether the command succeeded or not. 

Maybe there could also be a --verbose mode that would show the last 10 lines of the output??? That's a nice to have.

**Comment by Julian88Tex** [comment]
Maybe this is assumed but I'll also throw in there that it would be great to know if the command included any options when it was run.
