### ISSUE TITLE
Make `cci gist` title include date/time when log was made

### ISSUE THREAD

**Issue by TheBitShepherd** [SFDO-Tooling/CumulusCI#1467]
The title of gists currently includes `datetime.utcnow()`; however, this occurs upon the creation of the GitHub gist, not when the command associated with the contents of the gist was run.

It would be good to have datetime values of when commands were run to help with troubleshooting issues.

**Comment by davisagli** [comment]
@Br4nd0R can we just use the creation date of the logfile?

**Comment by Br4nd0R** [comment]
That's what I was thinking would be easiest to grab.
