### ISSUE TITLE
cci task info on AnonymousApex task display a parsing error when the apex has a ">"

### ISSUE THREAD

**Issue by force2b** [SFDO-Tooling/CumulusCI#1497]
Error:
```
$ cci task info enable_incremental_rollups
<string>:17: (WARNING/2) Inline strong start-string without end-string.
<string>:18: (WARNING/2) Bullet list ends without a blank line; unexpected unindent.
enable_incremental_rollups

  Description: Configure NPSP Customizable Rollups to activate Incremental Rollups (unmanaged deploys only)

  Class:: cumulusci.tasks.apex.anon.AnonymousApexTask

  Use the apex option to run a string of anonymous Apex. Use the path option to run anonymous Apex from a file. Or use both to concatenate
  the string to the file contents.

  Options:

      • path: The path to an Apex file to run.
      • apex: A string of Apex to run (after the file, if specified). **Default:
      STG_SettingsService.stgService.stgCRLP.AccountHardCreditNonSkew_Incremental__c = true;
      STG_SettingsService.stgService.stgCRLP.ContactHardCreditNonSkew_Incremental__c = true; STG_SettingsService.stgService.saveAll();
      Inline strong start-string without end-string.

    Bullet list ends without a blank line; unexpected unindent.

    ** * managed: If True, will insert the project's namespace prefix. Defaults to False or no namespace. * namespaced: If True, the tokens
    %%%NAMESPACED_RT%%% and %%%namespaced%%% will get replaced with the namespace prefix for Record Types
```

After some experimentation it only happens with this as the option `apex: >`. For example, `cci task info enable_customizable_rollups` displays fine, `cci task info enable_incremental_rollups` shows the error. The only real difference (besides multiple lines) is the `>`. I even edited the first one to add the > and that generated the error when running info on it.
![image](https://user-images.githubusercontent.com/801017/73016794-91728880-3dec-11ea-83f0-88abbf2a000e.png)

**Comment by Br4nd0R** [comment]
This particular tasks output can be mitigated by using a [block chomping indicator](https://yaml-multiline.info/). Use `>-` in place of just `>`. 

The other problem is that yaml doesn't seem to like extra indents found in the larger code block. I'm not sure if this would just be a limitation of the yaml format or something we could workaround...

**Comment by force2b** [comment]
Not 100% sure this is fixes the issue. For example adding the "-" for one of my new tasks generates the following. The formatting still looks odd. I think it's because it's trying to display the entire block of apex in the middle of the "info".

![image](https://user-images.githubusercontent.com/801017/73025410-8a07ab00-3dfd-11ea-92aa-a22fdc735753.png)

**Comment by davisagli** [comment]
@Br4nd0R I think it would be best to fix this in the doc_task util so that we can avoid the warnings for any option that happens to have a multiline default value. The fix I have in mind is to truncate the value at the first newline and show some indicator that the value has been truncated.
