### ISSUE TITLE
Allow setting the --debug option via config or environment variables

### ISSUE THREAD

**Issue by jstvz** [SFDO-Tooling/CumulusCI#1499]
Setting the `--debug` option will output tracebacks to stdout. Some users, especially active task/flow developers, will always want tracebacks to appear. An environment variable, `CCI__CLI__DEBUG`, should control this behavior.

**Comment by boakley** [comment]
Out of curiosity, why the double underscores?

**Comment by jstvz** [comment]
It's the format [suggested by davisagli](https://github.com/SFDO-Tooling/CumulusCI/pull/1136#issuecomment-557681723) in #1136 to allow mapping from configuration values to environment variables.

**Comment by jstvz** [comment]
Fixed by #1836
