### ISSUE TITLE
Handle patch release workflow

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#15]
The process for handling patch releases was considered but has not yet been implemented.  Since NPSP 3.0 is deployed to everyone at once and we isolate all work in feature branches, we can easily cut new releases and push out for any issues that come up.  Thus, we've never needed to do patch upgrades.

However, many projects face customer demands that require use of the patch release process.  The solution is to create a branch to track the patch changes and ensure any fixes which need to be included in master get included.  This probably means adding new build targets and automation scripts to support the process, however much of the existing process should be able to be leveraged for patch releases.

**Comment by cdcarter** [comment]
CCI Flow doesn't use patch orgs/we don't recommend our users use them at this time. Our tooling is not optimized, YMMV. Perhaps someday, when we have muchmore bandwidth...and 2GP hasn't changed it all by then...
