### ISSUE TITLE
MaxListenersExceededWarning for every command

### ISSUE THREAD

**Issue by koenwesselman** [SFDO-Tooling/CumulusCI#1508]
I'm getting the following error for every command I run:
`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit`

In some cases it breaks the command, as it is trying to parse some result and then ends up in an infinite loop where it doesn't seem to be able to parse it correctly due to that error being at the bottom.

**Comment by jstvz** [comment]
Hi @koenwesselman. This is an SFDX issue (you should see it when running `sfdx` directly) was reported as fixed upstream (forcedotcom/cli#216), so I'd suggest starting with `sfdx update` to see if that resolves your issue. Feel free to re-open if you're still seeing it only when running `cci`.
