### ISSUE TITLE
Add Access Token to `cci org info` command

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#1566]
Currently, the `cci org info` command contains a lot of info similar to `sfdx force:org:display` but one thing that is missing is the Access Token. Having the Access Token in this command comes in handy often when doing things like API testing.

**Comment by Julian88Tex** [comment]
I suspect access token was admitted due to size. Alternatively, I created a PR to update help text so it's clear that JSON option includes access token.

https://github.com/SFDO-Tooling/CumulusCI/pull/1567

**Comment by davisagli** [comment]
It was omitted intentionally because we were concerned about the risk of accidentally exposing the access token in public CI logs.

**Comment by Julian88Tex** [comment]
@davisagli I see. Hm, seems like sfdx display command would have same risk but they left it for some reason. If that's the case then the PR I created shouldn't cause that situation.
