### ISSUE TITLE
Windows: Not able to create a gist with a successful flow output

### ISSUE THREAD

**Issue by annejackson** [SFDO-Tooling/CumulusCI#1619]
Per @davisagli - looks like we're not handling special characters correctly on Windows.

steps:
1. Run a flow in a repo and it completes successfully 
2. Try to share the flow so can see tasks run with someone by creating a gist
3. Run `cci error gist`
Get an error:
Error: 'charmap' codec can't decode byte 0x90 in position 117552: character maps to <undefined>

See full output here (had to manually create this gist)
https://gist.github.com/annejackson/aef0088833f7f59e5362cecd7bd03e3d

**Comment by prescod** [comment]
Thanks for the report. I remember that Brandon had some big challenges with character support on Windows. I will work with him on this when he gets back.
