### ISSUE TITLE
Error 404 when publishing to MetaDeploy

### ISSUE THREAD

**Issue by ricxsar** [SFDO-Tooling/CumulusCI#1620]
I was trying to publish Cumulus experiment project to MetaDeploy but it returns an error.
```
cci task run metadeploy_publish -o commit 0ff6caa58a33370e62334c30485061f4f8a24aba -o plan install
2020-03-17 18:37:18: Beginning task: Publish
2020-03-17 18:37:18: 
2020-03-17 18:37:20: Found https://metadeploy-experiment.herokuapp.com/admin/rest/versions/L929nqz
2020-03-17 18:37:20: Downloading commit 0ff6caa58a33370e62334c30485061f4f8a24aba of ricxsar/cumulus-experiment from GitHub
2020-03-17 18:37:23: Processing dependencies from Github repo https://github.com/SalesforceFoundation/NPSP
2020-03-17 18:37:27: Processing dependencies from Github repo https://github.com/SalesforceFoundation/Households
2020-03-17 18:37:30: Processing dependencies from Github repo https://github.com/SalesforceFoundation/Contacts_and_Organizations
2020-03-17 18:37:34: Processing dependencies from Github repo https://github.com/SalesforceFoundation/Recurring_Donations
2020-03-17 18:37:37: Processing dependencies from Github repo https://github.com/SalesforceFoundation/Relationships
2020-03-17 18:37:40: Processing dependencies from Github repo https://github.com/SalesforceFoundation/Affiliations

Error: 404 Not Found
Type `cci error --help` for more information about debugging errors.
```

GitHub: `https://github.com/ricxsar/cumulus-experiment.git`
Cumulus Version: 
```
cci version
CumulusCI version: 3.9.0 (C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\Scripts\cci)
Python version: 3.8.1 (c:\users\admin\appdata\local\programs\python\python38-32\python.exe)

You have the latest version of CumulusCI.
```

**Comment by prescod** [comment]
Can you please try again and when you are done type "cci error info" or "cci error gist"? Thank you.

**Comment by ricxsar** [comment]
Gist: https://gist.github.com/ricxsar/02f1c031f381b4219d1fe4a2ac19b350
I have already authenticated the cumulus to my github account with repo and gist permissions

**Comment by davisagli** [comment]
Hi @ricxsar, it looks like the install plan you are publishing includes a step with the install_managed task, which installs the latest release of your project. In order to find the latest release it looks for the latest release in github, then uses the tag from that release to determine the Salesforce package version. Have you made a release of the cumulus-experiment managed package by running the release_production flow? If not, you may have more success trying MetaDeploy with a plan that does not try to install your package as a managed release.

**Comment by davisagli** [comment]
@ricxsar I've merged a fix which will be in the next release to show a more helpful error message in this scenario: https://github.com/SFDO-Tooling/CumulusCI/pull/1621

**Comment by ricxsar** [comment]
@davidmreed Thanks. I will try to create a release and get back to you if it is resolved.

**Comment by ricxsar** [comment]
@davisagli I hit an error when publishing the release to MetaDeploy. It seems that Metadeploy needs some fields to be filled.
https://gist.github.com/ricxsar/ef85cc6c503969c38c585bccfd3f1bca

`Error: b'{"preflight_message":["This field is required."],"post_install_message":["This field is required."],"error_message":["This field is required."]}'`

Where should I specify the `preflight_message`, `post_install_message` and `error_message`?

I make the repository public for now for you to have access.

Sorry for the inconvenience.

**Comment by davisagli** [comment]
This is not something you are doing wrong; this is a bug we need to fix in the metadeploy_publish task in CumulusCI. The new fields were added to the MetaDeploy API as required fields but CumulusCI is not sending them yet. Sorry for the inconvenience; we'll try to get a fix out soon.

**Comment by ricxsar** [comment]
@davisagli It's fine. This is for the experiment anyways. Currently, we have multiple managed packages right now including NPSP on our bundle and we would like our clients to preview it on their own.

I think this would be a better approach. Also planning to migrate our development and release methodology to Cumulus, currently it is pure `SFDX` with custom scripts and external builds (pipelines)

**Comment by davisagli** [comment]
The error about missing required fields should be gone with latest versions of CumulusCI and MetaDeploy.
