### ISSUE TITLE
Fix handling of long file paths on Windows

### ISSUE THREAD

**Issue by miteshmsharma** [SFDO-Tooling/CumulusCI#1626]
While attempting to complete the trailhead module for cumulusci-for-postinstall-customizations I ran into strange issue which @davisagli  attributed to an issue relating to CumulusCI not able to take input > 255 on windows but the error I received had no mention of this fact and I was getting something like 
Error: [Errno 2] No such file or directory: '.cci\projects\NPSP\a7a239223ce04ed37caa877a9e5f00117ce3b297\unpackaged\config\regression_bdi_custom_metadata\customMetadata\npsp__Data_Import_Field_Mapping.Account1_State_Province_843b0878f.md'
Type cci error --help for more information about debugging errors.

Not in my wildest dream I would have associated it to be related to length of inputs and hence changing the project path to be less in size. 

Can this be fixed so there are meaningful error messages shown to the developers?

**Comment by davisagli** [comment]
In the case of this specific error, I'd rather fix it so that we successfully handle long paths. That is in our backlog.

**Comment by davidmreed** [comment]
Current versions of CumulusCI will warn the user about required configuration if Windows long pathname support is not enabled.
