### ISSUE TITLE
Typo related to cumulusci.core.tasks vs cumulusci.tasks 

### ISSUE THREAD

**Issue by sfdcale** [SFDO-Tooling/CumulusCI#1653]
Example given here (https://cumulusci.readthedocs.io/en/latest/cookbook.html#query-the-enterprise-api-for-data) produces the below error :

**Error: No module named 'cumulusci.core.tasks.salesforce'; 'cumulusci.core.tasks' is not a package**

Import statement should be changed from 

```python
from cumulusci.core.tasks.salesforce import BaseSalesforceApiTask
```
to

```python
from cumulusci.tasks.salesforce import BaseSalesforceApiTask

```

**Comment by davisagli** [comment]
Thanks; fixed.
