### ISSUE TITLE
Provide the option to use REST API for dataset tasks

### ISSUE THREAD

**Issue by sfdcale** [SFDO-Tooling/CumulusCI#1662]
Command `$ cci task run extract_dataset -o mapping datasets/mapping.yml -o sql_path datasets/data.sql --org devsandbox`

throws the below error if `mapping.yml` has definitions for binary fields of objects like (Attachment,ContentVersion,ContentDocument etc..)

> **2020-04-09 17:02:54: Batch failure message: FeatureNotEnabled : Binary field not supported**
> 
> **Error: Unable to execute query: FeatureNotEnabled : Binary field not supported**

Here is the help article about this error: https://help.salesforce.com/articleView?id=000315523&type=1&mode=1

Provide the option to use regular REST API.

**Comment by prescod** [comment]
The help article says: "If you disable Bulk API, these fields can be exported but will return only the encoding details and not the actual file uploaded into Salesforce."

Is that actually useful for your use-case?

**Comment by sfdcale** [comment]
@prescod  That help article is written specifically for Dataloader tool. In Dataloader, we have the option to not use Bulk API and we need similar setting/flag in CumulusCI.

**Comment by prescod** [comment]
Sorry I was unclear. What I meant to ask is:

What would you like CumulusCI to do if the setting says "do not use Bulk API" but there are binary fields? Should it do what DataLoader does? Or convert the binary to text and inline it? Or separately download the actual binary attachments?

**Comment by sfdcale** [comment]
@prescod  Based on what I am seeing in CumulusCI code base, it is using [simple salesforce python library](https://github.com/simple-salesforce/simple-salesforce) to query from and push data into Salesforce. 

This library supports both regular REST API and Bulk API to talk to Salesforce.  CumulusCI is always using the Bulk API option and it should give the option to user to use regular REST API.

I posted same on CumulusCI trailblazer community and here is the post:  https://success.salesforce.com/0D53A00004riOQU

**Comment by sfdcale** [comment]
@prescod  If CumulusCI can download these binary files,I would expect it to download the binary as is and store in a separate folder.

**Comment by davidmreed** [comment]
This is not just about REST versus Bulk APIs but also about our underlying data storage implementation. 

Adding REST API support is definitely on our roadmap and has a large number of use cases. However, REST API support does not necessarily come with support for binary blobs. Supporting binary blob fields is something I think we'd like to do but is not at the top of the priority list for bulk data tooling.

**Comment by davidmreed** [comment]
REST API support has been added as of CumulusCI 3.19.1. However, CumulusCI does not support binary blobs in any data API.
