### ISSUE TITLE
How to create a custom task that can run against two orgs

### ISSUE THREAD

**Issue by sfdcale** [SFDO-Tooling/CumulusCI#1668]
I have a unique case where functionality of `extract_dataset` and `load_dataset` tasks are not sufficient. So, I started writing a custom task and stuck with this.  

Let's assume `$ cci org list` gives this output:
```

┌Connected Orgs───┬───────────────────────────────────────────────┬────────────┐
│ Name            │ Default │ Username                            │ Expires    │
├─────────────────┼─────────┼─────────────────────────────────────┼────────────┤
│ UAT             │         │ uatsandboxusername@acme.com         │ Persistent │
├─────────────────┼─────────┼─────────────────────────────────────┼────────────┤
│ devsandbox      │ ✔       │ devsandboxusername@acme.com         │ Persistent │
└─────────────────┴─────────┴─────────────────────────────────────┴────────────┘
```

I want to create a custom task which can be run as below:
`$ cci task run dummyTask -o baseOrgName UAT`
```
from cumulusci.tasks.salesforce import BaseSalesforceApiTask

class dummyTask(BaseSalesforceApiTask):
    api_version = "46.0"
    task_options = {
        "baseOrgName": {
            "description": "Org to use for querying data from",
            "required": True,
        }
    }
        
    def doSomething(self):

        # THIS IS WHERE I AM STUCK
        # point self.sf to baseOrgName parameter passed.

        # Query some data
        res = self.sf.query('SELECT Id FROM Account')

        # point self.sf to default org.

        # update some data 
        res = self.sf.update(accData)

    def _run_task(self):
        self.doSomething()

```

I spent hours doing reverse engineering on how to point `self.sf` to the org I want but with no success.

**Comment by davisagli** [comment]
You don't need to add the `baseOrgName` option; every task extending BaseSalesforceApiTask can already be used with any org. Run with this command:

    cci task run dummyTask --org UAT

and `self.sf` will be pre-authorized for the UAT org.

**Comment by sfdcale** [comment]
@davisagli  Thanks for the reply. But in the same task, I want to switch `self.sf` to default org. How can I do that?

**Comment by davidmreed** [comment]
How are `extract_dataset` and `load_dataset` insufficient?

**Comment by davisagli** [comment]
@sfdcale Sorry, I missed that you want to access two different orgs in the same task. I don't think we have any established precedent for this but it should be possible with something like this:

    from cumulusci.salesforce_api.utils import get_simple_salesforce_client

    base_org = self.project_config.keychain.get_org(self.options["baseOrgName"])
    base_org.refresh_oauth_token(self.project_config.keychain)
    sf = get_simple_salesforce_client(self.project_config, base_org)

**Comment by sfdcale** [comment]
Thanks @davisagli .  I will try this.

@davidmreed  Here is my requirement at very high level:

1. Query `KnowledgeArticleVersion` data from UAT sandbox as per mapping.yml -- solved this using `extract_dataset`(There are few record which I could not retrieve because of issue [1662](https://github.com/SFDO-Tooling/CumulusCI/issues/1662)) 
2. Load `KnowledgeArticleVersion` data into dev sandbox as per mapping.yml  -- solved this using `load_dataset` (Ran into bulk batch character limit, posted it on community. In the meanwhile, hacked it by updating batchsize in cumulusci/tasks/bulkdata/step.py to 100  ) 
3. Publish 'KnowledgeArticleVersion' records loaded though [KbManagement REST API](https://developer.salesforce.com/docs/atlas.en-us.knowledge_dev.meta/knowledge_dev/apex_KbManagement_PublishingService_publishArticle.htm). -- For this I am using a custom task.
4. Query `KnowledgeArticle` table from UAT sandbox and get the corresponding `KnowledgeArticle` Id from dev sandbox(matching with article title and url).
5. Populate those article Ids in a different table.

I want to implement steps 4 and 5 using a single custom task but stuck on how to switch `self.sf` between different orgs.

**Comment by sfdcale** [comment]
@davisagli   That code snippet you gave worked. Closing the issue.
