### ISSUE TITLE
Managed directory for CCI subsystems to cache data

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/CumulusCI#1677]
In ~/.cumulusci there could be a directory called "orgdata"

Each subdirectory of orgdata could be associated with a particular org by ORGID.

Any subsystem of CCI could cache data in there as files, directories or SQLite DBs (which are just files).

When the org is destroyed explicitly, the orgdata could be cleaned up.

If the org is discovered to be disconnected or expired (e.g. in cci org list), the orgdata could be cleaned up.

Types of things we might cache there:

 * log of commands executed against the org
 * serialized describe() schema of the org
 * OID->ID mapping
 * ...

**Comment by davisagli** [comment]
Added in cumulusci 3.18.0
