### ISSUE TITLE
cci 3.8.0 not working for Non DX Orgs

### ISSUE THREAD

**Issue by jhgihub0** [SFDO-Tooling/CumulusCI#1678]
This is a continuation of https://github.com/SFDO-Tooling/CumulusCI/issues/1471, which was closed with no resolution.  Specifically look at my comments "jhgihub0 commented on Jan 16"

We are still facing the same issue with version 3.8.0.  We are running cci tests on regular Sandboxes, not scratch orgs.  To get it work, we have to edit /usr/local/lib/python3.7/site-packages/cumulusci/cli/cci.py and comment out line 912 and 913. See screenshot 
![screenshot](https://user-images.githubusercontent.com/59979805/79472642-175c3500-7fd2-11ea-87d8-18ce2480e1d6.jpg)

If we don't comment out line 912 and 913, we get the error:
Error: 'NoneType' object is not subscriptable

Please advise if there is a way to use cci on regular sandboxes.

**Comment by davisagli** [comment]
@jhgihub0 The `cci org import` command currently supports scratch orgs only. Have you tried the suggested steps for connecting a persistent org from my comment on that thread? https://github.com/SFDO-Tooling/CumulusCI/issues/1471#issuecomment-575212718

**Comment by jhgihub0** [comment]
I tried that before, and tried again now, and it does not work.

**Comment by davisagli** [comment]
@jhgihub0 can you show us the commands you are running and the output?

**Comment by jhgihub0** [comment]
@davisagli 

Before we set up the Jenkins job that runs our automated tests, we generated the force URL of our persistent sandbox by running these commands:
sfdx force:auth:web:login --setalias OrgAlias --instanceurl https://test.salesforce.com
sfdx force:org:display -u OrgAlias –verbose
![2020-04-20_14-53-37](https://user-images.githubusercontent.com/59979805/79788942-6dedaa00-8317-11ea-97cf-9c0fe750bd8e.jpg)
sfdx force:auth:logout --targetusername OrgAlias --noprompt

We then store the force:// URL in sfdx_login_force.txt

In our Jenkins job we do this to log into the persistent org:
sfdx force:auth:sfdxurl:store --sfdxurlfile sfdx_login_force.txt --setalias orgAlias –setdefaultusername

With CCI version 3.8.0 installed, I run “cci org import orgAlias orgAlias”

It fails with: "Getting scratch org info from Salesforce DX.  Error: 'NoneType' object is not subscriptable"

I cannot run "cci org info orgAlias --json", because it wants me to be authenticated first, and 'cci org import' fails.

The only way to get it to work and run tests is to comment line 912 and 913 of cumulusci/cli/cci.py after each upgrade
![2020-04-20_15-02-54](https://user-images.githubusercontent.com/59979805/79789377-13a11900-8318-11ea-97df-87862318899d.jpg)

**Comment by davisagli** [comment]
@jhgihub0 That is not the process I recommended in my comment on the other thread. As I said above, `cci org import` only supports scratch orgs.

I will repeat my recommended steps because it sounds like you have not tried them yet:
1. Connect the org on your own computer using `cci org connect orgalias` (this adds the org to CumulusCI's keychain but not to sfdx's keychain)
2. Run `cci org info orgalias --json` to get the org's configuration as JSON, including its oauth2 refresh token.
3. In the configuration for your Jenkins job, the CI environment, make sure the CUMULUSCI_KEYCHAIN_CLASS environment variable is set to cumulusci.core.keychain.EnvironmentProjectKeychain. This uses an alternate keychain that gets org and service config information from environment variables instead of files.
4. In the configuration for your Jenkins job, set the CUMULUSCI_ORG_orgalias environment variable to the JSON from step 1.

**Comment by jhgihub0** [comment]
I cannot use "cci org connect orgalias", because it tries to spawn a browser window.

These tests are running on a headless AWS Redhat Linux node that has no UI.  That's why we need to use cci org import" or something else.

**Comment by davisagli** [comment]
@jhgihub0 steps 1 and 2 are for you to do once on your local machine where you have access to the browser. They give you some JSON which you will configure in an environment variable on the headless system for use each time the job runs there.

**Comment by jhgihub0** [comment]
On my Mac, after typing "cci org connect orgalias", and logging in, I get.  I tried two different development orgs

![2020-04-20_16-32-08](https://user-images.githubusercontent.com/59979805/79797074-9fb93d80-8324-11ea-9c6f-b11c21ec0e48.jpg)

**Comment by davisagli** [comment]
@jhgihub0 you'll need to use `cci org connect orgalias --sandbox` since you are logging in to a sandbox, so that it opens the login form on test.salesforce.com instead of login.salesforce.com

**Comment by jhgihub0** [comment]
Okay, so I ran "cci org connect orgalias --sandbox" on my local, got the content and saved it as file.json

Then in my automation job I run:

CUMULUSCI_KEYCHAIN_CLASS=cumulusci.core.keychain.EnvironmentProjectKeychain
CUMULUSCI_ORG_orgalias=file.json
cci task run robot -o include PreDeployment -o vars BROWSER:headlesschrome --org orgalias

It gives error:

Error: Org information could not be found. Expected to find encrypted file at /home/user/.cumulusci/project_SF_AutoTest/3.org

**Comment by davisagli** [comment]
The error mentioning an encrypted file means that CumulusCI is not actually using the EnvironmentProjectKeychain, so you probably are not setting the environment variable correctly. You might need to do `export CUMULUSCI_KEYCHAIN_CLASS=cumulusci.core.keychain.EnvironmentProjectKeychain` so that it is available to subsequent commands.

Also CUMULUSCI_ORG_orgalias needs to be set to the actual JSON, not the name of a file that contains the JSON.

**Comment by jhgihub0** [comment]
Updated:

export CUMULUSCI_KEYCHAIN_CLASS=cumulusci.core.keychain.EnvironmentProjectKeychain
declare CUMULUSCI_ORG_orgalias="$(<"file.json")"
cci task run robot -o include PreDeployment -o vars BROWSER:headlesschrome --org orgalias

Error:

Org named orgalias was not found in keychain

**Comment by jhgihub0** [comment]
Updated:

export CUMULUSCI_KEYCHAIN_CLASS=cumulusci.core.keychain.EnvironmentProjectKeychain
declare CUMULUSCI_ORG_orgalias="$(<"file.json")"
cci task run robot -o include PreDeployment -o vars BROWSER:headlesschrome --org orgalias

Error:

Org named orgalias was not found in keychain

**Comment by davisagli** [comment]
Replace the second line with:

    export CUMULUSCI_ORG_orgalias="$(<file.json)"

**Comment by davisagli** [comment]
You didn't change both of the things I fixed in line 2. You can't include double quotes inside a double-quoted string.

**Comment by jhgihub0** [comment]
That made no difference:

export CUMULUSCI_KEYCHAIN_CLASS=cumulusci.core.keychain.EnvironmentProjectKeychain
export CUMULUSCI_ORG_orgalias="$(<file.json)"
cci task run robot -o include PreDeployment -o vars BROWSER:headlesschrome --org orgalias

Error:

Org named orgalias was not found in keychain

**Comment by prescod** [comment]
Hello. Can you please look at those variables and verify that they are properly set?

echo $CUMULUSCI_KEYCHAIN_CLASS
echo $CUMULUSCI_ORG_orgalias

Please do not share the output here, because it will have private information in it.

But your error message is consistent with CUMULUSCI_ORG_orgalias being blank so perhaps it is not being set in the right subshell.

If you replace your cci task run command with "echo $CUMULUSCI_ORG_orgalias" do you see JSON or do you see nothing?

**Comment by jhgihub0** [comment]
The echo prints fine

echo $CUMULUSCI_KEYCHAIN_CLASS
echo $CUMULUSCI_ORG_orgalias

![2020-04-22_17-32-46](https://user-images.githubusercontent.com/59979805/80036277-6e28a980-84bf-11ea-890b-91885a131b2c.jpg)

**Comment by Br4nd0R** [comment]
@jhgihub0 - I went ahead and removed your last comment because it contained information that should be kept private.

**Comment by jhgihub0** [comment]
Thanks, but that was not necessary. It was only a partial screen shot with less than 3rd of the key. In any way, the variables are populated properly, and I still get the error

**Comment by prescod** [comment]
I'm sort of stumped. I'm not sure if it is a hint or a red herring but your screenshot showed JSON being "double encoded". That could just be a side effect of how you captured the screenshot.

Can you confirm that these commands DO work on your local laptop but DO NOT work in Jenkins?

```
export CUMULUSCI_KEYCHAIN_CLASS=cumulusci.core.keychain.EnvironmentProjectKeychain
export CUMULUSCI_ORG_orgalias="$(<file.json)"
cci task run robot -o include PreDeployment -o vars BROWSER:headlesschrome --org orgalias
```

**Comment by jhgihub0** [comment]
Same issue doing it on my Mac

![2020-04-27_12-30-38](https://user-images.githubusercontent.com/59979805/80396690-012c5f80-8883-11ea-8a48-c75a04e1da87.jpg)

**Comment by prescod** [comment]
I'm my laptop I tytpe:

cci org info --json SomeOrg > /tmp/SomeOrg.json

Then I open /tmp/SomeOrg.json in a text editor to verify that it looks like roughly valid JSON with nothing strange at the top or bottom. Copy the JSON to the clipboard.

Then I SSH into another computer.

And I do this:

```$ cat > file.json
```

And I paste the json into that window and hit Ctrl-D.

Still in the SSH to the remote server, I run these commands:
```
export CUMULUSCI_KEYCHAIN_CLASS=cumulusci.core.keychain.EnvironmentProjectKeychain
export CUMULUSCI_ORG_orgalias="$(<file.json)"
```
My server doesn't have a repo loaded so I fake it like this:

```
$ git init
$ touch cumulusci.yml
```
Then I run:

`` $ cci org shell orgalias --python "print(sf.base_url)"
```

And it prints the URL for my org.

**Comment by jhgihub0** [comment]
What happens when you type cci task run robot -o include PreDeployment -o vars BROWSER:headlesschrome --org orgalias

**Comment by prescod** [comment]
I don't have that tag, but yes the rest of the command works:

```
~ $ git clone https://github.com/SalesforceFoundation/NPSP.git
Cloning into 'NPSP'...
remote: Enumerating objects: 331, done.
remote: Counting objects: 100% (331/331), done.
remote: Compressing objects: 100% (222/222), done.
remote: Total 180184 (delta 211), reused 169 (delta 101), pack-reused 179853
Receiving objects: 100% (180184/180184), 123.00 MiB | 44.93 MiB/s, done.
Resolving deltas: 100% (136385/136385), done.

~ $ cd NPSP

~/NPSP $ cci task run robot -o vars BROWSER:headlesschrome --org orgalias
2020-04-29 10:32:43: Org info updated, writing to keychain
2020-04-29 10:32:43: Beginning task: Robot
2020-04-29 10:32:43:        As user: pprescod+abacus-ldv-scheduled-alpha@salesforce.com
2020-04-29 10:32:43:         In org: 00D6g000003tfpoEAA
2020-04-29 10:32:43: 
==============================================================================
Tests                                                                         
==============================================================================
Tests.Api                                                                     
==============================================================================
Tests.Api.Create Contact Api                                                  
==============================================================================
````

etc. etc.

**Comment by prescod** [comment]
@jhgihub0 : Okay to close this issue?

**Comment by jhgihub0** [comment]
No, I am still having to try the latest

**Comment by jhgihub0** [comment]
I got it to work. Thank you for all the help. You can close the ticket now
