### ISSUE TITLE
How to delete data from Org using CumulusCI?

### ISSUE THREAD

**Issue by sfdcale** [SFDO-Tooling/CumulusCI#1679]
I have a bash script that deletes data from org and I am trying to convert this into CumulusCI custom task as below but running into the error **Error: 'DeleteData' object has no attribute 'bulk'**

```
from cumulusci.tasks.salesforce import BaseSalesforceApiTask
from cumulusci.tasks.bulkdata.delete import DeleteData

class WipeExistingData(BaseSalesforceApiTask):


    def _run_task(self):
        self.task_config.options = dict(objects='FAQ__c')
        a = DeleteData(self.project_config,self.task_config)
        a._run_task()
```

Is this task not supposed to be extended in custom task? OR can you provide some sample code on how to get this working? 
cc: @davisagli @davidmreed

**Comment by davidmreed** [comment]
Typically you don't need to subclass that task. You specify options in `cumulusci.yml` to spec out what objects you want to delete and in what order. Here's an example in NPSP:

https://github.com/SalesforceFoundation/NPSP/blob/master/cumulusci.yml#L251

**Comment by sfdcale** [comment]
Thanks @davidmreed
