### ISSUE TITLE
Default Timezone to User's Local Machine on Scratch Org Creation

### ISSUE THREAD

**Issue by BrianKSFDO** [SFDO-Tooling/CumulusCI#1715]
I'm on the East Coast and every time I create a new scratch org I go into Company Information to update timezone to America/New_York.  I then go into the user "User, User" that was created for me and update that as well.  CCI (and/or SFDX) defaults to America/Los_Angeles which creates timezones that aren't local to me as a small NPO or SMB on the East Coast.

It would be a nice feature and time-saver to default timezones to match the user's local machine that is creating the scratch org.

**Comment by annejackson** [comment]
This would be helpful for SAL too (and us non Pacific time zone users)

**Comment by annejackson** [comment]
Where might this be in the backlog/priority list? @jstvz  @davisagli ?

**Comment by jstvz** [comment]
Logged as [W-8887075](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000096XVkIAM/view).
