### ISSUE TITLE
Feature Request: Add NPSP Locators file to CCI for easier robot test writing

### ISSUE THREAD

**Issue by acrosman** [SFDO-Tooling/CumulusCI#1722]
NPSP provides a really useful set of helper libraries to make it easier to write robots tests:

* https://github.com/SalesforceFoundation/NPSP/blob/master/robot/Cumulus/resources/NPSP.py
* https://github.com/SalesforceFoundation/NPSP/blob/master/robot/Cumulus/resources/locators_48.py

To write goods tests I've found myself copying and maintaining my own versions of those in my project, which means every SF platform release I have to go back and hunt up the new locators file from NPSP. 

It looks like the vast majority of that code is actually generic Salesforce not really NPSP specific. Therefore it seems like those helpers could be moved into CCI, to more easily benefit the whole community.

**Comment by davisagli** [comment]
@acrosman We do intend to move keywords that are not NPSP-specific over to CumulusCI, but so far that's been more intention than reality. What would be your top requests for which keywords to prioritize moving?

**Comment by acrosman** [comment]
`click_dropdown` was the show stopper that got me digging around for a solution.

The date related functions and modal forms are next on my todo list -- not testing things that need those on my project now cause I haven't had time to adapt NPSP's since I realized I didn't need to role my own solution.

**Comment by boakley** [comment]
click dropdown and the date keywords are all already scheduled to be worked
on this month.

**Comment by jstvz** [comment]
Fixed by #1768
