### ISSUE TITLE
Login as functionality in Salesforce for System Admin, not working in Google Chrome version 80+

### ISSUE THREAD

**Issue by jagadishkumarS** [SFDO-Tooling/CumulusCI#1738]
In my selesforce application, i need login to other salesforce users, using system admin login as functionality.

My Test Scenario:
Chrome Browser Version : 81
Org is setup with for System Admin.
Steps:
- Login to application using System Admin (Using "Open Test Browser" keyword)
- Navigate to any one of the Salesforce user (Say "David") details page
- Click 'Login' button on David's user details page.......(now "David" is logged in)
- Use any Salesforce keyword or CumulusCI keyword to do anything while David is logged in. Here nothing works. Tried to do operation with many keywords available in robotframework SeleniumLibrary and CumulusCI. None of it worked.

Solution:
After lot of google search, i decided to give try by downgrading the chrome version, to chrome 79. Then the keywords started working. I again upgraded to chrome version 81, keywords stopped working. Downgraded again...started working.

My observation:
Here is the keyword i am using to login to other users via system admin:

Login To User
	[Documentation]                 Login to the system admin first and then login to other SF users.
	[Arguments]			    ${Selected User}
	Open Test Browser
	Maximize Browser Window
	@{UserID}			    Salesforce Query    User  select=Id    Name=${Selected User}
	&{UserID}  			    Get From List	${UserID} 	0
	${User ID}		            Set Variable  	&{UserID}[Id]
	Go To Record Home            ${User ID}
	Wait For Aura
	Click Element                       title=User Detail
	Sleep  				    15  reason=Wait for page to load for elements
	Select Frame  		            //*[contains(@title, 'User:')]
	Click Element                       title=Login
	Wait Until Page Contains     Logged in as

Just come to "Select Frame" keyword. The iframe is selected, as the login button is located in iframe. Then click on login button on the next step. The next keyword (Wait Until Page Contains) is now to be performed on newly logged in users home page, which fails, even though page contains "Logged in as". Not only this keyword, but any other keyword from SeleniumLibrary as well as cumulusCI library fails. Nothing would be located, nothing would be clicked, on this newly logged user homepage.

Weird try:
1. I commented out the keywords for selecting the iframe, and click login button, to click in "Login" button manually.
    Result: now keywords works on user homepage
    This tell she problem is in this two lines:
    Select Frame  		         //*[contains(@title, 'User:')]
    Click Element                       title=Login

2. I commented "Click Element" keyword, and let "Select Frame" keyword in to select frame automatically.
   Result: Keywords stopped working on user homepage.
   This confined the problem to the one line:
   Select Frame  		         //*[contains(@title, 'User:')]

(Here is when i switched to chrome Version 79, then everything worked fine)

**Comment by davisagli** [comment]
This is just a wild guess, but does it help if you add `Unselect Frame` in between `Click Element title=Login` and `Wait Until Page Contains Logged in as` to make sure that it is looking at the top-level frame again?

**Comment by jagadishkumarS** [comment]
Hi @davisagli 
The solution given by you worked. Thank you very very much!!!

But still wonder, why is it not required to unselect frame in chrome 79 (or versions prior to 80).

Anyway, now i know the solution. Thanks again for help.  :)

**Comment by davisagli** [comment]
It might be related to this issue in chromedriver: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3353
