### ISSUE TITLE
cci 3.8.0 cci authentication in MS-DOS

### ISSUE THREAD

**Issue by jhgihub0** [SFDO-Tooling/CumulusCI#1742]
Hi, I am trying to do the same as https://github.com/SFDO-Tooling/CumulusCI/issues/1678 in MS-DOS batch.

I use these commands in batch:

set CUMULUSCI_KEYCHAIN_CLASS=%cumulusci.core.keychain.EnvironmentProjectKeychain%
set CUMULUSCI_ORG_orgalias=<Org.json
cci org shell orgalias --python "print(sf.base_url)"

But it fails

Error: Org information could not be found. Expected to find encrypted file at C:\Windows\system32\config\systemprofile\.cumulusci\MyTests/orgalias.org

What are the batch equivalent of what was discussed in https://github.com/SFDO-Tooling/CumulusCI/issues/1678 ?

Thank you

**Comment by davisagli** [comment]
I'm sorry but I don't quite understand what you are trying to do. If you are running CumulusCI interactively then you don't need to set these variables; you can just use the default keychain which stores org configuration in files. If you are running CumulusCI from a continuous integration system, then that CI system likely has documentation for its own preferred way to set environment variables for a CI job.

**Comment by jhgihub0** [comment]
This code runs in Jenkins on Windows node. There will be no UI.  I am trying to authenticate via command line to a persistent Salesforce Org, not a scratch org.

I generated the Org.json by typing these commands:

cci org connect orgalias --sandbox
cci org info --json orgalias > Org.json
cci org remove orgalias

In linux we use:

export CUMULUSCI_KEYCHAIN_CLASS=cumulusci.core.keychain.EnvironmentProjectKeychain
export CUMULUSCI_ORG_orgalias="$(<Org.json)"
cci org shell CUMULUSCI_ORG_orgalias --python "print(sf.base_url)"

I am trying to find the Windows bash equivalent.

Thank you.

**Comment by davisagli** [comment]
bash syntax should work the same whether bash is running on Linux or Windows. I suspect that on Windows, Jenkins is actually running commands using the Windows Command Prompt (cmd.exe) or Powershell rather than bash.

Have you tried setting the environment variables in the Jenkins pipeline rather than in a script? https://e.printstacktrace.blog/jenkins-pipeline-environment-variables-the-definitive-guide/

**Comment by jhgihub0** [comment]
At this time I am just trying to get it working in windows command line.... no Jenkins.  I even tried PowerShell:

$CUMULUSCI_KEYCHAIN_CLASS="cumulusci.core.keychain.EnvironmentProjectKeychain"
$CUMULUSCI_ORG_orgalias = Get-Content Org.json
cci org shell orgalias --python "print(sf.base_url)"

I get error: "Error: Org information could not be found. Expected to find encrypted file at D:\Users\User\.cumulusci\tests/orgalias.org"

It seems that the CUMULUSCI_KEYCHAIN_CLASS is not set properly.  I don't know how to set it, so it keep trying to look for the org and service config information from files instead of environment variables.

Any ideas how to set this in PowerShell?

**Comment by davisagli** [comment]
For PowerShell it looks like this might work (but I don't have easy access to Windows to try it):

    $env:CUMULUSCI_KEYCHAIN_CLASS="cumulusci.core.keychain.EnvironmentProjectKeychain"
    $env:CUMULUSCI_ORG_orgalias="$(Get-Content -Path .\Org.json)"

To view the current environment variables you can use:

    Get-ChildItem env:

**Comment by jhgihub0** [comment]
Great that worked. Thanks @davisagli
