### ISSUE TITLE
`inject_namespace` is difficult to use

### ISSUE THREAD

**Issue by spelak-salesforce** [SFDO-Tooling/CumulusCI#1775]
**If you are seeking support on using CumulusCI, please do not open an Issue. Instead, please visit us on the [Trailblazer Community](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009M9Z), or, for Nonprofit and Education customers, the [Power of Us Hub](https://powerofus.force.com/s/group/0F980000000PSRHCA4/cumulusci-cci)**

## Please describe the nature of this feature request

- I'm interested in functionality that solves a current problem or limitation in how CumulusCI works.
- I'm interested in functionality that has to do with CumulusCI's architecture or overall capabilities.

## Does your feature request solve a current problem? Please describe.
Namespace injection is difficult.  Having to remember to use namespace tokens and trouble shoot namespace injection is difficult and takes a lot of time.   The current tool feels esoteric and hard to describe how to implement to unaccustomed developers.

### Use an org context parameter
Instead of passing in `managed` and `namespaced_org` arguments, pass in an `org_context` argument.   This would make it a lot easier to understand how the namespace injection tokens are used or not used.  Possible values:
- `UNMANGED`, `UNMANAGED_NAMESPACED`, `MANAGED`, `PACKAGING` (for the special context of 1GP packaging orgs).
 - An alternative: `None` (for unmanaged), `NAMESPACED`, `MANAGED`, `PACKAGING`.
 - If we need different contexts for 1GP packaging vs 2GP packaging, perhaps split `PACKAGING` into different context enums `1GP_PACKAGING`, `2GP_PACKAGING`.

### Use easier to understand namespace tokens.
The current namespace tokens have a mix of context plus what is being injected, and I think we could change the token to only describe what is being injected.   We could then use the `org_context` to choose what to do with the namespace tokens.  The end users just need to understand what type of injection is needed, then cci is smart enough to know what to inject based on the org context.

[inject_namespace](https://github.com/SFDO-Tooling/CumulusCI/blob/master/cumulusci/utils/__init__.py#L267) currently injects namespace tokens for the following use cases.
- `SCHEMA`-like: where the token is either replaced by the namespaced+ 2 underscores, e.g. `namespace__`, or a blank string.   This is the type of namespace injection we need for schema: objects and fields.
- `APEX`-like: where the token is either replaced by the namespace + a period, e.g. `namespace.`, or a blank string.   This is the type of namespace injection we need for Apex references.
- `LIGHTNING_COMPONENT`-like: where the token is either replaced by the namespace or the common `c` namespace.   This is the type of namespace injection we need for Lightning Components: Aura or Lightning Web Components.

We could also extend this further to identify a namespace token for different metadata types, e.g. metadata types relating to above.  This is a lot less for the developer to remember: just use the namespaced token for the type of metadata you want to namespace inject.

- Using `SCHEMA` injection
    - `OBJECT`
    - `FIELD`
    - `LAYOUT`
    - `LIST_VIEW`
- Using `APEX` injection
    - `APEX`
- Using `LIGHTNING_COMPONENT` injection
    - `AURA`
    - `LWC`

Since the `MANAGED` org context has different namespace injection for packaged vs unpackaged metadata, double the number of metadata tokens for both use cases:

- `UNPACKAGED`
    - Using `UNPACKAGED__SCHEMA` injection
        - `UNPACKAGED__OBJECT`
        - `UNPACKAGED__FIELD`
        - `UNPACKAGED__LAYOUT`
        - `UNPACKAGED__LIST_VIEW`
    - Using `UNPACKAGED__APEX` injection
        - `UNPACKAGED__APEX`
    - Using `UNPACKAGED__LIGHTNING_COMPONENT` injection
        - `UNPACKAGED__AURA`
        - `UNPACKAGED__LWC`
- `PACKAGED`
    - Using `PACKAGED__SCHEMA` injection
        - `PACKAGED__OBJECT`
        - `PACKAGED__FIELD`
        - `PACKAGED__LAYOUT`
        - `PACKAGED__LIST_VIEW`
    - Using `PACKAGED__APEX` injection
        - `PACKAGED__APEX`
    - Using `PACKAGED__LIGHTNING_COMPONENT` injection
        - `PACKAGED__AURA`
        - `PACKAGED__LWC`

#### Example inject_namespace implementation

```py
def inject_namespace(
    name,
    content,
    org_context,
    namespace=None,
    logger=None,
):

    token_replacements = {}

    # Remember None means "UNPACKAGED" (non-namespaced)
    if org_context is None:
        token_replacements["UNPACKAGED_SCHEMA"] = ""
        token_replacements["PACKAGED_SCHEMA"] = ""

        token_replacements["UNPACKAGED__APEX"] = ""
        token_replacements["PACKAGED__APEX"] = ""

        token_replacements["UNPACKAGED__LIGHTNING_COMPONENT"] = "c"
        token_replacements["PACKAGED__LIGHTNING_COMPONENT"] = "c"
    
    elif org_context == "NAMESPACED":
        token_replacements["UNPACKAGED_SCHEMA"] = namespace + "__"
        token_replacements["PACKAGED_SCHEMA"] = namespace + "__"

        token_replacements["UNPACKAGED__APEX"] = namespace + "."
        token_replacements["PACKAGED__APEX"] = namespace + "."

        token_replacements["UNPACKAGED__LIGHTNING_COMPONENT"] = namespace
        token_replacements["PACKAGED__LIGHTNING_COMPONENT"] = namespace
    
    elif org_context == "MANAGED":
        token_replacements["UNPACKAGED_SCHEMA"] = ""
        token_replacements["PACKAGED_SCHEMA"] = namespace + "__"

        token_replacements["UNPACKAGED__APEX"] = ""
        token_replacements["PACKAGED__APEX"] = namespace + "."

        token_replacements["UNPACKAGED__LIGHTNING_COMPONENT"] = "c"
        token_replacements["PACKAGED__LIGHTNING_COMPONENT"] = namespace
    
    elif org_context == "PACKAGING":
        # TODO: confirm what the packaging context needs
        token_replacements["UNPACKAGED_SCHEMA"] = ""
        token_replacements["PACKAGED_SCHEMA"] = namespace + "__"

        token_replacements["UNPACKAGED__APEX"] = ""
        token_replacements["PACKAGED__APEX"] = namespace + "."

        token_replacements["UNPACKAGED__LIGHTNING_COMPONENT"] = "c"
        token_replacements["PACKAGED__LIGHTNING_COMPONENT"] = namespace

    # Fill out the rest of the namespace tokens
    for package_type in [
        "UNPACKAGED",
        "PACKAGED",
    ]:
        for schema in [
            "OBJECT",
            "FIELD",
            "LAYOUT",
            "LIST_VIEW",
        ]:
            token_replacements[f"{package_type}__{schema}"] = packaged[f"{package_type}__SCHEMA"]

        for lightning_component in [
            "AURA",
            "LWC",
        ]:
            token_replacements[f"{package_type}__{lightning_component}"] = packaged[f"{package_type}__LIGHTNING_COMPONENT"]
    
    # Replace content and name
    for token, replacement in token_replacements.items():
        # Replace content
        previous_content = content
        content_token = f"%%%{token}%%%"
        content = content.replace(content_token, replacement)
        if logger and content != prev_content:
            logger.info(f'  {name}: Replaced {content_token} with "{replacement}"')

        # Replace name
        previous_name = name
        file_token = f"___{token}___"
        name = name.replace(file_token, replacement)
        if logger and name != previous_name:
            logger.info(f"  {previous_name}: renamed to {name}")

    return name, content
```

##### Apex Anonymous Script for NPSP
```apex
Type batchServiceType = Type.forName('%%%PACKAGED__APEX%%%BatchService');

if (batchSerivceType != null) {
    Object instance = batchServiceType.newInstance();

    if (instance instanceof System.Callable) {
        final System.Callable batchService = (System.Callable) instance;

        List<%%%PACKAGED__OBJECT%%%Batch__c> batches = [
            SELECT
                Id,
                %%%PACKAGED__FIELD%%%Description__c,
                %%%PACKAGED__FIELD%%%Number_of_Items__c
            FROM %%%PACKAGED__OBJECT%%%Batch__c
            WHERE %%%UNPACKAGED__FIELD%%%IsAbortable__c
        ];

        batchService.call(
            'abort', 
            new Map<String, Object>{
                'batches' => batches
            }
        );
    }
}
```

##### Update packaged Page Layout
`___PACKAGED__LAYOUT___Funding_Program__c-Community User - Funding Program Layout.layout-meta.xml`

##### Update packaged List View
File names and path

```
force-app/main/default
    objects/
        ___PACKAGED__OBJECT___Funding_Program__c
        listViews/
            ___UNPACKAGED__LIST_VIEW___Top_Level_Funding_Programs.listView-meta.xml
```

List view file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ListView xmlns="http://soap.sforce.com/2006/04/metadata">
    <fullName>%%%UNPACKAGED__LIST_VIEW%%%Open_Funding_Programs</fullName>
    <columns>NAME</columns>
    <columns>%%%PACKAGED__FIELD%%%Funding_Program_Manager__c</columns>
    <columns>%%%PACKAGED__FIELD%%%Status__c</columns>
    <columns>%%%PACKAGED__FIELD%%%Start_Date__c</columns>
    <columns>%%%PACKAGED__FIELD%%%End_Date__c</columns>
    <columns>%%%PACKAGED__FIELD%%%Total_Program_Amount__c</columns>
    <columns>%%%UNPACKAGED__FIELD%%%AwardIncrememnt__c</columns>
    <filterScope>Everything</filterScope>
    <filters>
        <field>%%%PACKAGED__FIELD%%%Status__c</field>
        <operation>equals</operation>
        <value>In progress</value>
    </filters>
    <label>Open Funding Programs</label>
</ListView>
```

## Describe alternatives you've considered
Related to this issue, there is no out of the box cci task to `sfdx fore:source:deploy` with namespace injection.  I am creating my own work-around.  I want to use existing tools as much as possible, so I am using `inject_namespace`.  I found it difficult to use the existing parameters, though not impossible.  I want the cci task to be smart enough to know what org context it is in, so I don't have to manually set task options for each context THEN have different flows or flow extensions for the same task.  But the solution feels a bit hacky with the `inject_namespace` args/kwargs to get it to work as expected..

## Additional context
Here's the current [inject_namespace code](https://github.com/SFDO-Tooling/CumulusCI/blob/master/cumulusci/utils/__init__.py#L267).  

To inject `%%%NAMESPACED_ORG%%%`, I set `namespaced_org` as True, but I found it weird that I also had to set `managed` as True too.  The org context is definitely not managed.   It seems the `namespaced_org` kwarg was added later than `managed` to get both scenarios to work.

```py
def inject_namespace(
    name,
    content,
    namespace=None,
    managed=None,
    filename_token=None,
    namespace_token=None,
    namespaced_org=None,
    logger=None,
):
    """ Replaces %%%NAMESPACE%%% in file content and ___NAMESPACE___ in file name
        with either '' if no namespace is provided or 'namespace__' if provided.
    """

    # Handle namespace and filename tokens
    if not filename_token:
        filename_token = "___NAMESPACE___"
    if not namespace_token:
        namespace_token = "%%%NAMESPACE%%%"
    if managed is True and namespace:
        namespace_prefix = namespace + "__"
    else:
        namespace_prefix = ""

    # Handle tokens %%%NAMESPACED_ORG%%% and ___NAMESPACED_ORG___
    namespaced_org_token = "%%%NAMESPACED_ORG%%%"
    namespaced_org_file_token = "___NAMESPACED_ORG___"
    namespaced_org = namespace_prefix if namespaced_org else ""

    # Handle token %%%NAMESPACE_OR_C%%% for lightning components
    namespace_or_c_token = "%%%NAMESPACE_OR_C%%%"
    namespace_or_c = namespace if managed and namespace else "c"

    # Handle token %%%NAMESPACED_ORG_OR_C%%%
    namespaced_org_or_c_token = "%%%NAMESPACED_ORG_OR_C%%%"
    namespaced_org_or_c = namespace if namespaced_org else "c"

    orig_name = name
    prev_content = content
    content = content.replace(namespace_token, namespace_prefix)
    if logger and content != prev_content:
        logger.info(f'  {name}: Replaced {namespace_token} with "{namespace_prefix}"')

    prev_content = content
    content = content.replace(namespace_or_c_token, namespace_or_c)
    if logger and content != prev_content:
        logger.info(
            f'  {name}: Replaced {namespace_or_c_token} with "{namespace_or_c}"'
        )

    prev_content = content
    content = content.replace(namespaced_org_token, namespaced_org)
    if logger and content != prev_content:
        logger.info(
            f'  {name}: Replaced {namespaced_org_token} with "{namespaced_org}"'
        )

    prev_content = content
    content = content.replace(namespaced_org_or_c_token, namespaced_org_or_c)
    if logger and content != prev_content:
        logger.info(
            f'  {name}: Replaced {namespaced_org_or_c_token} with "{namespaced_org_or_c}"'
        )

    # Replace namespace token in file name
    name = name.replace(filename_token, namespace_prefix)
    name = name.replace(namespaced_org_file_token, namespaced_org)
    if logger and name != orig_name:
        logger.info(f"  {orig_name}: renamed to {name}")

    return name, content

```

**Comment by davisagli** [comment]
We added automatic inference for when namespaces need to be injected last fall (but without introducing the new tokens proposed here). We also fixed a bug where the `namespaced_org` parameter was not being used correctly.
