### ISSUE TITLE
Release notes generator duplicates subheadings

### ISSUE THREAD

**Issue by jstvz** [SFDO-Tooling/CumulusCI#1776]
#### Expected
When an h2 level subheading is included under an h1 heading, it will only appear under the corresponding h1 heading in the release notes.

#### Actual
The h2 subheading is duplicated for every non-empty h1 heading

**Reproduction steps**
1. Add a subheading under an H1 heading ([Omega #15](https://github.com/SalesforceFoundation/omega/pull/15))
2. Run [`github_release_notes`](https://sfdo-metaci.herokuapp.com/builds/251258/flows)
3. Review the [release notes](https://github.com/SalesforceFoundation/omega/releases/tag/beta%2F1.0-Beta_43)

**Comment by davisagli** [comment]
I think this is the issue that got fixed in #1923
