### ISSUE TITLE
value_field: is this obsolete?

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/CumulusCI#1777]
I can't find any code that actually processes value_field.

https://github.com/SFDO-Tooling/CumulusCI/blob/5216c5651845f3bab3ed654ce9b771a725809f05/cumulusci/tasks/bulkdata/tests/mapping_v1.yml#L24

**Comment by prescod** [comment]
Also the mapping file references a thing called join_field which is similar.

**Comment by davisagli** [comment]
Yes, it looks like value_field and join_field are obsolete. Left over from before we stored ids in their own table, I think.

It looks like there are quite a few existing mappings that still include them, so it would be better to add a warning than make it an error to include them. https://github.com/search?p=2&q=org%3ASalesforceFoundation+value_field&type=Code
