### ISSUE TITLE
No parser configuration found for subdirectory customHelpMenuSections

### ISSUE THREAD

**Issue by Nickers3** [SFDO-Tooling/CumulusCI#1832]
**Describe the bug**
Running ci_master to packaging org and getting the following error when running the task: update_package_xml:

Exception in task deploy_packaging.update_package_xml
Error: No parser configuration found for subdirectory customHelpMenuSections

**Reproduction steps**
1. Ran flow: cci flow run ci_master --org packaging

**Context**
Per post on the HUB, likely due to capitalization.

- Your CumulusCI version (`cci version`). - 3.13.2
- Your Python version (`python --version`) - 3.7.1 
- Your operating system and version. - Windows 10
- If using Windows, whether you are using Command Prompt, PowerShell, Bash on Windows, or WSL. - Powershell
- If possible, whether you installed CumulusCI using `brew`, `pip`, or `pipx`. - pip

**Gist**
If applicable, please use the `cci error gist` command to create a Gist from your error log and include the link here. See the [documentation](https://cumulusci.readthedocs.io/en/latest/features.html#working-with-errors) to learn how to create a Gist.

**Additional information**

**Comment by davisagli** [comment]
This was fixed in cumulusci 3.15.0
