### ISSUE TITLE
Add 'Group' to Flows

### ISSUE THREAD

**Issue by MatthewBlanski** [SFDO-Tooling/CumulusCI#1833]
**Please describe the nature of this feature request**
- I'm interested in categorizing my repositories' flows at a glance.

**Does your feature request solve a current problem? Please describe.**
I am attempting to communicate the categories of tasks in my repositories, such as those that perform an all-in-one install, those that do pre-package config, those that perform a post-package config, and so on. I want to have an easily-consumable list of my flows by general function.

**Describe the solution you'd like**
I would like flows to receive groupings in `cci flow list` similar to how tasks receive groupings in `cci task list`.

**Describe alternatives you've considered**
I've considered using naming conventions, prefixes, suffixes, and so on, but they fall short of the mark or create complexities that insufficiently solve the issue.

**Additional context**
This feels consumable.
![tasks with groups](https://user-images.githubusercontent.com/45603724/85462303-f0d6ef00-b56a-11ea-9b10-83746521fd86.png)

This feels less consumable.
![flows without groups](https://user-images.githubusercontent.com/45603724/85462340-fa605700-b56a-11ea-9517-b9e6f42ccfbd.png)

**Comment by davisagli** [comment]
@MatthewBlanski I'm in favor of adding this, but realistically won't be able to get to it for a while. Would you have any interest in submitting a PR?

**Comment by MatthewBlanski** [comment]
@davisagli Sounds like a fun weekend open source project for me. I have a strong interest in submitting a PR for this.

**Comment by davisagli** [comment]
@MatthewBlanski here is where it's implemented for `task list`: https://github.com/SFDO-Tooling/CumulusCI/blob/master/cumulusci/cli/cci.py#L1288

**Comment by Br4nd0R** [comment]
fyi @MatthewBlanski - This enhancement was delivered today in v3.20.0
