### ISSUE TITLE
Dataset extract charmap codec can't decode byte

### ISSUE THREAD

**Issue by tcdahlberg** [SFDO-Tooling/CumulusCI#1838]
**Describe the bug**
I'm starting a project that interacts with PriceBook information on Salesforce. I have captured my fields, spun up a scratch org, populated the scratch org with the data from my production org (not sensitive) and wish to extract that data into my repository dataset. During the extraction I get a can't decode byte error. I have successfully extracted data in other projects on this computer.

**Repo**
https://github.com/UniversityOfSaintThomas/CAPE-Salesforce

**Reproduction steps**
1. Dataloaded Pricebook2, Product2, PriceBookEntries into scratch org from production
2. cci task run generate_dataset_mapping
3. cci task run extract_dataset -o mapping datasets/mapping.yml -o sql_path datasets/data.sql --org dev
4. Error: 'charmap' codec can't decode byte 0x9d in position 7147: character maps to <undefined>

**Context**
Please include the following information at minimum.

- CumulusCI version 3.14.0.
- Python version 3.8.2
- Windows Version 10.0.19041 Build 19041
- Using Windows PowerShell, and tried in intelliJ terminal (Command Bash)
- Installed CumulusCI using `pipx`.

**Gist**
I manually created this gist from the log file. Still working on cci command access for this.

https://gist.github.com/tcdahlberg/888c805a2dfc103fc723d359abf405e6

**Comment by davisagli** [comment]
@tcdahlberg I think I understand what is happening here and the fix is pretty straightforward, but I need to jump through some hoops to set up a Windows environment for testing. If I give you a command to install a pre-release with the fix, would you be willing to give it a try?

**Comment by tcdahlberg** [comment]
@davisagli, I can definitely do that. Thanks!

**Comment by davisagli** [comment]
@tcdahlberg ok, I think this will get you updated to a version with the fix: `pipx install --force cumulusci==3.15.0.dev2`

**Comment by tcdahlberg** [comment]
@davisagli, I can confirm that the new version worked!

**Comment by davisagli** [comment]
@tcdahlberg great! It'll be in the next release; in the meantime you can keep using 3.15.0.dev2

**Comment by tcdahlberg** [comment]
Just an interesting side note. I populated Products2, PriceBook2, and PricebookEntry but only Products2 auto generated in the mapping. I think there is some weird relationships between these tables with a one-two-many on the PriceBookEntry object. I'll manually build those out.

Thanks again for the fix!

**Comment by davisagli** [comment]
@tcdahlberg The mapping generator only includes standard objects if they have custom fields from your package namespace. We know this isn't ideal but haven't been able to come up with a good heuristic for determining which standard objects should be included. We're working on adding an option so you can explicitly specify a list of standard objects to include (https://github.com/SFDO-Tooling/CumulusCI/pull/1834)

**Comment by davisagli** [comment]
This was fixed in cumulusci 3.15.0
