### ISSUE TITLE
Changing `days` in org config does not take effect

### ISSUE THREAD

**Issue by davisagli** [SFDO-Tooling/CumulusCI#1860]
Once an org config has been added to the keychain, changing its settings in cumulusci.yml has no effect. For example, after changing `days`, new orgs still get created with the old number of days. We should probably make deleting an org completely remove the keychain entry if it's one that was initialized from cumulusci.yml rather than created using cci org scratch.

**Comment by swapnilshrikhande** [comment]
I am trying to override the default days as below too

`orgs:
    scratch:
        dev:
            config_file: orgs/dev.json
            days: 31
`

Still the scratch org expires in 7 days

**Comment by jstvz** [comment]
Bug logged as [W-11175030](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000xPBSmYAO/view).

**Comment by Br4nd0R** [comment]
Closed by #3209
