### ISSUE TITLE
Remove Expired Connected/Persistent Orgs that are expired with `cci org prune`

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#1988]
**Please describe the nature of this feature request**

As a Quality Engineer, I often need to connect other users I create to cci. These users appear in the "Connected Orgs" section after running a `cci org list` command and have expiration dates based on the trial or scratch org expiration.

**Describe the solution you'd like**
I would like for these users to be removed after their org has expired when I run `cci org prune`.

**Describe alternatives you've considered**
Alternatively, perhaps and users that expire should appear in the "Scratch Org" section if they indeed are for a scratch org. This may require some creative formatting of this section.

**Additional context**
Special care should be taken to **not** unintentionally remove unexpired users or Persistent users.

Example of a bunch of orgs (outside of persistent ones) that I expected to be removed after running `cci org prun`:

<img width="733" alt="Screen Shot 2020-09-01 at 12 08 58 PM" src="https://user-images.githubusercontent.com/459099/91896006-09d7dc80-ec4d-11ea-947c-cfd0383625fc.png">

**Comment by jstvz** [comment]
Fixed in #1749
