### ISSUE TITLE
Error running org list

### ISSUE THREAD

**Issue by acrosman** [SFDO-Tooling/CumulusCI#1998]
**Describe the bug**
When I run `cci org list` I get a python error:

`Error: expected str, bytes or os.PathLike object, not NoneType`

**Reproduction steps**
1. Run `cci org connect production`
2. Connect to a trailhead org
3. Run `cci org list`

**Context**
Please include the following information at minimum.

- CumulusCI version: 
```
> cci version
CumulusCI version: 3.17.1 (C:\Users\ahcrosman\.local\bin\cci)
Python version: 3.8.5 (c:\users\ahcrosman\.local\pipx\venvs\cumulusci\scripts\python.exe)

You have the latest version of CumulusCI.
```

- Your operating system and version: 
Windows 10
- If using Windows, whether you are using Command Prompt, PowerShell, Bash on Windows, or WSL: 
First from PowerShell in vscode terminal, the cmd, then PowerShell standard window
- If possible, whether you installed CumulusCI using `brew`, `pip`, or `pipx`.
pipx

**Gist**
https://gist.github.com/acrosman/01f3b23cfefdd0d185ed66e150bc5664

**Comment by davisagli** [comment]
@acrosman This looks like a possible bug in some recent changes we made to how the default org is tracked. Am I correct in thinking that you ran these commands outside of a CumulusCI project directory? Does `cci org list` work if you run it from inside a project directory?

**Comment by acrosman** [comment]
In practice yes, but honestly didn't think about it that way until you asked.  I ran it from the project root of an SFDX where I had skipped the step of running cci project init.  So yeah, no project was present.  Once I ran that the issue resolved.

**Comment by acrosman** [comment]
Confirmed that yesterday's release did fix the error.
