### ISSUE TITLE
Missing namespaces on snowfakery NPSP test files

### ISSUE THREAD

**Issue by acrosman** [SFDO-Tooling/CumulusCI#2000]
**Describe the bug**
There are a couple objects and fields in the test setup for snowfakery that will not run directly because they are missing the npsp namespace.

GAU object : https://github.com/SFDO-Tooling/CumulusCI/blob/master/cumulusci/tasks/bulkdata/tests/snowfakery/gen_npsp_standard_objects.yml#L5 
Opp Payment Payment_Acknowledged_Date__c field: https://github.com/SFDO-Tooling/CumulusCI/blob/master/cumulusci/tasks/bulkdata/tests/snowfakery/npsp_standard_objects_macros.yml#L16
Opp Payment Payment_Acknowledgment_Status__c field: https://github.com/SFDO-Tooling/CumulusCI/blob/master/cumulusci/tasks/bulkdata/tests/snowfakery/npsp_standard_objects_macros.yml#L20

**Reproduction steps**
1. Setup cci connection to empty NPSP sandbox.
2. Copy the snowfakery yml files into your project.
3. `> cci task run generate_and_load_from_yaml --org [org name] -o num_records 50 -o generator_yaml .\datasets\snowfakery\gen_npsp_standard_objects.yml -o num_records_tablename Contact`

```
2020-09-04 14:31:57: sObject General_Accounting_Unit__c does not exist or is not visible to the current user.
2020-09-04 14:32:02: Field npe01__OppPayment__c.Payment_Acknowledged_Date__c does not exist or is not visible to the current user.
2020-09-04 14:32:02: Field npe01__OppPayment__c.Payment_Acknowledged_Date__c is not present or does not have the correct permissions.
2020-09-04 14:32:02: Field npe01__OppPayment__c.Payment_Acknowledgment_Status__c does not exist or is not visible to the current user.
2020-09-04 14:32:02: Field npe01__OppPayment__c.Payment_Acknowledgment_Status__c is not present or does not have the correct permissions.
```

Adding namespace to linked lines resolves the errors, and all other similar elements have their namespaces.

**Context**
Please include the following information at minimum.

* CumulusCI version:
```
> cci version
CumulusCI version: 3.18.0 (C:\Users\ahcrosman\.local\bin\cci)
Python version: 3.8.5 (c:\users\ahcrosman\.local\pipx\venvs\cumulusci\scripts\python.exe)

You have the latest version of CumulusCI.

```
* Your operating system and version:
Windows 10
* If using Windows, whether you are using Command Prompt, PowerShell, Bash on Windows, or WSL:
PowerShell in vscode terminal
* If possible, whether you installed CumulusCI using brew, pip, or pipx.
pipx

**Comment by davisagli** [comment]
@acrosman Acknowledged. @prescod is planning to address this by adding the namespaces to these mappings and making cci's load_dataset task smart enough to strip them off in orgs where those objects/fields do not have the prefix.

**Comment by acrosman** [comment]
@prescod I'd love to see how that's done. I've spent the last couple days getting my head around the Snowfakery recipes finally.
