### ISSUE TITLE
Dataset checks all checkbox fields regardless of true/false insert

### ISSUE THREAD

**Issue by tcdahlberg** [SFDO-Tooling/CumulusCI#2032]
**Describe the bug**
Datasets that are loaded seem to be setting all checkboxes to true (checked).

**Reproduction steps**
1. cci flow run dev_org using previously working [datasets for Summit Events App](https://github.com/SFDO-Community-Sprints/Summit-Events-App/tree/master/datasets/dev)
2. Checked org and all checkboxes regardless of true/false insert are checked.
3. Created a new mapping/dataset in [branch currently here](https://github.com/SFDO-Community-Sprints/Summit-Events-App/tree/cookie_key/datasets/dev) and tried again with the same results

**Context**
- CumulusCI version: 3.19.0
- Python version: 3.8.5
- Windows 10.0.19041 Build 19041
- Using Powershell
- Cumulus installed/updated with pipx.

**Comment by davisagli** [comment]
@tcdahlberg at first glance, this sounds like something that might be a bug in the new feature we added to load data using the REST API instead of the Bulk API when the dataset is small. We'll look into it, but in the meantime as a workaround you can try forcing the use of the Bulk API by setting `api: bulk` in each step of the mapping file.

**Comment by prescod** [comment]
@tcdahlberg Can you please confirm that this is a behaviour that changed yesterday? That would bolster David's hypothesis.

**Comment by tcdahlberg** [comment]
@prescod,
I can confirm the issue started yesterday after I updated CumulusCI.
Thanks,
Thad

**Comment by davidmreed** [comment]
I'm looking into it. Thank you for reporting, @tcdahlberg!

**Comment by davisagli** [comment]
@tcdahlberg We made a new release 3.19.1, with a fix for this issue.

**Comment by tcdahlberg** [comment]
Great! Thanks! Really love the new anchor_date feature btw 👍

**Comment by tcdahlberg** [comment]
@davisagli, I can confirm that 3.19.1 fixed the issue on my end. Thanks!
