### ISSUE TITLE
Suspicious line: "zip_url" or "repo_name" in dependency

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/CumulusCI#2148]
https://github.com/SFDO-Tooling/CumulusCI/blob/1d9a8623244fa79e491ebd0e74a0b0a776e83840/cumulusci/tasks/salesforce/update_dependencies.py#L248

I think this branch will always evaluate True. Should probably be:

         if "zip_url" in dependency or "repo_name" in dependency:

I don't know a lot about this code path though, so I don't want to fiddle with unit tests to make the change pass.

**Comment by davisagli** [comment]
Oh, good catch. It looks like it doesn't actually matter because "zip_url" dependencies are still making it through to the block that handles them, and the case where neither of these keys is present is also handled. But we should clean it up.
