### ISSUE TITLE
Document OS X set up to have the cci command always available in terminals

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#217]
* Install python and virtualenv (or link to good docs for it)
* Create a virtualenv
* Activate virtualenv in .bash_profile
* Open new terminal and check that the virtualenv is active
* pip install cumulusci
* Creating a ~/.cumulusci_key file
* Securing the ~/.cumulusci_key file
* Including the ~/.cumulusci_key file in the .bash_profile

**Comment by cdcarter** [comment]
The tutorial has thsi now.
