### ISSUE TITLE
Retry metadata deployments after failure due to temporary org locking

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#218]
There can be an error returned from metadata deployments that really doesn't indicate an issue with the code.  It is intermittent and is usually due to some background task not yet completing from the previous build.  The SOAP response message contains the following XML that could be parsed for:

```
<errorMessage>null: The changes you requested require salesforce.com to temporarily lock your organization&apos;s administration setup. However, the administration setup has already been locked by another change. Please wait for the previous action to finish, then try again later.</errorMessage><errorStatusCode>ALREADY_IN_PROCESS</errorStatusCode>
```

This should probably behave like the `retries` option on the `cumulusci.tasks.salesforce.InstallPackageVersion` task does if a beta version is not yet available.

**Comment by davisagli** [comment]
This may still happen, but hasn't been a practical issue since we're mostly using scratch orgs.
