### ISSUE TITLE
Filesystem access abstraction layer

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#222]
CumulusCI should provide some pluggable mechanism for interacting with the filesystem instead of directly using the os module.  Tasks should be changed to use the abstracted methods to access the filesystem.

# Why?

- Ability to run cumulusci tasks and flows against a repo stored somewhere other than the local filesystem like perhaps in Amazon S3
- Makes cumulusci portable to web apps

**Comment by cdcarter** [comment]
I just pushed a branch over on my fork where salesforce_api/metadata.py uses StringIO in place of TemporaryFile (for unrelated poking around reasons): https://github.com/cdcarter/CumulusCI/commit/3a303c19fe4b4040a942c428a5e5e7099f07dfb9. 

Not sure if this is in line with what you're thinking at all or helpful?

**Comment by cdcarter** [comment]
A few things today from a chat with Jason about this feature:

- Probably makes sense for BaseTask to add `self.fs` or `self.workspace` which would be the definitive API for task authors to access the filesystem.
- Probably modules/APIs should be written to handle all files in-memory, only tasks should touch/be aware of the filesystem.
