### ISSUE TITLE
Autocompletion for the command line

### ISSUE THREAD

**Issue by avisser** [SFDO-Tooling/CumulusCI#2220]
I'd like the `cci` cli to support autocomplete. 

We're moving from mostly `sfdx` to a `cci`-based workflow and I'm missing autocomplete.

Rumor has it, the ClickCLI library you are using already supports an autocomplete functionality.

Ideally, the feature would work just as it does for SFDX - I'd add something to my `~/.profile` that would run `cci autocomplete` or similar. That command would output the right data that I could then ingest into my shell.

Thanks!

**Comment by davisagli** [comment]
Yes, `click` supports this. Here are its docs on how to activate it for different shells: https://click.palletsprojects.com/en/7.x/bashcomplete/#activation

So for example with zsh you just need to add this to ~/.zshrc: `eval "$(_CCI_COMPLETE=source_zsh cci)"`

Let us know how your experience with it is. I think that autocompleting most command and option names should work, as well as task names for `cci task run`, but we'll need to make some adjustments to make it work for `cci task info`, `cci flow info`, and `cci flow run`.

**Comment by avisser** [comment]
That does work, but it's slow. I see `python` flash across my terminal every time I hit tab. It takes about 1.5 seconds to respond when I hit tab. With sfdx, it generates a static list when I start bash and the tab completions are instantaneous. 

I looked into the https://click.palletsprojects.com/en/7.x/bashcomplete/#activation-script section, but that didn't seem to work either. 

From the click site
> At least Zsh will also cache the results of completion files
Maybe time for me to migrate to zsh.

**Comment by davisagli** [comment]
@avisser Part of the challenge is that unlike sfdx, in cci the tasks and flows that are available for completion will vary from project to project based on what is configured in cumulusci.yml. So it can't be just a static list that's initialized when the shell starts.

**Comment by spelak-salesforce** [comment]
This is a pretty good work around.

**Comment by davisagli** [comment]
Closing since we have something that sort of works and don't have a clear path to improving it. Improvements welcome, though.
