### ISSUE TITLE
Documentation is incorrect about task syntax

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/CumulusCI#2221]
**Describe the bug**

The task reference suggests that option names will have dashes in them but they seem to still be underscores.

https://cumulusci.readthedocs.io/en/latest/tasks.html#set-duplicate-rule-status

e.g. --api_names is listed as --api-names

cci task info has the same issue.

**Comment by davisagli** [comment]
@prescod Do you think we should simply fix the doc generator, or also actually support options passed with a dash in place of an underscore?

**Comment by prescod** [comment]
If we want to invest the effort, I'd suggest that we support dashes and underscores in YAML, Python and both CLI syntaxes. If the programmer felt that they had higher priorities and just wanted to fix the doc generator, I'd agree with that too.
