### ISSUE TITLE
Create a task for executing post install scrips

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#2326]
**Please describe the nature of this feature request**

- I'm interested in a new Task for CumulusCI which runs classes that implement InstallHandler. When simulating unmanaged deploys, post-install scripts are not automatically run. As suggested in #129, it is possible to create a task that executes a script, but I think it would be convenient to have a task that automatically finds this class or at least allows for an easy way to define the class as a parameter. Furthermore, this task could be added to existing OOTB unmanaged deploy flows where reasonable like `deploy_unamanged`.

**Comment by davisagli** [comment]
@Julian88Tex I'm not sure this is possible. Install scripts implement an interface [InstallHandler](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_install_handler.htm#apex_install_handler), which has a method onInstall which takes an InstallContext argument. I don't think we have a way to construct one of those outside of an actual installation or unit tests.

Probably the best you can do is put the bulk of the implementation in a separate class which can be called by an anonymous Apex task. There's some precedent for this; for example if I recall correctly, NPSP includes an npsp_default_settings anon Apex task in unmanaged flows which initializes settings using the same code that is run from the install script.

**Comment by Julian88Tex** [comment]
We discussed this further in another tool. For reference here are some of the key thoughts as best as I understand them:

From @davidmreed : "It could check for a postinstall script in the CumulusCI YML, then synthesize a small Anonymous Apex script to execute it via the Tooling API."
From @davidmreed: "We’d need to be careful about rollout because many projects have their own automation already to run postinstall scripts, and because some postinstall scripts may not run properly in an unmanaged context."
From @davidmreed: "the Anon Apex script would have to use JSON deserialization to synthesize a mock InstallContext (which, to be fair, I haven’t tried and which might not work)"

**Comment by davidmreed** [comment]
My final comment is wrong, as @MatthewBlanski noted - you can actually construct an `InstallContext` directly.

**Comment by davisagli** [comment]
This was also requested in https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000BuQZI
