### ISSUE TITLE
Formal task return values

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/CumulusCI#233]
Currently, task return values are implicit -- any attribute on the prior task can be accessed by the flow runner. This is a _work in progress_ proposal for adding a `return_values` dict to BaseTask. 

## Rationale

Accessing any attribute of the prior task execution class is likely to expose internal behaviors to the flow. Though the public attributes of a task instance rarely change, accessing them by flow definition is asking for trouble.

Other benefits include:

- CI servers - such as mrbelvedereci - being able to easily store task results. 
- Access to return values in a structured way for functional testing.
- Generation of documentation for task definitions.

## Task Running Contexts

CumulusCI has three public interfaces for running tasks:

- the CLI tool
- the flow task runner
- the BaseTask Callable interface

### Current Task Return Value Conventions / Impact Analysis

There are two conventions for task return values. Attributes are used by the flow runner, and a function return value is used by the Callable interface. The CLI tool has no support for task return values.

#### Attributes - Flow Runner

Public instance attributes of the task can be accessed after the completion of a task by the next flow in the flow runner using `^^task_name.attr` syntax. The following tasks are known to use this:

- cumulusci.tasks.salesforce.PackageUpload
- cumulusci.tasks.github.CreateRelease

#### _run_task return value

The `_run_task` method can return a value, which will be returned by the `__call__` of the task. I can find no instance of this actually being put to use in the codebase. mrbelvedereci impact yet to be assessed, but this enhancement would create a change to that tool anyway.

### MVP

Add a `return_values` property to BaseTask which is initialized as an empty dict.

Task implementations set their return values by adding to the `return_values` dict.

The flow runner will be updated to reach into the return_values dict instead of the instance of the task itself. Access semantics and syntax will remain the same.

The `__call__` interface on task will return the return_values property instead of the result of _run_task.

The result of _run_task is stored in an instance attribute named `task_result`.

### Further Implementation

Task classes declare their `return_values` dict at a class level like `task_options`.

**Comment by davisagli** [comment]
This happened.
