### ISSUE TITLE
"github_release" task fails when git SSH is using custom SSH host

### ISSUE THREAD

**Issue by lordgordon** [SFDO-Tooling/CumulusCI#2370]
**Describe the bug**
The "github_release" task fails when using SSH custom Host configuration with the error:

```
2021-02-05 19:30:26: ------------------------------------------------------------
2021-02-05 19:30:26: Running task: github_release
2021-02-05 19:30:26: ------------------------------------------------------------
2021-02-05 19:30:26: 
2021-02-05 19:30:26: Options:
2021-02-05 19:30:26:   version: 1.1 (Beta 2)
2021-02-05 19:30:26:   dependencies: []
2021-02-05 19:30:26: Beginning task: CreateRelease
2021-02-05 19:30:26: 
2021-02-05 19:30:27: Exception in task github_release

404 Not Found
```

**Reproduction steps**

Set the following git configuration.

Content of `.git/config`:
```
[remote "origin"]
    url = git@github-config:myusername/Food-Bank.git
    fetch = +refs/heads/*:refs/remotes/origin/*
```

Content of `~/.ssh/config`:
```
Host github-config
    HostName github.com
    IdentityFile ~/.ssh/***
    User git
```

Then `cci shell --python "print(project_config.repo_owner, project_config.repo_name)"` shows:
```
git@github-config:myusername Food-Bank
```

The expected result should be:
```
myusername Food-Bank
```

**Context**
- CumulusCI version: `3.28.0`
- Python version: `3.8.7`
- MacOS Big Sur 11.2
- CumulusCI installed with `brew`

**Additional information**
HTTPS url works fine. Also, works fine with "normal" SSH url without the custom SSH host.

*edit*: minor fixes with English grammar.

**Comment by davisagli** [comment]
@lordgordon We have code that is handling ssh urls by specifically looking for `git@github.com`, which isn't matching your URL because of using the `github-config` alias. Can you change the name of the `Host` to `github.com` in `~/.ssh/config`?

**Comment by lordgordon** [comment]
> @lordgordon We have code that is handling ssh urls by specifically looking for `git@github.com`, which isn't matching your URL because of using the `github-config` alias. Can you change the name of the `Host` to `github.com` in `~/.ssh/config`?

Yes, setting `github.com` as the `Host` in `~/.ssh/config` allows `cci` to properly recognize the configuration and solves the issue.
