### ISSUE TITLE
Add org name to flow success message

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#2389]
**Please describe the nature of this feature request**
- Add org name to flow success message `Completed flow 'regression_org' successfully!`

I often have to scroll up to verify which org I ran a flow on so it would be helpful to have it in the success message.

**Comment by davisagli** [comment]
@Julian88Tex good idea. Here's where that line is produced if you want to try to fix it yourself: https://github.com/SFDO-Tooling/CumulusCI/blob/main/cumulusci/core/flowrunner.py#L418 ... should be a matter of including `org_config.name`

**Comment by Julian88Tex** [comment]
@davisagli thanks! just created the PR. Any chance there's a good doc on setting up CumulusCI locally for development so I can test it out?

**Comment by davisagli** [comment]
@Julian88Tex You can tell us whether it's good or not, but that's what https://github.com/SFDO-Tooling/CumulusCI/blob/main/CONTRIBUTING.rst is for

**Comment by davisagli** [comment]
Fixed in #2390
