### ISSUE TITLE
Show more details in org list

### ISSUE THREAD

**Issue by cpolcyn** [SFDO-Tooling/CumulusCI#241]
Currently `cci org list` shows a list of org aliases and identifies which (if any) is default. We should add some more fields such as:

- Global vs local CCI org
- Scratch vs dev
- Which pod is it running on
- etc

**Comment by cdcarter** [comment]
a fair amount of this can be pulled out of userinfo - tho i don't know if ScratchOrgConfig has been tested to actually inherit that implementation.

**Comment by jlantz** [comment]
Two new things we should show:

* Which scratch org config the org was generated from
* Whether the namespace is applied in the org
