### ISSUE TITLE
Command task should accept --extra option

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/CumulusCI#2495]
**Please describe the nature of this feature request**

- I'm interested in extensions to existing CumulusCI functionality (e.g., broader applicability of an existing Task or Flow).

**Does your feature request solve a current problem? Please describe.**

Tasks like 'dx' have a --extra option for adding information to the end of a command. The "Command" task does not.

**Describe the solution you'd like**

```
cci task run my_command -o extra "woopie doo dah day" 
```

**Comment by davidmreed** [comment]
@prescod Can you give a concrete example of how this would be used? Are you envisioning specialization of some base Command task with other tasks that append arguments, or similar?

**Comment by prescod** [comment]
Sorry I should have documented the example use-case when I ran into it. My bad. Now II don't remember.

But conceptually the request makes sense that if you need to pass an argument to a command dynamically then it would be useful. We can close it for now and re-open if a specific example arises again.
