### ISSUE TITLE
Get rid of task.result

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/CumulusCI#2525]
We should get rid of task.result because it does not seem to be either documented nor used anywhere.

We don't need both task.result and task.return_values in my opinion.

**Comment by davisagli** [comment]
I think we'll need more careful inspection to confirm that it is not used anywhere. That's why I've been hesitant to touch it so far.

**Comment by dcinzona** [comment]
I'd like to be able to hook into the results to be able to validate the data loaded into an org.  I had to create a custom task that called the generate data and load data tasks separately (to keep the temp database around long enough to extract the results of the data generation task, and merge with the SF IDs.  This helps us troubleshoot any automation that could be changing values depending on the different sets of data loaded.

**Comment by davidmreed** [comment]
Closing out this issue pending further research. @dcinzona Would welcome more detail on your use case (feel free to reach out internally or open an enhancement issue here) for the backlog.
