### ISSUE TITLE
release_beta flow fails with NPSP dependency in 3.33

### ISSUE THREAD

**Issue by georgeslater** [SFDO-Tooling/CumulusCI#2564]
**Describe the bug**
Starting in version 3.33, when the release_beta flow is run, the github_release task produces an error when an NPSP dependency is present in the package.

**Reproduction steps**
1. In cumulusci.yml, specify the dependency:

dependencies:
    - github: "https://github.com/SalesforceFoundation/NPSP"

2. Run the `release_beta` flow.
3. Observe the following warning:

> CumulusCI Configuration Warning:
>  '<stream>' -> 'flows' -> 'release_beta' -> 'tasks'

4. The github_release task fails with the following:
> The repo_name and repo_owner keys are deprecated. Please use the github key.
> The dependency keys `repo_owner` and `repo_name` are deprecated. Use the full repo URL with the `github` key instead.

**Context**

We are seeing this in our continuous integration pipeline:

- Your CumulusCI version **3.33**
- Your Python version **3.8**
- Your operating system and version. **ubuntu-latest**
- If possible, whether you installed CumulusCI using `brew`, `pip`, or `pipx`. **brew**

**Gist**
https://gist.github.com/georgeslater/f8e6151ea444c9778077a43d687f2f69

**Additional information**
This started happening when our continuous integration job started pulling version 3.33 from Homebrew.  I don't see how we can easily modify the dependencies structure as this is part of the release_beta flow.

**Comment by davisagli** [comment]
Thanks for the report. I've reproduced this and we are working on a fix.

**Comment by davisagli** [comment]
@georgeslater We just released cumulusci 3.33.1 with a fix for this issue.
