### ISSUE TITLE
update_dependencies task not updating the package dependencies

### ISSUE THREAD

**Issue by krutidave** [SFDO-Tooling/CumulusCI#2569]
**Describe the bug**
Starting in version 3.33, The update_dependencies task does not update the dependencies present in the project. 
There are no nested dependencies.

**Reproduction steps**
1. In cumulusci.yml, specify the dependency:

```
dependencies:
- namespace: "test"
  version: "1.0"
```

2. Run `update_dependencies` task

3. The task completes without installing dependencies - 
CumulusCI Configuration Warning:
  '/Users/kdave/workspace/cpbase/cumulusci.yml' -> 'dependencies'
    extra fields not permitted

Project has no dependencies, doing nothing

**Context**
Please include the following information at minimum.

cci version 3.33.0
python 3.9.4
macOS 10.14.6

**Additional information**
This started happening when our continuous integration job started pulling version 3.33 from Homebrew. I don't see how we can easily modify the dependencies structure to install the dependent packages.

**Comment by davisagli** [comment]
@krutidave It looks like you have the `dependencies` key at the top level of cumulusci.yml. It needs to be indented inside the `project` section. If I'm correct that this is the problem, the only change from previous versions of CumulusCI is that we are now showing a warning about the `dependencies` key in the wrong location.

**Comment by krutidave** [comment]
@davisagli - Thank you for sharing that. This is how we are using in our continuous integration job to update the dependencies. Is there anything changed on this structure, as its no longer identifying the dependencies ?

`import os
from cumulusci.tasks.salesforce import UpdateDependencies as BaseUpdateDependencies
from cumulusci.utils import find_replace
from cumulusci.utils import find_replace_regex
import requests
class UpdateDependencies(BaseUpdateDependencies):
      def _init_options(self, kwargs):
        super(UpdateDependencies, self)._init_options(kwargs)
        dependencies = []
        dependencies.append({'namespace': 'npe01', 'version': '3.6'})
        self.options["dependencies"] = dependencies`

```
2021-04-20 11:35:56: Getting org info from Salesforce CLI for test-pzpvwduxdy37@example.com
2021-04-20 11:36:00: Beginning task: UpdateDependencies
2021-04-20 11:36:00: As user: test-pzpvwduxdy37@example.com
2021-04-20 11:36:00: In org: 00D1h000000IH0d
2021-04-20 11:36:00: 
2021-04-20 11:36:00: Project has no dependencies, doing nothing
```

**Comment by davisagli** [comment]
@krutidave The implementation of the UpdateDependencies task works internally has changed quite a lot in cumulusci 3.33.0, and the dependencies are now stored in an internal format after being processed by _init_options. I think you can get it to work if you change your subclass to work like this:

```
class UpdateDependencies(BaseUpdateDependencies):
    def _init_options(self, kwargs):
        dependencies = []
        dependencies.append({'namespace': 'npe01', 'version': '3.6'})
        kwargs["dependencies"] = dependencies
        super(UpdateDependencies, self)._init_options(kwargs)
```

**Comment by krutidave** [comment]
@davisagli - It worked. Thank you so much !
