### ISSUE TITLE
YML Warning should not have been generated

### ISSUE THREAD

**Issue by WadeLovell** [SFDO-Tooling/CumulusCI#2606]
**If you are seeking support on using CumulusCI, please do not open an Issue. Instead, please visit us on the [Trailblazer Community](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009M9Z), or, for Nonprofit and Education customers, the [Power of Us Hub](https://powerofus.force.com/s/group/0F980000000PSRHCA4/cumulusci-cci)**

**Describe the bug**
Warning received but there aren't any issues with the YML file.
'C:\\Users\\wadel\\Documents\\GitHub\\Food-Bank-Implementation\\.cci\\projects\\NPSP\\1d3e7d9e46d791b752065dc42c8e3187b20b7b48\\cumulusci.yml' -> 'project' -> 'apexdoc'
    extra fields not permitted

**Reproduction steps**
1. Open repository from GitHub Desktop in VS Code
2. cci flow run dev_org --org dev

**Context**
Please include the following information at minimum.

- Latest CumulusCI version).
- Python version 3,9
- Windows 10 - 64 bit - fully updated
- Using VS Code on Windows
- Installed CumulusCI using `pipx`

**Gist**
NA

**Additional information**
minimum_cumulusci_version: '3.34.1'
project:
    name: Food-Bank-Implementation
    package:
        name: Food-Bank-Implementation
        api_version: '50.0'
    dependencies:
        - github: 'https://github.com/SalesforceFoundation/NPSP'
        - github: 'https://github.com/WadeLovell/Food-Bank'
    git:
        default_branch: 'main'
    source_format: sfdx

tasks:
    robot:
        options:
            suites: robot/Food-Bank-Implementation/tests
            options:
                outputdir: robot/Food-Bank-Implementation/results

    robot_testdoc:
        options:
            path: robot/Food-Bank-Implementation/tests
            output: robot/Food-Bank-Implementation/doc/Food-Bank-Implementation_tests.html

    run_tests:
        options:
            required_org_code_coverage_percent: 75
sources:
    npsp:
        github: https://github.com/SalesforceFoundation/NPSP
flows:
    dependencies:
        steps:
            3:
                flow: npsp:config_managed

**Comment by davisagli** [comment]
The warning is not about your own cumulusci.yml file, but about NPSP's, which includes a name (apexdoc) that is no longer supported. This is not a bug in CumulusCI, but is a problem for the NPSP team to correct in their configuration. You can safely ignore the warning.
