### ISSUE TITLE
When running CCI packaging commands, it would be great to display the SFDX equivalent command lines as they are being made

### ISSUE THREAD

**Issue by RupertBarrow** [SFDO-Tooling/CumulusCI#2731]
**Please describe the nature of this feature request**

- When running CCI packaging commands, it would be great to display the SFDX equivalent command lines as they are being made 
 
**Does your feature request solve a current problem? Please describe.**
This would make it easier for the developer to explore the cause of the error, when it is related to SFDX questions (eg packaging, metadata coverage, etc.)

**Describe the solution you'd like**
When I run the "cci error info" command, I would like to see a list of the equivalent SFDX commands issued

**Describe alternatives you've considered**
Otherwise, we need to trial-and-error changes to check whether they will fix the error

**Additional context**

**Comment by davisagli** [comment]
cci does not make use of the sfdx commands for creating packages. Instead it constructs an equivalent package and makes calls directly to the Package2VersionCreateRequest object in the Tooling API to create the package version.

What sort of errors have you run into? To a large extent we are probably limited to reporting the errors that are returned from the Tooling API, but more detail would help us determine if it's something we can improve.
