### ISSUE TITLE
Creating a dev scratch org with Einstein Bot feature fails

### ISSUE THREAD

**Issue by RupertBarrow** [SFDO-Tooling/CumulusCI#2734]
**Describe the bug**
Creating a scratch org sandbox which includes the Einstein Bot feature fails, leaving a created scratch org but a CCI error

**Reproduction steps**
1. Make sure that you have activated Einstein Bot feature in your Dev Hub, and accepted legal terms
2. Include
`    "botSettings": {
      "enableBots": true
    }
`
in orgs/dev.json
3. run `cci org info dev`
4. Notice that the command fails with this error : 
`2021-07-14 01:23:17: Creating scratch org with command: sfdx force:org:create  -f orgs/dev.json -w 120 --targetdevhubusername mydevhub -n --durationdays 7 -a zzz__dev adminEmail=xxx@yyy.com
Failed to create scratch org: 

=== Component Failures [1]
Error  shape/settings/Bot.settings  Bot   Legal Terms acceptance and/or necessary feature dependencies required to enable Bot Settings

ERROR running force:org:create:  Failed to deploy settings to scratch org.`

5. By running `sfdx force:org:list`, also  notice that the scratch org has in fact been created, but has no alias.

**Context**
Please include the following information at minimum.

- Your CumulusCI version (`cci version`) : 3.39.0
- Your Python version (`python --version`) : 3.9.6
- Your operating system and version : MacOS 10.14.6
- If using Windows, whether you are using Command Prompt, PowerShell, Bash on Windows, or WSL.
- If possible, whether you installed CumulusCI using `brew`, `pip`, or `pipx` : brew

**Gist**
If applicable, please use the `cci error gist` command to create a Gist from your error log and include the link here. See the [documentation](https://cumulusci.readthedocs.io/en/latest/features.html#working-with-errors) to learn how to create a Gist.

**Additional information**
I think that the SFDX scratch org is being created correctly, but that CCI is incorrectly handling Bot.settings

**Comment by davidmreed** [comment]
What is the behavior if you run `sfdx force:org:create` directly, using the same Dev Hub and the same scratch org definition file?

**Comment by RupertBarrow** [comment]
Making sure the orgs/dev.json configuration included
`  "features": ["ServiceCloud", "Chatbot"],
`
fixed this issue.
