### ISSUE TITLE
If no service for a connected_app is defined in environment variable an error occurs

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#2737]
**Describe the bug**
If there is no service for a connected_app defined via environment variables and get_service('connected_app') is called, on EnvironmentProjectKeychain an error occurs.

**Context**
- Best guess is this is the PR which causes it: https://github.com/SFDO-Tooling/CumulusCI/pull/2664
- Occurs with sfdx_url authentication method

**Example**
 https://github.com/Salesforce-org-Impact-Labs/01HousingandHomelessness/runs/3090372340?check_suite_focus=true

**Additional information**
In the _load_default_services() method on the EnvironmentProjectKeychain, check for service_type of `connected_app` and then set it to the DEFAULT_CONNECTED_APP_NAME.

**Comment by Julian88Tex** [comment]
@Br4nd0R Here's that issue :-)

**Comment by Julian88Tex** [comment]
@Br4nd0R assuming no blocks to release is it right to assume this will be in the CCI release ~7/27/21?

**Comment by Br4nd0R** [comment]
@Julian88Tex - This will be in the cci release occurring today. I also mentioned a workaround that can be done currently on the slack thread.

**Comment by Julian88Tex** [comment]
@Br4nd0R ah great thanks for the update!
