### ISSUE TITLE
CCI task `upload_beta` creates a major release version and not a beta package 

### ISSUE THREAD

**Issue by epellish** [SFDO-Tooling/CumulusCI#2750]
**If you are seeking support on using CumulusCI, please do not open an Issue. Instead, please visit us on the [Trailblazer Community](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009M9Z), or, for Nonprofit and Education customers, the [Power of Us Hub](https://powerofus.force.com/s/group/0F980000000PSRHCA4/cumulusci-cci)**

**Describe the bug**
A clear and concise description of what the bug is. Please make sure to describe the expected behavior and how your experience differs from it.

After connecting to the packaging org, running ci_master to push code to the packaging org, I run cci task run upload_beta --org packaging --name PackageName 

I expected it to create a Beta version `2.1 (Beta 2)` instead it created a major release version 2.1. 

**Reproduction steps**
1. cci org connect packaging
2. cci flow run ci_master --org packaging 
3. cci task run upload_beta --org packaging --name PackageName
4. Beta package was not created but it created a new major release version 

**Context**
Please include the following information at minimum.

- Your CumulusCI version (`cci version`).
- 3.37.0
- Your Python version (`python --version`)
- 3.9.5
- Your operating system and version.
- macOS Big Sur, 11.4 
- If using Windows, whether you are using Command Prompt, PowerShell, Bash on Windows, or WSL.
- If possible, whether you installed CumulusCI using `brew`, `pip`, or `pipx`.
- Installed via pipx (locally, and pip in docker for our pipelines) 

**Gist**
If applicable, please use the `cci error gist` command to create a Gist from your error log and include the link here. See the [documentation](https://cumulusci.readthedocs.io/en/latest/features.html#working-with-errors) to learn how to create a Gist.

**Additional information**

**Comment by davidmreed** [comment]
Hi @epellish, thanks for opening this issue. The behavior you're describing is certainly concerning. We run `upload_beta` many times per day and have never observed this behavior. To help me reproduce your situation, can you share your `cumulusci.yml`? To do so privately, you can reach out to me at `d.reed@salesforce.com`.

**Comment by jstvz** [comment]
Fixed in #2756.

**Comment by davidmreed** [comment]
@epellish Mind if I follow up on this issue? I wonder if you were ever able to reproduce or isolate it.

Another possibility is that this was a manifestation of a bug we fixed, which saw CumulusCI inaccurately creating releases in GitHub that were marked as production releases (but actually referenced beta managed package versions).

**Comment by davidmreed** [comment]
Closing this issue for now as a likely manifestation of a different bug that has been fixed. Please reopen if you're able to reproduce this behavior on the current version of CumulusCI.
