### ISSUE TITLE
Scratch org creation hangs when sfdx fails due to socket timeout

### ISSUE THREAD

**Issue by lordgordon** [SFDO-Tooling/CumulusCI#2863]
### Describe the bug

`sfdx force:org:create` fails with `error - Socket timeout occurred while listening for results` but CumulusCI doesn't handle the error and hangs. CumulusCI should capture the error and retry.

Reference: https://trailblazer.salesforce.com/issues_view?id=a1p4V000001U1BhQAK

### Reproduction steps

Unable to provide a reliable reproduction steps since this is randomly occurring in our CI.

### Your CumulusCI and Python versions

cci 3.43
Python 3.9
sfdx 7.116.2

### Operating System

dockerized debian slim (official py39 image)

### Windows environment

- [ ] Command Prompt
- [ ] PowerShell
- [ ] Bash on Windows
- [ ] WSL

### CumulusCI installation method

pip

**Comment by lordgordon** [comment]
Related to https://github.com/forcedotcom/cli/issues/1149

**Comment by davidmreed** [comment]
Closing as underlying SFDX bug has been fixed - please reopen if this issue occurs again.
