### ISSUE TITLE
2GP Feature Test flow should check code coverage

### ISSUE THREAD

**Issue by georgeslater** [SFDO-Tooling/CumulusCI#2865]
### Describe the bug

The 2GP Feature Test flow (`ci_feature_2gp`) generates and tests a managed package.  This is an improvement on the 1GP Feature Test flow which tested unmanaged code, as now we can now catch namespace errors earlier in the development process.

However, it has the side effect of not calculating code coverage during the `run_tests` task, since CumulusCI detects we are in a managed context and our package is installed.  Message displayed is 

> This org contains a managed installation; not checking code coverage

I believe we should be checking code coverage as part of the flow.  One fix that comes to mind is to check code coverage if we are in a scratch org, otherwise keep the current behaviour.

### Reproduction steps

Run the ci_feature_2gp flow
Observe that after test execution finishes, CumulusCI reports that it is skipping code coverage calculations.

### Your CumulusCI and Python versions

CumulusCI version: 3.41.0 (/opt/homebrew/Cellar/cumulusci/3.41.0/libexec/bin/cci)
Python version: 3.9.6 (/opt/homebrew/opt/python@3.9/bin/python3.9)

### Operating System

MacOS

### Windows environment

- [ ] Command Prompt
- [ ] PowerShell
- [ ] Bash on Windows
- [ ] WSL

### CumulusCI installation method

brew

### Additional information

Relevant line: https://github.com/SFDO-Tooling/CumulusCI/blob/246e75f49e89b3d269a9613d68e932c4363cf9fb/cumulusci/tasks/apex/testrunner.py#L559

**Comment by davisagli** [comment]
@davidmreed Do you recall what the rationale was for skipping the code coverage check when the package is managed?

**Comment by davidmreed** [comment]
You just can't - the Tooling API doesn't allow you to obtain that data from a managed package installation. Inasmuch as feature-branch 2GPs are actually managed betas (albeit built with SkipValidation), I believe the same applies to them, although I haven't tested it directly. That's why we run both `ci_feature_2gp` _and_ `ci_feature`; the latter does check code coverage.

**Comment by georgeslater** [comment]
Thanks David, I hadn't considered that.  So really the only workaround, apart from running `ci_feature`, is to pass `--skip_validation False` to the `create_package_version` task which will at least allow you to see the coverage in the 2GP Dev Hub (but add to the build time considerably).

Feel free to close this out.
