### ISSUE TITLE
No documentation for ignore_failure

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/CumulusCI#2873]
### Feature Type

I'm interested in functionality that solves a current problem or limitation in how CumulusCI works.

### Does your feature request solve a current problem?

I cannot find any "formal" documentation for ignore_failure although it is mentioned in passing in one example in the docs.

### Describe the solution you'd like

It would be good to have a section that describes it.

**Comment by davisagli** [comment]
Duplicate of #2500
