### ISSUE TITLE
Add support for installation keys for 2GP package versions

### ISSUE THREAD

**Issue by georgeslater** [SFDO-Tooling/CumulusCI#2892]
### Feature Type

I'm interested in extensions to existing CumulusCI functionality (e.g., broader applicability of an existing Task or Flow).

### Does your feature request solve a current problem?

The 2GP `create_package_version` task does not support installation keys.  The 1GP equivalent `upload_beta` provides a `--password` flag.

### Describe the solution you'd like

The task creates a Package2VersionCreateRequest via the Tooling API here: https://github.com/SFDO-Tooling/CumulusCI/blob/main/cumulusci/tasks/create_package_version.py#L477

It looks as though that object provides an `InstallKey` field, so CumulusCI could set that if provided.

### Describe alternatives you've considered

It seems as though the only workaround is to manually run:

`sfdx force:package:version:update --package "<package_name>@<package_version>" --installationkey "<key>"` 

after the package version is created.

**Comment by davidmreed** [comment]
Tracking as W-10502500

**Comment by jstvz** [comment]
Provided as `--install_key`
