### ISSUE TITLE
Error: No parser configuration found for subdirectory fields

### ISSUE THREAD

**Issue by neutronron** [SFDO-Tooling/CumulusCI#2997]
### Describe the bug

We're running into a problem when deploying managed package metadata to our packaging org using the flow "cci flow run ci_master --org packaging"

The Error: 

"Error: No parser configuration found for subdirectory fields"

The flow appears to be successfully creating the /src directory  and files.  Including a subdirectory "fields", which seems to be triggering the error.  This subdirectory is filled with custom field translation metadata.  e.g.

<?xml version="1.0" encoding="UTF-8"?>
<CustomFieldTranslation xmlns="http://soap.sforce.com/2006/04/metadata">
    <label></label>
    <name>Attended__c</name>
</CustomFieldTranslation>

Is this a bug in CumulusCI?  Or maybe custom field translations aren't supported?

Thanks

### Reproduction steps

Define custom field translations in a scratch org for a managed package and attempt to deploy to the packaging org.

### Your CumulusCI and Python versions

Cumulus v 3.48.2

### Operating System

Mac OSX 11.5.2

### CumulusCI installation method

pipx

### Error Gist

https://gist.github.com/neutronron/5ece6172115ea60b4c94cfc8156c0dce

**Comment by davisagli** [comment]
@neutronron There should not be a `fields` directory in the Metadata API format metadata in `src`. In Metadata API format, field definitions are included in CustomObject metadata files (.object extension in the objects folder) and field translations are included in CustomObjectTranslation metadata files (.objectTranslation extension in the objectTranslations folder).

The deploy_packaging flow converts sfdx format into Metadata API format by running the `sfdx force:source:convert` command. I suspect that either sfdx is not converting your metadata correctly, or you don't have the field translations in the right location in sfdx format.

**Comment by davisagli** [comment]
I see an entry in the sfdx release notes from Oct. 7 (https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71218-oct-7-2021) that looks related: "FIX: The force:source:convert command correctly converts the CustomFieldTranslation metadata type."

So it's probably worth checking that you have an up-to-date version of sfdx installed.

**Comment by neutronron** [comment]
Thanks - even with the latest versions of sfdx and cumulusci we're generating this unwanted /fields directory.  We don't need objectTranslations in the package (those were inadvertantly retrieved from a scratch org), so for now we'll just remove that metadata from the force-app/main/default dir. 

Thanks for your help!
