### ISSUE TITLE
Unpackaged metadata does not deploy in SFDX format

### ISSUE THREAD

**Issue by Chanmander** [SFDO-Tooling/CumulusCI#3029]
### Describe the bug

The source in the `unpackaged/post` directory is not deploying. It deploys as expected when I run `cci flow run qa_org` locally, but it is not working in the GitHub Actions context.

<img width="663" alt="Screen Shot 2022-01-07 at 9 06 51 AM" src="https://user-images.githubusercontent.com/18584424/148555312-c3ce1263-d852-4e7a-9a04-801cc79dae5b.png">

### Reproduction steps

1. Add some SFDX format metadata to the `unpackaged/post` directory.
2. Run a pipeline that uses `cci flow run qa_org` to deploy to an org.

### Your CumulusCI and Python versions

CumulusCI version: 3.50.0
Python version: 3.10.1

### Operating System

GitHub Actions (ubuntu-latest)

### CumulusCI installation method

pip

**Comment by davidmreed** [comment]
Have you placed your metadata inside a subdirectory of `unpackaged/post`?

Is `unpackaged/post/<your subdirectory>` listed as a package directory in `sfdx-project.json`?

**Comment by Chanmander** [comment]
Yes, I'd removed `unpackaged` from `sfdx-project.json` because I was seeing `unpackaged/config` was deployed with the `create_package_version` task. Re-adding it fixed the issue with `qa_org`, but not with `create_package_version`.

Two questions, then:
- Does each `unpackaged/***` directory need to be separately listed in `sfdx-project.json`?
- I'm noticing that `unpackaged/config` contents are being deployed with `create_package_version`. Is that by design? It doesn't appear to be based on [the docs](https://cumulusci.readthedocs.io/en/stable/unpackaged.html#unpackaged-config-tailor-an-org)?. Can I exclude them?

Thank you!

**Comment by davidmreed** [comment]
> I'm noticing that unpackaged/config contents are being deployed with create_package_version. Is that by design? It doesn't appear to be based on the docs?. Can I exclude them?

No, that is not by design. I will get a bug opened for us to look into. In the meantime, storing your unpackaged metadata in MDAPI format is an effective workaround.

**Comment by Chanmander** [comment]
Thank you @davidmreed for the workaround! Can confirm that it is effective. I'm going to close this issue so you all can handle the SFDX format issues separately.
