### ISSUE TITLE
Ability for separate Python eggs to register their own cumulusci.yml

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#304]
CumulusCI needs some sort of registry for add on packages.  For example, when building `cumulusci_mockaroo` I want to add a new service to CumulusCI.  Ideally, cumulusci_mockaroo could just have its own cumulusci.yml file that gets added to the stack for HiYaPyCo to do the hierarchical yaml merge.  This would allow add ons to extend the base cumulusci.yml across all projects while still allowing projects to override everything if needed.

**Comment by davisagli** [comment]
setuptools entry points would be the normal Pythonic way to do this.

**Comment by davidmreed** [comment]
Closing issue as outdated - please feel free to open a new issue with current details if this issue is still impactful.
