### ISSUE TITLE
CumulusCI Configuration Warning: '.../cumulusci.yml' -> 'ci_feature' extra fields not permitted

### ISSUE THREAD

**Issue by RupertBarrow** [SFDO-Tooling/CumulusCI#3091]
### Describe the bug

I have added these lines to my cumulusci.yml file : 
`ci_feature:
  steps:
    0.7:
      task: uniquify_connected_app
`
I have also added lines to define the uniquify_connected_app task, but those do not change the problem.

When I run `cci flow info ci_feature` I get the following error message : 
`% cci flow info ci_feature
CumulusCI Configuration Warning:
  '/Users/rupert/Workspaces/other/RBW_RAPIDO/RAPIDO_Forms/rapido-forms-sf-tdl/cumulusci.yml' -> 'ci_feature'
    extra fields not permitted
NOTE: These warnings may become errors in future versions of CumulusCI.
If you think your YAML has no error, please report the bug to the CumulusCI team.
https://github.com/SFDO-Tooling/CumulusCI/issues/

Description: Prepare an unmanaged metadata test org and run Apex tests. Intended for use against feature branch commits.

Flow Steps
0.5) task: github_parent_pr_notes [from current folder]
     options:
         branch_name: $project_config.repo_branch
         build_notes_label: Build Change Notes
... etc.
`

### Reproduction steps

1. Add these lines to cumulusci.yml : 
`tasks:
  uniquify_connected_app:
    description: Changes connected app secret to unique value, with prefix as a parameter
    class_path: cumulusci.tasks.sfdx.SFDXBaseTask
    group: dx
    options:
      command: sfdx shane:connectedapp:uniquify -p dev -a ./force-app/Integration/default/connectedApps/RAPIDO_Forms.connectedApp-meta.xml

ci_feature:
  steps:
    0.7:
      task: uniquify_connected_app
`
2. run `cci flow info ci_feature`

### Your CumulusCI and Python versions

cci 3.62.0
Python : 3.10.1

### Operating System

MacOS 11.6.3

### CumulusCI installation method

pipx

**Comment by davisagli** [comment]
@RupertBarrow Did you intend to put `ci_feature` inside the `flows` section of cumulusci.yml? It can't go at the top level.

**Comment by RupertBarrow** [comment]
I just want to add step 0.7 to flow 'ci_feature"

**Comment by RupertBarrow** [comment]
OK, I got it : I should have added : 

flows:
  ci_feature:
    steps:
      0.7:
        task: uniquify_connected_app

Sorry for the disturbance
