### ISSUE TITLE
Document how to test with 2GP packages, with GitHub actions

### ISSUE THREAD

**Issue by RupertBarrow** [SFDO-Tooling/CumulusCI#3095]
### Feature Type

I'm interested in extensions to existing CumulusCI functionality (e.g., broader applicability of an existing Task or Flow).

### Does your feature request solve a current problem?

Your documentation article about testing with second generation packages (https://cumulusci.readthedocs.io/en/stable/2gp_testing.html?highlight=ci_feature_2gp) is great but not totally practical : we need a working example.

### Describe the solution you'd like

You provide a great practical example of implementing using Cumulus CI with Github Actions : https://cumulusci.readthedocs.io/en/latest/github_actions.html

It would be great to see this example extended to support the use of testing with 2GP.

### Describe alternatives you've considered

I'm trying to implement it myself ...

You could also write a follow-up on the excellent Salesforce Architects Medium article "Find Bugs Earlier with Second-Generation Packaging" (https://medium.com/salesforce-architects/find-bugs-earlier-with-second-generation-packaging-f7c7a0b5300a), explaining how to implement this with CCI and Github Actions.

**Comment by davidmreed** [comment]
@RupertBarrow I have a full-scale example coming in the very near future that is currently tested and working. I'd be delighted to run it by you.

**Comment by RupertBarrow** [comment]
Hi David, you want me to read your doc through for comments : ok !

**Comment by jstvz** [comment]
https://cumulusci.readthedocs.io/en/stable/2gp-testing.html

**Comment by RupertBarrow** [comment]
Thanks @jstvz !
Maybe you could add a paragraph on testing package upgrade deployments for regressions (`regression_org`, `install_regression` and `config_regression`) ?

Also, maybe point out how these examples differ (or not) between 2GP and Unlocked Packages testing.

Thanks,
Rupert
