### ISSUE TITLE
Deploy Post inexplicable filesize of 496b on *.swf

### ISSUE THREAD

**Issue by Szandor72** [SFDO-Tooling/CumulusCI#311]
Hello,

running on CircleCI with python 2.7.12

In my project folder I got the following structure: unpackaged / post / src

in src, there is a package.xml referencing static resources which are located in their own folder. usual package setup.

I have 5 static resources: 3 of type text (JSON) and 2 of type swf/shockwave application

My JSON files get updated without any issues.

My SWF Files do not: They are 1.02MB in size but after upload/task completion show up as 496 Bytes only:

![image](https://cloud.githubusercontent.com/assets/16804218/25620687/850d5556-2f4f-11e7-91ff-bd3cabf2899b.png)

**Comment by Szandor72** [comment]
different org,  different beta, persisting issue. 

![image](https://user-images.githubusercontent.com/16804218/26989632-1f1c022e-4d54-11e7-9471-391e65dd4f87.png)

I used:
`cci task run deploy_post -o managed true` (same for `managed false`)

unpackaged/post/src does contain a few more files than just the two with failing file size. These do not get updated (see lastModifiedDate) either.  😕 

package.xml in /post/ contains wildcarded static resource reference only. no other metadata are deployed.

**Comment by davisagli** [comment]
Is this still an issue?

**Comment by Szandor72** [comment]
We're not using CCI for this part of our deployments anymore. cannot confirm/deny but will close down this issue since 2 years old.
