### ISSUE TITLE
Error Message for CCI is Displaying at Top of Doc Flows Page

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#3143]
### Describe the bug

There's an error message at the top of the flows docs page (I happened to be researching it) that seems to be incorrectly displaying. I'm not seeing in on the yml doc though: https://github.com/SFDO-Tooling/CumulusCI/blob/main/docs/flows.yml

<img width="1496" alt="Screen Shot 2022-04-04 at 12 46 11 PM" src="https://user-images.githubusercontent.com/459099/161611642-640e580a-c1ec-47ff-bb5e-22c05e603e7c.png">

### Reproduction steps

1. Navigate to https://cumulusci.readthedocs.io/en/latest/flows.html

Result: "[04/01/22 21:00:07] Unable to store an encryption key. Any orgs or services
written to disk will not be encrypted." displays at the top of the page

### Your CumulusCI and Python versions

n/a

### Operating System

MacOS 12.3.1

**Comment by jstvz** [comment]
Thanks for the report. Also mentioned in #3051
