### ISSUE TITLE
Removing an org hands on in the cloud clashes with "org remove"?

### ISSUE THREAD

**Issue by tombvo** [SFDO-Tooling/CumulusCI#3155]
### Describe the bug

Hi everyone,
I'm not sure of this is a bug or if I'm getting something wrong. 
However, I have always used `org remove` to delete a certain scratch org. Since the dependent config was persisted in the cumulus.yml, I've thought it doesn't matter since it's not getting removed.

What happened to me now is the following:
I've deleted the scratch org hands on in the cloud, so It still existed in the cci keychain. 
When I tried to remove it via `cci org remove` - it caused the this exception:

`raise OrgNotFound(
                    f"Could not find org named {name} to delete.  Deleting in project org mode.  Is {name} a global org?"
                )`

When I now try to create a new scratch org, It somehow won't take all my cumulus.yml configs into consideration, for example, it creates the scratch org with no namespace although namespaced is true in the .yml.

I can only get the config back working with: `cci org scratch dev --org dev`

Note: When I'm repeating this, It's not raising the exception anymore but my config is still not "live" anymore.

I think `scratch_delete` fixed the problem and is probably the command I should be using for my intention, but I thought this could be interesting whatsoever.

### Reproduction steps

1. 
2.
3.
n. ...

### Your CumulusCI and Python versions

cci 3.49
python 3.9

### Operating System

Win 11

### Windows environment

PowerShell

**Comment by davidmreed** [comment]
Could you please attach a Gist generated by `cci error gist` to show the complete trace of this problem?
