### ISSUE TITLE
Add Documentation for Flow to Task Option Passing

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#3160]
### Feature Type

I'm interested in extensions to existing CumulusCI functionality (e.g., broader applicability of an existing Task or Flow).

### Describe the solution you'd like

Add documentation for flow option which allows passing to tasks. Currently the only documentation I've found is when you use `cci flow run --help`: https://github.com/SFDO-Tooling/CumulusCI/blob/4f7b5748e586437012f63a7e1d9551e2979f29a9/cumulusci/cli/flow.py#L137

**Comment by davidmreed** [comment]
It's documented now - I think this is a fairly recent addition: https://cumulusci.readthedocs.io/en/stable/cli.html#specify-task-options-when-running-flows

**Comment by Julian88Tex** [comment]
@davidmreed Thanks so much!
