### ISSUE TITLE
github_release_notes task adds a parenthesis to PR link

### ISSUE THREAD

**Issue by georgeslater** [SFDO-Tooling/CumulusCI#3181]
### Describe the bug

The `github_release_notes` task incorrectly adds a closing parenthesis to the PR link.

Example output is:

```
# Changes                                                                                                               
                    123456 - Did the thing                            
                    [[PR537](https://github.com/foo/bar/pull/537)]      
                    123457 - Did something else            
                    [[PR539](https://github.com/foo/bar/pull/539)] 
```

If I click the links, I am redirected to `https://github.com/foo/bar/pull/537)` and `https://github.com/foo/bar/pull/539)` (note the parenthesis).  We only keep our builds for a month but this has been happening since at least April 4th.

### Reproduction steps

Run a flow that uses the `github_release_notes` task such as `release_2gp_beta` 

### Your CumulusCI and Python versions

CumulusCI: 3.56.0
Python: 3.8.12

### Operating System

Linux

### CumulusCI installation method

brew

### Additional information

The CI job is running as an Azure DevOps Pipeline if that makes a difference.

**Comment by jstvz** [comment]
@georgeslater I'm not able to repro this with your example output:

```markdown
[[PR537](https://github.com/foo/bar/pull/537)] 
```
Produces: [[PR537](https://github.com/foo/bar/pull/537)]                          

Where is the markdown being rendered? Or are you attempting to click the URL from your CI logs instead?

**Comment by georgeslater** [comment]
Sorry, you're absolutely right - it only fails from within the Azure CI system.  In GitHub itself there is no issue.  I'll close this out.
