### ISSUE TITLE
Create a Dev Container with CumulusCI

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#3219]
### Feature Type

I'm interested in functionality that has to do with CumulusCI's architecture or overall capabilities.

### Describe the solution you'd like

Create a [dev container](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers) (docker) that includes CumulusCI installed for GitHub Codespaces in CumulusCI repo so development can be done on the browser easily.

**Comment by bethbrains** [comment]
Hi @Julian88Tex . There is an open issue that looks similar, #577 , that looks like it even has a link to a community-maintained docker image w/ cci. Does this meet your needs?

**Comment by Julian88Tex** [comment]
@bethbrains I would say almost :-D. Having a docker container already should make this one even easier, but specifically, this issue relates to creating a Dev Container for use in GitHub Codespaces. Having a docker by itself doesn't mean it's usable by a Codespace. You also need a `devcontainer.json` which references the docker container.

**Comment by RupertBarrow** [comment]
https://hub.docker.com/repository/docker/rupertbarrow/salesforcedx-cci

**Comment by Julian88Tex** [comment]
> https://hub.docker.com/repository/docker/rupertbarrow/salesforcedx-cci

Thanks @RupertBarrow ! I will probably use this for some of my actions. That being said I think it still needs one more file to satisfy this feature request.

**Comment by RupertBarrow** [comment]
@Julian88Tex 
What file are you missing ? cci is there, that is why I created it !

If you need to expand it, read the last lines of the README here : 
https://github.com/RupertBarrow/salesforcedx-cci-Docker

**Comment by Julian88Tex** [comment]
@RupertBarrow sure for this feature request I'm pretty sure a `devcontainer.json`. For a Dev Container I believe it's a Dev Container file paired with a docker image.

**Comment by attilah** [comment]
There is one more implementation exists I found Today: https://github.com/GeekStewie/SalesforceDX_CCI_DEV

**Comment by Julian88Tex** [comment]
@attilah thanks so much!
