### ISSUE TITLE
dev_org flow on sandbox

### ISSUE THREAD

**Issue by ajanicko** [SFDO-Tooling/CumulusCI#3322]
### Describe the bug

Hello, 

I am trying to run dev_org flow against a sandbox and suddenly it started throwing this error after I added more metadata into the project.

### Reproduction steps

1. run dev_org flow against sandbox

### Your CumulusCI and Python versions

CumulusCI version: 3.63.0 (C:\Users\ajani\.local\bin\cci)
Python version: 3.9.0 (C:\Users\ajani\.local\pipx\venvs\cumulusci\Scripts\python.exe)

### Operating System

Windows 10

### Error Gist

https://gist.github.com/ajanicko/81ba04d38118fa990655cf4ac73cb3d4

**Comment by prescod** [comment]
Workaround identified:

https://gist.github.com/ajanicko/81ba04d38118fa990655cf4ac73cb3d4?permalink_comment_id=4269938#gistcomment-4269938

And internal bug filed.
