### ISSUE TITLE
Scratch org creation dev hub issue

### ISSUE THREAD

**Issue by ajanicko** [SFDO-Tooling/CumulusCI#3329]
### Describe the bug

I had some issues with authentication, so I decided to delete all authenticated orgs and aliases and try again. This approach did fix some issues, but created a new one. Now when I try to use cci flow run dev_org, CumulusCI can't recognize my dev hub even though it is set.

C:\Users\ajani\OneDrive\Documents\sfdx\holver-salesforce>sfdx force:config:list      
=== List Config
Name                   Value              Location
─────────────────────  ─────────────────  ────────
defaultdevhubusername  holver_prod_sfdx4  Local
defaultusername        holver_prod_sfdx4  Local

### Reproduction steps

1. delete .sfdx authenticated orgs and aliases
2. run sfdx auth:web:login --setdefaultdevhubusername --setalias holver_prod_sfdx4 
3. run cci flow run dev_org --org dev

### Your CumulusCI and Python versions

CumulusCI version: 3.63.0 (C:\Users\ajani\.local\bin\cci)
Python version: 3.9.0 (C:\Users\ajani\.local\pipx\venvs\cumulusci\Scripts\python.exe)

### Operating System

Windows 10

### Error Gist

https://gist.github.com/ajanicko/6801a4e655570a342eecb5c4d54b35f8

**Comment by ajanicko** [comment]
Creating scratch org with command: sfdx force:org:create  -f orgs/dev.json -w 120 --targetdevhubusername CCIDevHub -n --durationdays 7 -a
                    holver-salesforce__dev adminEmail=91895754+ajanicko@users.noreply.github.com
                    
Looks like it somehow, somewhere still remembers the old dev hub. which no longer exists

**Comment by davidmreed** [comment]
What happens if you do `cci service info devhub`?

**Comment by ajanicko** [comment]
C:\Users\ajani\OneDrive\Documents\sfdx\holver-salesforce>cci service info devhub
        devhub:default        

  Key              Value     
 ────────────────────────────
  username   CCIDevHub
  
  how do I change this?

**Comment by davidmreed** [comment]
Run `cci service remove devhub` to always use the default set in SFDX.

**Comment by ajanicko** [comment]
I tried, but it did not work
![image](https://user-images.githubusercontent.com/91895754/186352212-1cc66886-7aa2-47a3-8558-313f6df4fd91.png)
