### ISSUE TITLE
Release 2GP Beta issue

### ISSUE THREAD

**Issue by dlisovsky** [SFDO-Tooling/CumulusCI#3333]
### Describe the bug

The `create_package_version` is failing with: `expected str, bytes or os.PathLike object, not NoneType`

### Reproduction steps

Run `cci flow run release_2gp_beta` for sfdx project that worked fine and now failing after the SFDX/CumulusCI upgrades.

### Your CumulusCI and Python versions

CumulusCI version: 3.63.0
Python version: 3.9.5

### Operating System

MacOS

### CumulusCI installation method

pipx

### Error Gist

[https://gist.github.com/dlisovsky/9ad83ef7fbab7d1dfcaacf739eceabda](https://gist.github.com/dlisovsky/9ad83ef7fbab7d1dfcaacf739eceabda)

### Additional information

sfdx-cli/7.164.2 darwin-x64 node-v16.17.0

Seems also related to [https://github.com/SFDO-Tooling/CumulusCI/issues/3332](https://github.com/SFDO-Tooling/CumulusCI/issues/3332) as I had to manually add alias in SFDX for scratch org created by CCI. Looks like CCI is adding additional . (dot) in the end of the username/alias that SFDX not able to find.

**Comment by dlisovsky** [comment]
The `3.64.0` release has fixed the issue.

**Comment by tahina-netizen** [comment]
Hello !
That update seems not fixing the issue for me.
For info:
- I used the flow `release_unlocked_beta` (instead of `cci flow run release_2gp_beta`)
-  I'm on _windows 10_
- Python version: 3.9.0
Error Gist: https://gist.github.com/tahina-netizen/0be0d1e0cce07e5adb6f131ef02cba68

**Comment by davidmreed** [comment]
@tahina-netizen Can you open a new issue with your details (please also include SFDX version) so that this doesn't get lost?

**Comment by tahina-netizen** [comment]
@davidmreed I opened a new issue here: https://github.com/SFDO-Tooling/CumulusCI/issues/3347
