### ISSUE TITLE
Missing metadata support for metadata type `customindex`?

### ISSUE THREAD

**Issue by mattmartin26** [SFDO-Tooling/CumulusCI#3381]
### Describe the bug

When running the `deploy_unmanaged_ee` flow against a persistent org and the `src` folder is created, the error is raised: `No parser configuration found for subdirectory customindex`.  Seems that CumulusCI doesn't (yet?) support that metadata type. However, as we have multiple custom fields that are marked as external IDs Salesforce change tracking seems to want to pull these into source, so we have done so thus far.

### Reproduction steps

1. Clone [this repo](https://github.com/Cath-Strategic-Tech/MFC-Fundraising) and move to [this branch](https://github.com/Cath-Strategic-Tech/MFC-Fundraising/tree/feature/FUND-134-deploy-FRA-product-to-managed-org)
2. Run the flow `client_org` against a persistent org that already has NPSP installed (or possibly even a scratch org... haven't tried). 
3. Error should occur during the `update_package_xml` phase of `deploy_unmanaged_ee`. 

### Your CumulusCI and Python versions

CumulusCI version: 3.66.0 (/Users/matthewmartin/.local/bin/cci)
Python version: 3.10.4 (/Users/matthewmartin/.local/pipx/venvs/cumulusci/bin/python)

### Operating System

Macbook Pro, macOS Monterrey, Apple M1 Pro

### CumulusCI installation method

pipx

### Error Gist

https://gist.github.com/mattmartin26/e1a4174acf5478db4a70c6cc6a2d8e28

### SFDC Articles on Custom Indexes

- [Improve Performance of SOQL Queries using a Custom Index](https://help.salesforce.com/s/articleView?id=000325247&type=1)
- [Metadata API Developer Guide: Indexes](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/)

**Comment by jstvz** [comment]
Thanks for the report. We'll have a fix out in the next release.

**Comment by jstvz** [comment]
@mattmartin26 There's a fix in review, but I wanted to bring this [Known Issue](https://trailblazer.salesforce.com/issues_view?title=metadata-api-deploy-error-custom-index-allownullvalues-is-not-valid-in-version-55-0-in-winter-release-orgs&Id=a1p4V000002an7L) to your attention. There are also [reports](https://salesforce.stackexchange.com/questions/368274/how-to-add-a-new-field-with-a-custom-index-to-a-managed-package) that there are issues related to packaging. 

FYI: You can try excluding any problematic components by adding them to your [`.forceignore` file](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_exclude_source.htm).

**Comment by mattmartin26** [comment]
Thanks for the updates @jstvz !
