### ISSUE TITLE
load_dataset ContentVersion

### ISSUE THREAD

**Issue by ajanicko** [SFDO-Tooling/CumulusCI#3398]
### Describe the bug

When trying to run load_dataset task on a mapping containing ContentVersion object with VersionData field, the task fails due to:

Error: Error on record with id 1: UNSAFE_HTML_CONTENT: Note can't be saved because it contains HTML tags or unescaped characters that are not allowed in a Note. (VersionData)

Seems like CCI, can't really retrieve VersionData, as in the data.sql file, VersionData is populated as a relative URL '/services/data/v55.0/sobjects/ContentVersion/068Aa0000001uL7IAI/VersionData'. If this were to be fixed, CCI would somehow have to download the file from the link first and I don't think that is happening.

### Reproduction steps

1. Generate mapping.yml with ContentVersion object, containing VersionData field.
2. Run load_dataset task.

### Your CumulusCI and Python versions

CumulusCI version: 3.64.0
Python version: 3.9.0

### Operating System

W10

### Error Gist

https://gist.github.com/ajanicko/034a39f7089f70e1636f92263fe0e548

**Comment by davidmreed** [comment]
CumulusCI's data tooling does not support capture or load of ContentVersion data. Creating ContentVersion data is supported in [Snowfakery](https://snowfakery.readthedocs.io/en/latest/salesforce.html#contentversions).
