### ISSUE TITLE
Error creating 2GP version in Winter '23

### ISSUE THREAD

**Issue by leboff** [SFDO-Tooling/CumulusCI#3415]
### Describe the bug

In my specific case, we are creating a managed 2GP version with quick actions that have a dependency on record types in an unlocked 2GP. Building the package version with CumulusCI results in an error like:

`Error: UNKNOWN_EXCEPTION : Can’t add component <quick action name> because it’s associated with metadata from a managed 2GP package. Managed 1GP packages can’t depend on managed 2GP packages.`

I did some digging and it looks like when building with CumulusCI, the package.xml in the metadata sent in the 'Package2CreateVersionRequest' contains the 'fullName' field (with the project name in that field). I think this confuses the SFDC package validation into thinking you're creating a 1GP package, and the build fails with that error

I assume generally when generating a new 2GP version in CumulusCI that has dependencies on another 2GP, the validation fails with that error, but I've only tested/verified with the Record Type/ Quick Action metadata

### Reproduction steps

1. Create an Unlocked 2GP that contains record types (Package A)
2. Create a new CumulusCI project (Package B)
3. Add a quick action in Package B that references a record type from Package A
4. Attempt to create a new package version with CumulusCI task `create_package_version`

### Your CumulusCI and Python versions

CumulusCI version: 3.67.1 
Python version: 3.10.4

### Operating System

macOS 12.6

### CumulusCI installation method

pipx

### Additional information

Changing this:

https://github.com/SFDO-Tooling/CumulusCI/blob/f69f3946b94ef30c0e7953d282e6230b82b5117b/cumulusci/tasks/create_package_version.py#L212

to `None` resolves the issue, but I'm unsure if there are any side effects to that.

**Comment by jstvz** [comment]
@leboff Thank you for the report and pull request. We may need to discuss this change internally, so there may be some delay in getting it reviewed.

**Comment by jstvz** [comment]
Fixed in #3636.
