### ISSUE TITLE
PackageType enum value is formatted badly when creating package version

### ISSUE THREAD

**Issue by attilah** [SFDO-Tooling/CumulusCI#3436]
### Describe the bug

While I was trying to add `cci` to our workflow in a 2GP Managed package, when executing the `release_2gp_beta` flow cci failed to find the existing package and wanted to create a new one.

This was printed to the screen:
`Checking for existing PackageTypeEnum.managed Package named Veezla | Core with namespace vz`, notice the enum value string...

And this was the SOQL generated, which also has the enum value incorrectly:
`SELECT Id, ContainerOptions FROM Package2 WHERE IsDeprecated = FALSE AND ContainerOptions='PackageTypeEnum.managed' AND IsOrgDependent=False
                    AND Name='Veezla | Core' AND NamespacePrefix='vz'`

After adding `.value` to https://github.com/sfdO-Tooling/cumulusci/blob/main/cumulusci/tasks/create_package_version.py#L273 and https://github.com/sfdO-Tooling/cumulusci/blob/main/cumulusci/tasks/create_package_version.py#L276 cci worked as expected.

### Reproduction steps

1. Have a 2GP package
2. Execute the release_2gp_beta flow

### Your CumulusCI and Python versions

CumulusCI version: 3.68.1 (/Users/attila/.local/bin/cci)
Python version: 3.11.0 (/Users/attila/.local/pipx/venvs/cumulusci/bin/python)

You have the latest version of CumulusCI ⛅

See the latest CumulusCI Release Notes: https://github.com/SFDO-Tooling/CumulusCI/releases/tag/v3.68.1

### Operating System

macOS

### CumulusCI installation method

pipx

**Comment by davidmreed** [comment]
Thank you, @attilah! That's definitely a bug. We'll get that fixed as soon as we can work it in.

**Comment by davidmreed** [comment]
Tracking as W-12045409
