### ISSUE TITLE
Running a task that calls Command from a flow doesn't execute

### ISSUE THREAD

**Issue by jeremyherzberg-usds** [SFDO-Tooling/CumulusCI#3449]
### Describe the bug

We use github codespaces and we're attempting to use Cumulus CI to orchestrate the post create phase of the dev container spin up using a custom flow. When I run the flow the tasks that run command actions do not run and thus the flow doesn't complete the setup actions.

### Reproduction steps

1. create a task that calls a cci command like `cci service connect github`
2. call the task from a flow

### Your CumulusCI and Python versions

CumulusCI version: 3.69.0
Python version: 3.10.7

### Operating System

Ubuntu 20.04.5 LTS

### CumulusCI installation method

pipx

**Comment by davidmreed** [comment]
Interesting. I don't know much about Code Spaces and haven't had the opportunity to play with them yet. Do you have the capability to set up environment variables in that context? That's how we recommend configuring in a headless CI context.

Where is the GitHub credential coming from that you want to expose to CCI?

**Comment by jeremyherzberg-usds** [comment]
@davidmreed I understand what you're saying. I think this is not a bug. Thank you for your response!
