### ISSUE TITLE
chdir to repo root at beginning of flow 

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/CumulusCI#350]
cci commands can be run in any directory of the repository, but our pre-configured flows use paths relative to the repo root.

we should chdir to the repo root in python, with an override flag.

OR

at the very least print a warning.

**Comment by cpolcyn** [comment]
I'd prefer we print a warning. Can't we change flows to use correct paths no matter the pwd?

**Comment by cdcarter** [comment]
we should write our tasks in mind to be correct, but many of them just start working from `cwd`

**Comment by cpolcyn** [comment]
Can we close this and open a new issue to fix tasks incorrectly using `cwd` instead of repo root?

**Comment by davisagli** [comment]
We now change to the project repo_root for each task.
