### ISSUE TITLE
better error message when a service isn't configured

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/CumulusCI#353]
in the CLI, when a user runs a task depending on Github (or another service), we print the python exception.

when ServiceNotConfigured gets thrown by the CLI, we should display a nice error instructing the user to connect that service (including the service description, which might have additional documentation).

**Comment by Br4nd0R** [comment]
@davisagli - It looks like [one of the error messages](https://github.com/SFDO-Tooling/CumulusCI/blob/beb2a26dc1196e03b4740d6754f0b9a235235064/cumulusci/core/keychain/EncryptedFileProjectKeychain.py#L104) suggests `cci service connect {service}` and [the other](https://github.com/SFDO-Tooling/CumulusCI/blob/beb2a26dc1196e03b4740d6754f0b9a235235064/cumulusci/core/keychain/BaseProjectKeychain.py#L250) shows which services are configured.

The blame indicates that I've modified both of these a few months ago. Do you want me to create better parity between the two message or are we okay with closing this out?

**Comment by davisagli** [comment]
I think we're good here. The recent change to _not_ show stack traces helped.
