### ISSUE TITLE
Setting `skip_future_releases` option for `github_automerge_feature` task in cumulusci.yml to false is ignored.

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#3594]
### Describe the bug

Whenever I attempt to change the option `skip_future_releases` to `False` and run `github_automerge_main` it appears to be ignored. This is confirmed when I attempt to do the same in a flow like `release_beta` and run it.

### Reproduction steps

1. Create `feature/001`, `feature/002`, and `feature/003` branches.
2. Make a commit on your main branch.
3. Add the following to your `cumulusci.yml` file:
```
    github_automerge_main:
        options:
            skip_future_releases: False
```
5. Run `github_automerge_main`

Result: Not all branches are updated with commit on main.

Expected Result: All branches are updated by a commit on main.

### Your CumulusCI and Python versions

CumulusCI version: 3.75.1 (/Users/julianjoseph/.local/bin/cci)
Python version: 3.10.0 (/Users/julianjoseph/.local/pipx/venvs/cumulusci/bin/python)

### Operating System

MacOS 13.3.1 (a)

### CumulusCI installation method

pipx

### Additional information

This is very obvious when you run `github_automerge_main` task within a flow since you get CLI logs like this:

```
                    ------------------------------------------------------------                      
                    Running task: github_automerge_main                                               
                    ------------------------------------------------------------                      
                                                                                                      
                    Options:                                                                          
                      commit: e1d00d5cfa27d0fdabeb8a5e952fde8ca21732fe                                
                      source_branch: main                                                             
                      branch_prefix: feature.                                                         
                      skip_future_releases: True                                                      
                      update_future_releases: False  
```

A workaround is running `github_automerge_main` within the command task:

```
            4:
                task: command
                options:
                    command: cci task run github_automerge_main --skip_future_releases false
```

**Comment by Julian88Tex** [comment]
Loom with some more context: https://www.loom.com/share/8189fb6fcbf6485e9ff8157459b494bc?sid=3657ab41-c8b2-4240-924c-3bcdff5172a5

**Comment by jstvz** [comment]
Thank you for the great report. You can also use this as a workaround:

```yaml
    github_automerge_main:
        options:
            skip_future_releases: 'false'
```


The root cause is:

https://github.com/SFDO-Tooling/CumulusCI/blob/e5e9d8b2341b644d0b1e1284513b613c8445d3ab/cumulusci/tasks/github/merge.py#L52-L54

Which will always return `True` for `skip_future_releases: False` or `skip_future_releases : false` because those get converted to booleans before this line is run. (Because the CLI option doesn't go through the Pydantic model it's a `str`, which is truthy).

We'll have a fix out in the next release.

**Comment by Julian88Tex** [comment]
@jstvz My pleasure and thanks for the explanation. I partially got that, but I think [ChatGPT helped fill in the blanks](https://chat.openai.com/share/2f59e413-d065-4040-9b11-45cded09b2f2) :).
