### ISSUE TITLE
Upgrade all SFDX Commands to SF Commands

### ISSUE THREAD

**Issue by GeekStewie** [SFDO-Tooling/CumulusCI#3621]
### Feature Type

I'm interested in functionality that solves a current problem or limitation in how CumulusCI works.

### Does your feature request solve a current problem?

I noticed this in the SFDX update today:

`IMPORTANT ANNOUNCEMENT, PLEASE READ: We no longer update sfdx (v7); the last stable version is 7.209.6. You can keep using sfdx (v7) if you want, but it won't contain new features or bug fixes. And we no longer update this page.`

And looking at the installers, it now defaults to the SF CLI when you install via npm etc. 

I know we have had warnings for a while now but looks like the move needs to happen to ensure we are not using unsupported CLIs

### Describe the solution you'd like

Migrate all SFDX commands within CumulusCI to SF equivalents

**Comment by jstvz** [comment]
Initial work tracked in [W-13772594](https://gus.lightning.force.com/a07EE00001WL3vEYAT).

**Comment by mattmartin26** [comment]
Would really appreciate an update on this, our CTO is considering moving away from CumulusCI depending on if/how soon CCI will transition from SFDX to SF.

**Comment by davisagli** [comment]
@jlantz It looks like the Github Actions need to be updated to install `sf` rather than `sfdx`, though: https://github.com/SFDO-Tooling/CumulusCI/blob/main/.github/workflows/feature_test.yml#L77

**Comment by jlantz** [comment]
@davisagli Great point. That's an easy PR that I'll put together shortly as an early warning system at least.

**Comment by jstvz** [comment]
@mattmartin26 Thanks for flagging this. Here's a quick update on the SFDX to SF CLI transition:

- We've started work to migrate SFDX commands in CumulusCI to SF. It's on our   radar. For details, check out the discussion on the proposed ADR in #3630 (feedback welcome).
- As @jlantz mentioned, the new `sf` CLI still ships with `sfdx`, commands will still function as expected despite the warnings.
- We're adjusting our GitHub Actions per @davisagli's spot, to reflect the ongoing changes.

**Comment by georgeslater** [comment]
The [latest CLI release candidate's release notes](https://github.com/forcedotcom/cli/blob/main/releasenotes/README.md#2486-july-3-2024-stable-rc) states that the `force:org:create` command will stop working on November 6th, 2024.  Is that something to be concerned about?

**Comment by liamcollerton-giveclarity** [comment]
And as of today, I can't run any flow that creates a scratch org.

It gives the error

Error: Failed to create scratch org: 
 Did you mean force cmdt create? [2m(Y/n)[22m[40G
[?25h
 »   Warning: force org create is not a sf command.
 »   Error: Run sf help force for a list of available commands.

I see that the PR has been merged (https://github.com/SFDO-Tooling/CumulusCI/pull/3829)

Hopefully the release is imminent.

**Comment by Julian88Tex** [comment]
@jstvz I'm guessing you're already on this, but I just wanted to tag you since it sounds like a high-priority issue as of late.

**Comment by jstvz** [comment]
Thanks, @Julian88Tex, it's a high-priority for us too. We are actively working on this and will cut a release as soon as it's ready.
