### ISSUE TITLE
[cumulusci.robotframework.Salesforce] Input form data keyword returns a "No form handler" error with new SalesForce API = 59.0

### ISSUE THREAD

**Issue by frankeetou** [SFDO-Tooling/CumulusCI#3657]
### Describe the bug

We run a WebDriver test for one of our LWC (Account Creation) and it was working and populating the text fields on a prior apiVersion (58), now on newly created scratch orgs based on apiVersion 59, it's returning the following error:

![image](https://github.com/SFDO-Tooling/CumulusCI/assets/44180046/46dcf0aa-bd2b-4bea-a7ae-33cd3b4eaba0)

The keyword implementation we are using
```
Fill in all required fields for the Quick Create form
    ${firstName}        Get fake data       first_name
    ${lastName}         Get fake data       last_name
    Input form data
    ...     First Name                  ${firstName}
    ...     Last Name                   ${lastName}
    ...     Contact Type                Alumna/Alumnus.     #This is a dropdown field
    ...     Account Relationship        Head of Household.     #This is a dropdown field
    ...     Legal Credit %              100
    ...     Gift Recognition Credit %   100
```

That tag: `'lightning-primitive-input-simple'` was introduced within the new v 59 API

We also have the following WARN when executing the tests:
![image](https://github.com/SFDO-Tooling/CumulusCI/assets/44180046/da9fb78f-7153-495e-bfd6-672bad706853)

### Reproduction steps

1. Identify a LWC with text input or checkbox in your org
2. Create a sample robot test and use the "input form data" keyword from cumulusci library
3. Execute the test

### Your CumulusCI and Python versions

MacOs
CumulusCI version: 3.79.0
Python version: 3.11.3

Windows 11
CumulusCI version: 3.79.0
Python version: 3.10

### Operating System

MacOs Ventura 13.0 and Windows 10

### Windows environment

PowerShell

### CumulusCI installation method

None

### Additional information

**NOTE**: Multipick (dropdown) fields are working fine! with this keyword

**Comment by RobertoMartinez-districtm** [comment]
Did anyone find a way to work around that bug? @frankeetou , what are you doing in the meantime?

**Comment by frankeetou** [comment]
Not a quick one , but the workaround would be using selenium commands or keywords with different locators (depending on the locators strategy your are using). Unfortunately this is one of the most important UI keywords from CCI Salesforce Library (in my opinion). Still waiiting to see if they are going to tackle it or not

**Comment by RobertoMartinez-districtm** [comment]
I agree, it's definitely not trivial keyword given that pretty much any new records creation test would need to have an Name field populated. Let's hope it gets fixed quickly.

**Comment by frankeetou** [comment]
> I agree, it's definitely not trivial keyword given that pretty much any new records creation test would need to have an Name field populated. Let's hope it gets fixed quickly.

@RobertoMartinez-districtm just FYI, the workaround we are doing right now is using the "Populate Form" keyword instead.. which is field specific.

**Comment by RobertoMartinez-districtm** [comment]
Thanks! Will try it out

**Comment by RobertoMartinez-districtm** [comment]
Has this been fixed with v3.83.0?

**Comment by chanyahn-st** [comment]
@jstvz (please let me know if I should defer this question to a different contributor) I am working on this issue right now, and I'm having trouble testing the fix using the project directory I'm currently working on. How do you go about testing the features that are currently being worked on outside of the tests?

**Comment by chanyahn-st** [comment]
@vsbharath I see you made the most recent commit to the repo, would you mind letting me know about how the PR process? I am ready to open one for this issue, but I couldn't find a way to contact the relevant personnel to open a new feature branch. Any help is appreciated!

**Comment by vsbharath** [comment]
@chanyahn-st Please fork it and open a PR once your changes are done. We can review it and merge once everything is good. 

Note: Due to limited support, PR review and merge might take longer time.
