### ISSUE TITLE
sdfx command not found

### ISSUE THREAD

**Issue by lucascummins** [SFDO-Tooling/CumulusCI#3694]
### Describe the bug

The latest version of the Salesforce CLI does not come with `sfdx` commands. Any tasks using `class_path: cumulusci.tasks.sfdx.SFDXOrgTask` will fail since the sfdx commands don't exist

### Reproduction steps

1. Install Salesforce CLI (npm install sfdx-cli --global). Make sure you've uninstalled prior versions of CLI
2. Create CCI task using `class_path: cumulusci.tasks.sfdx.SFDXOrgTask`
3. Run cci task
4. Receive error missing sfdx
n. ...

### Your CumulusCI and Python versions

CumulusCI version: 3.80.0 (/Users/lcummins/.local/bin/cci)
Python version: 3.10.2 (/Users/lcummins/.local/pipx/venvs/cumulusci/bin/python)

You have the latest version of CumulusCI ⛅

See the latest CumulusCI Release Notes: https://github.com/SFDO-Tooling/CumulusCI/releases/tag/v3.80.0

### Operating System

Mac Version 13.4.1

### CumulusCI installation method

brew

**Comment by jstvz** [comment]
`sfdx-cli` is deprecated, and no updates are planned. Use `@salesforce/cli` instead. See https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm

**Comment by lucascummins** [comment]
@jstvz I have tasks that are using SFDXOrgTask class but it uses the `sfdx` commands (https://github.com/SFDO-Tooling/CumulusCI/blob/main/cumulusci/tasks/sfdx.py#L20C1-L20C9). How can I create custom cci tasks and use `sf` commands?
