### ISSUE TITLE
Optionally prevent downgrades of dependencies

### ISSUE THREAD

**Issue by Brent-Stewart** [SFDO-Tooling/CumulusCI#373]
This is mostly inspired as a workaround to W-3809423 (https://success.salesforce.com/issues_view?id=a1p3A0000008gaZQAQ), but I think would be useful in general.

When using the task `update_dependencies` to handle dependencies on managed packages, if one of the orgs we are working in (for example the feature org in a CI flow, or different developers' orgs) has a newer version of one of the dependencies for testing, we do not want the update task to attempt a downgrade.  In our scenarios the downgrade will always fail as there are other things dependent on it.  Rather than waste time attempting the downgrade it would be better to just fail the build as soon as it is apparent a downgrade is needed.  On other occasions we would want the task (and build) to ignore the downgrade and continue with the newer version.

Obviously there are scenarios where the current behaviour is desired, so I'd propose new argument(s) to the task to select one of three modes:
- Require Downgrades (default): this is the current behaviour
- Fail on Downgrades: the task would stop and return an error if a downgrade is needed, without ever attempting it
- Allow newer versions: If the version installed has a higher number than the required version (including betas), make no changes to the installed version and continue with the task / build

I'm not sure if a single option that takes a string to specify the mode is preferable to additional 'boolean' options: the booleans would be mutually exclusive (although this is true with other tasks) but probably slightly easier to build and document.

**Comment by jlantz** [comment]
This is a really interesting use case I hadn't thought of before.  I like the idea.  The dependency map building logic is a bit tricky but this should be possible to do.

I'm headed out of town for the next month but @cpolcyn is available to review a contribution if you feel up to taking a stab at it.

In the meantime, there is a workaround you could do:

- Create a subclass of cumulusci.tasks.salesforce.UpdateDependencies
- Override the _uninstall_dependencies method in the subclass to just:
`def _uninstall_dependencies(self):
    pass`
- In cumulusci.yml:
`update_dependencies:
    class_path: localdir.filename.classname_here

**Comment by Brent-Stewart** [comment]
Thanks for the workaround, that's a neat solution.

I'll have a go at the implementation, but I'm inexperienced with python so the tests might not be great...

**Comment by davisagli** [comment]
We added a way to do this in cumulusci 2.5.3
