### ISSUE TITLE
Repository is locked behind an IP Allow-list

### ISSUE THREAD

**Issue by dcinzona** [SFDO-Tooling/CumulusCI#3755]
### Describe the bug

Can no longer access SFDO-Tooling repositories on github from non-Salesforce IPs (including logging issues)

### Reproduction steps

1. Use a computer not on VPN or not connect to the Salesforce network
2. Browse to github.com/sfdo-tooling
3. Error is displayed (Access forbidden from this IP Address)

### Your CumulusCI and Python versions

N/A

### Operating System

Windows / Mac

### CumulusCI installation method

None

### Additional information

Didn't really have a good place to submit this ticket, so figured I'd put it here

**Comment by leboff** [comment]
@dcinzona this is the same for all open source salesforce repos (and is highly annoying) but there's not much anyone (except github) can do about it. From the[ github docs:](https://docs.github.com/en/enterprise-cloud@latest/admin/configuration/hardening-security-for-your-enterprise/restricting-network-traffic-to-your-enterprise-with-an-ip-allow-list)

"If a user is signed into GitHub.com, the IP allow list determines whether the user can access the organization's public resources. The list does not apply to anonymous access to public resources."
