### ISSUE TITLE
Configuration warning when cumulusci.yml name_exclude is set

### ISSUE THREAD

**Issue by BrandonEnclude** [SFDO-Tooling/CumulusCI#3816]
### Describe the bug

When a value is set for project.test.name_exclude in cumulusci.yml, I see the following "Cumulusci Configuration Warning":
```
CumulusCI Configuration Warning:
  'C:\\{path-to-my-project}\\cumulusci.yml' -> 'project' -> 'test' -> 'name_exclude'
    extra fields not permitted
NOTE: These warnings will become errors on Sept 30, 2022.
```

### Reproduction steps

1. Populate project.test.name_exclude with the name of a test class
2. Run `cci org browser dev` (or various other commands)

### Your CumulusCI and Python versions

CumulusCI version: 3.90.0
Python version: 3.11.6

### Operating System

Windows 11

### Windows environment

PowerShell

### CumulusCI installation method

pipx

**Comment by jstvz** [comment]
@BrandonEnclude This is working as intended. The `project.test` section only supports the `name_match` field. To exclude tests, you should use the `test_name_exclude` option in the `run_tests` command.

However, I agree it would be more consistent if `name_exclude` was also supported in the project config.
