### ISSUE TITLE
Use GitHub Discussions

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#3836]
### Feature Type

I'm interested in functionality that has to do with CumulusCI's architecture or overall capabilities.

### Does your feature request solve a current problem?

Yes. The current problem is that there is no place for the CumulusCI community to interact with the project ideas beyond the Trailblazer Community. Since CumulusCI isn't an official Salesforce product, we can't use IdeaExchange for ideas.

GitHub Discussions were added a few years ago to handle non-Issue and pre-Issue discussions that are open to the community and can be voted up and down. This could provide a place for the community to collaborate around the open source project.

### Describe the solution you'd like

Enable GitHub Discussions in the CumulusCI repository. The Salesforce CLI team is already using discussions effectively which provides a good model.

### Describe alternatives you've considered

A Slack workspace or other community run space. But, the GitHub repository is the most visible location for CumulusCI. The Trailblazer Community Group isn't really set up for the needs of managing discussions around an open source project like GitHub Discussions are.

### Additional context

I'm happy to help in configuring if needed.

**Comment by jstvz** [comment]
@jlantz Thanks for raising this! You’re right, and we’ve now enabled [GitHub Discussions for CumulusCI](https://github.com/SFDO-Tooling/CumulusCI/discussions/3838). This will provide a space for the community to collaborate, share ideas, and have discussions outside of formal issues.

We believe this will help with more open conversations around project improvements and ideas. While the Trailblazer Community has been useful, we feel that GitHub Discussions will be a better fit for managing open-source project interactions. We are still considering what role the Trailblazer Community will serve moving forward.
