### ISSUE TITLE
Task and Flow reference missing from documentation

### ISSUE THREAD

**Issue by jstvz** [SFDO-Tooling/CumulusCI#3848]
### Describe the bug

The Task and Flow reference sections are missing from the latest documentation. This appears to be due to a misconfiguration in the ReadTheDocs build process.

### Reproduction steps

1. Navigate to the documentation website.
2. Attempt to access the Task and Flow reference sections.
3. Notice that these sections are missing.

### Your CumulusCI and Python versions

CumulusCI version: 4.0.1 
Python version: 3.13.0

### Operating System

MacOS

### CumulusCI installation method

None

### Additional information

This issue was introduced after recent updates to the ReadTheDocs configuration. We'll correct the build process to include these sections.

**Comment by apretorius** [comment]
@jstvz Just noting that I'm watching this issue as I reference those docs almost daily! Getting by with running `cci task info` in the terminal but that's quite tedious to scroll through.

**Comment by jstvz** [comment]
@apretorius Restored on `main` until we cut a new release: https://cumulusci.readthedocs.io/en/main/cumulusci_tasks.html
