### ISSUE TITLE
Tag created with github_clone_tag has old timestamp

### ISSUE THREAD

**Issue by cpolcyn** [SFDO-Tooling/CumulusCI#396]
A tag created using the task github_clone_tag sometimes appears to have an older timestamp. It should be the time the tag was created, i.e. `now()`. I only notice this when doing releases for Cumulus.

**Comment by cpolcyn** [comment]
This is not necessarily an issue with CumulusCI. This also happens when tag is created by creating a new release from the GitHub web UI.

**Comment by davidmreed** [comment]
Closing issue as it's unclear that this is currently a problem. We can revisit.
