### ISSUE TITLE
Not able to connect multiple Org using Codeship and Circle CI

### ISSUE THREAD

**Issue by LovelIncapsulate** [SFDO-Tooling/CumulusCI#404]
As shown in the image I need to automated code flow from a different branch to different orgs how I can achieve that.
For now, I can use only one variable CUMULUSCI_CONNECTED_API, how can we use the same with the different name and diffrent values.

![image](https://user-images.githubusercontent.com/29042707/29818687-230a2a34-8cdb-11e7-8679-be9f9f10b5d7.png)

**Comment by jlantz** [comment]
Typically you only need a single connected app for all the orgs you want to connect.  If you need to deploy to different orgs, you'd just add multiple CUMULUSCI_ORG_orgname variables.  Then, the orgs would be available by their orgname.

**Comment by LovelIncapsulate** [comment]
Hey then what is the significance of CUMULUCSCI_CONNECTED_APP, and I am getting error of incorrect token when I try to connect different orgs of salesforce with same of CUMULUCSCI_CONNECTED_APP value.

**Comment by denverquentin** [comment]
Hi @jlantz, I'm trying to set the CUMULUSCI_CONNECTED_APP and CUMULUSCI_ORG_feature environment variables for use in Codeship and I can't find the JSON keys/values that I need to set to authenticate. Can you point me in the right direction?

**Comment by swagattalsania** [comment]
Hi @denverquentin. Which OS are you using? If you are on MAC simply type `cci org connected_app` and `cci org info feature --json` to get the required JSON values. I do not believe the first command uses a `--json` option so you will have to manually convert the output to a valid JSON. Somewhat like `{"callback_url": "http://localhost:8080/callback",     "client_id": "Test3MVG9zlTNB8o8BAK6fTCHmkWUsPOvFBRHAC.tsH8pfjl9klgCYFoxeTh",     "client_secret": "24542686485659057" }`

On Windows, simply run both the commands without the `--json` option and it should give you the expected output.

You can find more information [here](http://cumulusci.readthedocs.io/en/latest/cookbook.html#continuous-integration-with-cumulusci).

Hope this helps.
