### ISSUE TITLE
Apply incrementally increasing polling interval to InProgress state from MDAPI

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#438]
Sometimes a deployment takes a while to run.  We currently use incrementally increasing polling intervals when a deploy is "Pending" status but we still poll every second for "InProgress" status.  We should apply the same behavior to InProgress.

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL8OAAW" target="_blank">W-022282</a>

**Comment by Br4nd0R** [comment]
@davisagli - Is this already completed? Looking at `cumulusci/salesforce_api/metadata.py BaseMetadataApiCall._process_response_status()` seems to reset `check_num` to `1` once we detect that the status is `InProgress`. This is then runs in the [while loop in the _get_response()` method](https://github.com/SFDO-Tooling/CumulusCI/blob/7c7edf951bb4dbb5ca172c152d5f5a1f7fdf8356/cumulusci/salesforce_api/metadata.py#L160), which then starts increasing the value of `check_num`.

**Comment by davisagli** [comment]
@Br4nd0R yes I think you are right
