### ISSUE TITLE
Create a standard method in BaseTask to check the org_config

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#446]
Now that a scratch org config can contain `namespaced: true` which means the scratch orgs are created with the namespace from `sfdx-project.json` applied to the scratch org, it'd be nice for tasks to be able to restrict themselves to not run against orgs where they will fail.

An example is a namespaced scratch org where you try to run `install_prod` or `install_beta` against the namespace from `cumulusci.yml` (presumed to match `sfdx-project.json`).  The task would fail because you can't install a managed package with the same namespace as is applied in the scratch org.

Ideally, we'd have a BaseTask._validate_org() method that is always called and normally does nothing.  This would allow individual task classes to inspect the org_config as part of their initialization and immediately reject to run against an org that has the wrong config for the task.  This way task classes would have full control over their org validation logic.  If we find common patterns implemented across many task classes we could move those into BaseTask itself.

**Comment by cdcarter** [comment]
I think we would want to AOT validate the entire flow (in the case of `install_prod`), not each task once the flow runner gets there.
