### ISSUE TITLE
trialforce signup through the CLI

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/CumulusCI#466]
allow passing a 0TT id to the cli to signup an org.

scratch orgs with template ID requires specific perm.
or we do signuprequest and require a linked envhub.

both are lame.

**Comment by jlantz** [comment]
Even better, we could parse this into statusite and use the (yet to be built) statusite service in cci to get the template id via the api.  We should still allow manual template ids, but it'd be best to follow the path of defaulting to the latest and allowing manual override.

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL7eAAG" target="_blank">W-022281</a>

**Comment by davisagli** [comment]
This can be done in the scratch org definition file if the permission is enabled.
