### ISSUE TITLE
Zip unpackaged pre/post bundles and add to GitHub Release

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#47]
When creating a GitHub Release, upload the unpackaged/pre and unpackaged/post bundles from the package as individual zip attachments to the Release.

Also, pass the zip url to mrbelvedere to configure the bundles for installation.

Question: Does storing zips from every build potentially create issues with limits in GitHub?

**Comment by cdcarter** [comment]
this is very old, and although not inherently a bad idea, it doesn't benefit us much compared to other ideas of representing releases. certainly within CCI as a ready to go issue, nah.
