### ISSUE TITLE
namespace injection fails if a binary file is in the dir

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/CumulusCI#489]
See https://gist.github.com/jcschultz/87e7d5189ef9f31ae8dcbb1a3bda4092 for a traceback.

zip_inject_namespace tries to read each file in the given tree, and replace the namespace token with a namespace. 

this fails if the file cannot be safely decoded to ascii.

some options:

- catch `UnicodeDecodeError` and pass
- check the file type from the zip listing and skip binary
- whitelist the types of files that SHOULD receive namespace injection that we can guarantee we can decode.

**Comment by cdcarter** [comment]
Like, a .DS_Code.

**Comment by cdcarter** [comment]
Not actually closed. Stop gap in place, but we should use the metadata map for which files to actually edit.

**Comment by davisagli** [comment]
The stopgap is working pretty well.
