### ISSUE TITLE
Support for loading users (internal and external) with bulk data task

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/CumulusCI#532]
must be able to specify role + profile by developer name

must be able to refer to users by non-sfid in rest of sqlite database

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL7aAAG" target="_blank">W-022277</a>

**Comment by davidmreed** [comment]
Currently tracking as Epic `Enhanced Scratch Org User Management`.
