### ISSUE TITLE
support for loading non bulk-enabled entities 

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/CumulusCI#533]
custom settings per user, for just one example.

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL7ZAAW" target="_blank">W-022276</a>

**Comment by davisagli** [comment]
Added a separate task for loading custom settings in #1354
