### ISSUE TITLE
support for data transformation or expression syntax

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/CumulusCI#534]
map an sf field to an expression based on project configuration

sal use cases:
- date adjustments
- set contact emails to admin email+lastname for testing.

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL70AAG" target="_blank">W-022275</a>

**Comment by davisagli** [comment]
This was marked as Never in our internal tracker
