### ISSUE TITLE
Deploy errors "Required field is missing: encodingKey"

### ISSUE THREAD

**Issue by cpolcyn** [SFDO-Tooling/CumulusCI#540]
As of 2.0.0-b80 the deploy of Volunteers for Salesforce to its packaging org results in lots of "Required field is missing: encodingKey" errors:

https://mrbelvedereci.herokuapp.com/builds/15918

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL8PAAW" target="_blank">W-022283</a>
