### ISSUE TITLE
Note Failed Orgs During Batches

### ISSUE THREAD

**Issue by Joble** [SFDO-Tooling/CumulusCI#543]
This is just a small suggestion: During the adding of orgs to a batch, when the _"The specified SubscriberOrganizationKey is not eligible to receive this upgrade. It may not have the package installed, or has a beta version installed."_ error message is thrown, it would be valuable if the org ID in question was appended to a text file (or written out as a part of a summary at the end of the batching operation) to allow for further investigation. I am currently deploying to around 15,000+ orgs every week, so catching all of the failures can be problematic.

**Comment by davisagli** [comment]
You can use the push_failure_report task to generate a csv of orgs that failed a push request.
