### ISSUE TITLE
Create docker environment that contains cumlusci already installed to make it easier to get started contributing to cumulusci based products

### ISSUE THREAD

**Issue by dospromptman** [SFDO-Tooling/CumulusCI#577]
Suggestion from HED micro sprint at HED Summit by @nickarino

**Comment by jlantz** [comment]
We have another internal team that is currently building out a Dockerfile for CumulusCI which will be included soon :)

**Comment by dospromptman** [comment]
Is there any update on this?  Is there anything I can do to help with this (i.e. is it available internally but needs something done to make it public or something?)

**Comment by RupertBarrow** [comment]
Any news about this ?

**Comment by davisagli** [comment]
@RupertBarrow has developed a Docker image for CumulusCI: https://github.com/RupertBarrow/salesforcedx-cci-Docker
