### ISSUE TITLE
update_package_xml task adds diff noise

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/CumulusCI#600]
@bethbrains reporting that update_package_xml occasionally re-orders the package.xml and causes a lot of diff noise. she's going to send me a diff.

1) is update_package_xml ordering the file differently than platform retrieve?
2) or does NPSP just need to be re-ordered once and everything will be OKAY?

**Comment by davisagli** [comment]
Less of an issue now that using sfdx format is an option.
