### ISSUE TITLE
Install managed package as unmanaged package

### ISSUE THREAD

**Issue by topherlandry** [SFDO-Tooling/CumulusCI#603]
I've been having some issues with dynamically setting my `callbackUrl` in a connected app in a scratch org. I've reported the issue because I don't think it's working as intended, but I'm wondering if there's another way to work around the problem.

Is it possible to use cumulus to install a managed package as an unmanaged package. I updated my flow to use `deploy` with `unmanaged: True`, 'namespace_tokenize: True`, and my path as `src`, but it failed looking for a `package.xml` in the sub-directories under `src`.

Am I missing something? Is it possible to do this currently? If not I can certainly code this up and submit a PR.

**Comment by davisagli** [comment]
I'm cleaning out some older issues -- sorry for the lack of response last year.

This is what the `dev_org` flow is for in CumulusCI 2.
