### ISSUE TITLE
Ending "0" is not read in Cumulusci.yml file for dependency version number

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#605]
It appears that if "0" is the last character in a dependency's version number, it is removed and not interpreted when running commands like update_dependencies. This causes an error when CumulusCI attempts to install managed package.

**Example Cumulusci.yml**:
```
    dependencies:
        - namespace: rC_Inventory
          version: 1.10
```

**Example Resulting Logs**:
```
2018-04-17 23:33:18: Installing rC_Inventory version 1.1
2018-04-17 23:37:01: [Failed]: Update of InstalledPackage rC_Inventory: Error: Incorrect or missing password.
```

**Comment by davisagli** [comment]
The YAML parser reads this as a number instead of a string. I doubt we can do much about that. You can force it to be interpreted as a string by putting it in quotes: `version: "1.10"`
