### ISSUE TITLE
Anonymous Apex from file

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/CumulusCI#656]
Add AnonymousApexFromFileTask from sal/cumulus repos to core package. 

Needs to have updated options handling.

**Comment by force2b** [comment]
This is fixed with this PR: https://github.com/SalesforceFoundation/Cumulus/pull/3269

**Comment by cdcarter** [comment]
That's just for NPSP :)

**Comment by davisagli** [comment]
Done in #742
