### ISSUE TITLE
🐛 ci_beta flow: No longer able to pass version to install

### ISSUE THREAD

**Issue by e02d96ec16** [SFDO-Tooling/CumulusCI#665]
Something like `cci flow run ci_beta --org beta -o install_managed_beta__version "1.2 (Beta 11)"` installs the `latest_beta` instead. Extra fireworks if you don't have a Github service.

I suspect this was introduced in _beta98_ with nested flows (`ci_beta` adopted a `install_beta` child flow). I can not find anywhere (btw, what happened to the readthedocs updates?) how does option-passing happen in such a context (a parent flow can have two child flows who use the same tasks, so who would adopt the passed params?).

**Comment by cdcarter** [comment]
Hi @e02d96ec16 - thanks for the report. I can confirm that passing options to sub-flows isn't working. The syntax should be the same, but it doesn't work right now. I'll take a look today.

I haven't been able to update the online docs with the latest release yet, hopefully we can automate that soon. But I'll hopefully get them built in the next day...

**Comment by e02d96ec16** [comment]
Yeah, I actually wanted to contribute to the documentation a while back, but I had no idea how to get it built. Only managed to extract the code documentation, but this template (hope it's not sphinx itself) doesn't really know how to show things like `task_options` nicely 😞.
