### ISSUE TITLE
Password showing as None in cci org info

### ISSUE THREAD

**Issue by topherlandry** [SFDO-Tooling/CumulusCI#670]
This is popping back up again as an issue I'm running into consistently, and it's pretty annoying because I don't see anyway for me to fix it without editing the Cumulus source.

If I have a scratch org expire, then recreate it, the password in the org info shows as `None`.

This really breaks my work flow since I need to log into Salesforce with user name / password for the product I'm developing.

**Comment by jlantz** [comment]
We'll look into what's going on but in the meantime you should be able to work around the issue with:

`sfdx force:user:password:generate -u YourRepo__yourorgname`

In that example, `YourRepo` is your project -> name from cumulusci.yml name and `yourorgname` is the cci org name you are trying to get the password for.  CumulusCI will automatically set an sfdx alias on created scratch orgs using that naming pattern.

CumulusCI just calls out to sfdx force:org:display to get the org info displayed via `cci org info`.  If sfdx returns a password, we show it.  Setting a password via sfdx should cause it to show up in `cci org info`.
