### ISSUE TITLE
cci org scratch_import_sfdx <org_name> <username>

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#674]
Import a scratch org from the sfdx keychain into the cci keychain with a given name.  This would allow a workaround for cases where CumulusCI wrapping the sfdx command fails to create a scratch org but calling sfdx directly is successful by allowing scratch orgs created directly in sfdx to be imported into cci.

The command needs to construct a ScratchOrgConfig instance for an enabled scratch org using the username provided and attempt to get the org info.  If successful, record the org in the keychain with set_org.

**Comment by jstvz** [comment]
**lurch: add

**Comment by jstvz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fN7gAAE" target="_blank">W-027939</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fN7pAAE" target="_blank">W-027942</a>

**Comment by jstvz** [comment]
cf #877
