### ISSUE TITLE
Minor Errata for the Windows Section of the Install Docs

### ISSUE THREAD

**Issue by j-brandolini** [SFDO-Tooling/CumulusCI#724]
Hi there,

The documentation refers to **pip2** when it should be **pip** in the following section of the tutorial (docs/tutorial.rst):

See Part 1: Installing CumulusCI, Windows section

It might be worth mentioning that some people may have to activate their virtualenv via the command shell script found in C:\Python27\venvs\cci\Scripts\ as well

Regards,

John Brandolini

**Comment by jstvz** [comment]
Thanks for the report, John.

**Comment by j-brandolini** [comment]
Thanks!  I really like the project!!!  I was able to deploy the HEDA repository fairly easily with it, once I got through the install.  It is neat how it allows for project specific extensions, as well!

**Comment by jstvz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fNVsAAM" target="_blank">W-028233</a>

**Comment by davisagli** [comment]
These instructions got revised in version 2.1.0b1.

btw, welcome to Salesforce.org, @j-brandolini!
