### ISSUE TITLE
Support namespace injection into mapping.yml files

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#762]
Currently we need to have two separate mapping files solely to support unmanaged vs managed.  The only difference is the namespace prefix in front of objects/fields in the package metadata.

The simple solution would probably be to require mapping files to have the namespace prefix and support stripping it out automatically for unmanaged deployments via a task option

**Comment by davisagli** [comment]
As of cumulusci 3.16.0, namespace prefixes will automatically be added if the name only exists with the prefix in the org.
