### ISSUE TITLE
Include a default mapping.yml in skeleton structure for cci project init

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#763]
It'd be nice to include a directory structure such as `datasets/mapping.yml` and `datasets/demo/data.db` in projects created via `cci project init` which includes mappings for basic fields on Accounts and Contacts and includes the corresponding query, load, and delete tasks in the cumulusci.yml to bootstrap projects for using our Bulk API tasks.

This would be similar in concept to how we include the `create_contact.robot` file to provide a functional example of robot tests for a project.

**Comment by davisagli** [comment]
We did this
