### ISSUE TITLE
zip_inject_namespace needs to make sure replacement is text

### ISSUE THREAD

**Issue by davisagli** [SFDO-Tooling/CumulusCI#812]
See https://github.com/SalesforceFoundation/Cumulus/issues/3685 for traceback

**Comment by davisagli** [comment]
@mishraankit191 I looked into this and I think that we actually may have already fixed the problem in the 2.1.0b1 release. Can you try that? To upgrade, run `pip install cumulusci==2.1.0b1` after activating your virtualenv.

**Comment by mishraankit191** [comment]
Hi David,

For the time being we have removed translations from our source as the flows handle it through .org configuration better but I’ll try it with a new iteration once we’re done testing.

Thanks!
Ankit

**Comment by davisagli** [comment]
Okay. I'm going to close this issue for now, but feel free to re-open if you discover that it is still a problem.
