### ISSUE TITLE
Windows Install From Documentation and Workaround

### ISSUE THREAD

**Issue by Auchtor** [SFDO-Tooling/CumulusCI#815]
Using the updated documentation for Python 3 for windows, there are a few considerations for powershell and environment setup using a completely fresh install.

The necessary command to install a virtual environment in the default configuration is as such in powershell:
```
python -m venv ~\cci
~\cci\Scripts\Activate.ps1
```

Doing so may throw an error for a lack of ability to run scripts. Workaround for this is to run the following in powershell:
`Set-ExecutionPolicy Unrestricted -Scope CurrentUser`

Afterward, one may again try to invoke the virtual environment with 
`~\cci\Scripts\Activate.ps1`

Running pip install cumulusci after this is non-functional, erroring out with code 1.
The workaround for this was to run the following set of commands:

First upgrade pip install
`python -m pip install --upgrade pip`

Second upgrade setuptools to attempt to resolve the initial error of cumulus install
`pip install --upgrade setuptools`

Third install ez_setup. Note that this is necessary as pip install cumulusci will still error out.
`pip install ez_setup`

Last, install using easy_install:
`easy_install cumulusci`

This allowed for cumulusci to install, but still had a number of small exceptions that did not appear to be critical.

**Comment by davisagli** [comment]
Thanks for the report -- I don't have easy access to a Windows machine so was sort of guessing when I updated the installation instructions for Python 3. :(

We should really get the pip install working. Can you report the errors that you got when trying to pip install cumulusci?

**Comment by Auchtor** [comment]
Addendums:

A more effective way of initializing the virtual environment is:
```
python -m venv ~\cci
~\cci\Scripts\Activate.ps1
```

Also, the full output is:
`pip install cumulusci
Collecting cumulusci
  Using cached https://files.pythonhosted.org/packages/68/07/5db40854fe5f17d18df08891418f0dffb1a4cad8ff7f1df2e78d7bc2f1e5/cumulusci-2.0.13-py2.py3-none-any.whl
Collecting simple-salesforce==0.74.2 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/ad/59/c63fed8dcbfe91d398321d8d8f28c0a3660f861c8d5c57361af65ad13615/simple_salesforce-0.74.2-py2.py3-none-any.whl
Collecting rst2ansi==0.1.5 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/46/cb/fdb216f2b8bbec9c43655a79f2f280b2ba7822b2c8396ecceafa0c232320/rst2ansi-0.1.5-py3-none-any.whl
Collecting lxml==4.2.1 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/e8/5d/98f56e274bdf17f2e0d9016d1788ca80d26d8987dcd5e1d9416d86ee0625/lxml-4.2.1.tar.gz
Collecting plaintable==0.1.1 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/fc/3e/948a6007ef6fdbcfe9a228b8e3c46b75c86c40a60acf1909438b6adb9d5a/plaintable-0.1.1.tar.gz
Collecting coloredlogs==9.3.1 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/55/6c/4f79a8ff5aac9dd0a9dcdb0b58c9b9ae88b0c5a2ef2fd9900c3b6dd29d13/coloredlogs-9.3.1-py2.py3-none-any.whl
Collecting robotframework-seleniumlibrary==3.1.1 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/35/06/bac4b9dad29f4c59bb0c1d781c995940f4a39a964d5e0ea882e69c58495e/robotframework_seleniumlibrary-3.1.1-py2.py3-none-any.whl
Collecting pycrypto==2.6.1 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz
Collecting SQLAlchemy==1.2.7 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/c1/c8/392fcd2d01534bc871c65cb964e0b39d59feb777e51649e6eaf00f6377b5/SQLAlchemy-1.2.7.tar.gz
Collecting xmltodict==0.10.2 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/4a/5e/cd36c16c9eca47162fbbea9aa723b9ab3010f9ae9d4be5c9f6cb2bc147ab/xmltodict-0.10.2.tar.gz
Collecting raven==6.7.0 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/51/7c/bdfa7eff52208a949bc5ab770c084f4725c42dde41e36d5a9e15f11a9a14/raven-6.7.0-py2.py3-none-any.whl
Collecting click==7.0 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting PyGithub==1.39 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/fd/28/c42bdd56111dae8c622c01af69e6d7f3d3ff0a96ad846f221749701f86b1/PyGithub-1.39.tar.gz
Collecting github3.py==0.9.6 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/b9/bd/9e433bd695567ccf2bdc0f4c2cdc7da2ce2bb8467e405b2fca62631d8690/github3.py-0.9.6-py2.py3-none-any.whl
Collecting requests[security]==2.18.4 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting sarge==0.1.4 (from cumulusci)
  Using cached https://files.pythonhosted.org/packages/bc/9a/a715357f0f0a394edf964fb52b8b39551b629f4d1c996ade5f600fb3d278/sarge-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Mblanski\AppData\Local\Temp\pip-install-drda0fvn\sarge\setup.py", line 11, in <module>
        import sarge
      File "C:\Users\Mblanski\AppData\Local\Temp\pip-install-drda0fvn\sarge\sarge\__init__.py", line 604
        def run(self, input=None, async=False):
                                      ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Mblanski\AppData\Local\Temp\pip-install-drda0fvn\sarge\
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

**Comment by davisagli** [comment]
@Auchtor huh. I'm not sure why I didn't run into it when I tested with Python 3.7 here, but `sarge` is clearly not compatible with Python 3.7 (which added `async` as a reserved keyword in the language). I will revisit whether we can really suggest using Python 3.7 yet; in the meantime, I'd suggest trying Python 3.6.

**Comment by davisagli** [comment]
@Auchtor we figured it out -- since the new release that supports Python 3.7 is a beta release, you don't get it automatically when you run "pip install cumulusci". To request it specifically, run "pip install cumulusci==2.1.0b1" instead

**Comment by Auchtor** [comment]
Install validated with the new instructions. I'm going to go ahead and test if the bug I saw in the other issue can be reproduced now.

**Comment by davisagli** [comment]
Thanks! And I will update the tutorial's instructions for creating a virtualenv on Windows based on your notes.

**Comment by davisagli** [comment]
Instructions updated in #817
