### ISSUE TITLE
cci project init non-functional in latest build.

### ISSUE THREAD

**Issue by Auchtor** [SFDO-Tooling/CumulusCI#816]
The project initialization script is currently not functioning. Attempting to run it to initialize a new project results in a failed check for an existing cumulusci.yml

`cci project init
Checking the version!
The file cumulusci.yml was not found in the repo root: \foo\bar. Are you in a CumulusCI Project directory?`

**Comment by davisagli** [comment]
Confirmed this happens for me too.

**Comment by davisagli** [comment]
**lurch: attach W-029086

**Comment by davisagli** [comment]
Fixed in 2.1.0
