### ISSUE TITLE
Make setting the default cci org also set it as default for sfdx

### ISSUE THREAD

**Issue by njjc** [SFDO-Tooling/CumulusCI#868]
In order to facilitate using the VS Code integration with sfdx, I'd like the command
`cci org default foo` 
to run the command
`sfdx force:config:set defaultusername=test-autogeneratedscratchlogin@example.com`

Both commands are project specific. This would allow my scratch org to follow along in VS Code without typing an extra sfdx command every time I switch orgs.

**Comment by 1handclapping** [comment]
Hi @cdcarter, I definitely second this enhancement - I made a quick patch that works for me [here](https://github.com/SFDO-Tooling/CumulusCI/compare/master...1handclapping:feature/new-dx-commands). I figure there is some larger refactoring that will go into 2.3 but if this suffices happy to make a pr.

**Comment by davisagli** [comment]
@njjc added in cumulusci 2.5.0
