### ISSUE TITLE
Move Repo Info into BaseRuntime

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/CumulusCI#874]
After spending too much time going down a scary path in #869, it makes sense to me to move the repo_info (and friends) methods from BaseProjectConfig into BaseRuntime. They're runtime context. The implementation in BaseRuntime will be very basic: accept the params at initialization, expose the properties, update BaseProjectConfig to look back, for now.

The git-fs based detection and env variable based detection should be declared by overrides in CliRuntime

More description to come...

**Comment by davisagli** [comment]
If we're going to support running steps defined in a different project, I think we'll want the repo info to remain connected to a specific project config rather than the runtime.
