### ISSUE TITLE
CumulusCI should be able to connect to any DX alias and/or understand dx auth files

### ISSUE THREAD

**Issue by Szandor72** [SFDO-Tooling/CumulusCI#877]
We use vanilla DX tooling mostly and CumulusCI for special tasks like cascading deletes, nsp manipulation or browsertests.

One blocker is the inability to connect a Scratch org to CCI on the fly during a CI process to run tasks against it. 

Ideally, we could connect CCI with any DX alias or at least feed a DX auth url file into the CCI keychain.

**Comment by davisagli** [comment]
cumulusci 2.2.0 added a `cci org import` command to import an org from SFDX.
