### ISSUE TITLE
Special characters break deploy task when running user is in French

### ISSUE THREAD

**Issue by bethbrains** [SFDO-Tooling/CumulusCI#911]
![image](https://user-images.githubusercontent.com/12188165/50253779-4479e280-03a0-11e9-9329-d41a95a0d2b2.png)
Set my scratch org user to French to test translated labels and got this error when I tried to run `cci task run deploy`.

**Comment by davisagli** [comment]
**lurch: add

**Comment by davisagli** [comment]
This was fixed in cumulusci 2.3.0b1
