### ISSUE TITLE
Expired scratch org recreate flow doesn't automatically set a password

### ISSUE THREAD

**Issue by bethbrains** [SFDO-Tooling/CumulusCI#945]
When a scratch org expires, the user attempts to run something against the org, and cci asks `Attempt to recreate the scratch org? [Y/n]:`, if the user enters Y, the new org is created without a password. The expected behavior would be the same as `cci org scratch`, which does by default generate a password.

**Comment by davisagli** [comment]
Thanks -- I think this is a duplicate of #670 (which we still need to work on).
