### ISSUE TITLE
Generate scratch org password with cci, not sfdx

### ISSUE THREAD

**Issue by bethbrains** [SFDO-Tooling/CumulusCI#946]
In order to easily generate a password for a scratch org, a user can simply run a `cci org` command. (Currently, we must run `sfdx force:user:password:generate -u ORGNAME`.)

**Comment by davisagli** [comment]
Closing this since we made the automatic generation of a password for new scratch orgs more reliable a long time ago. But willling to reconsider if there's still a need.
