### ISSUE TITLE
Pass org in robot file

### ISSUE THREAD

**Issue by moloman** [SFDO-Tooling/CumulusCI#948]
There doesn't seem to be a way to specify the org you use from within a robot test. When using multiple robot tests which test multiple salesforce users, specifying those users in the robot test files can be the best way to keep that organised.

**Comment by davidmreed** [comment]
@boakley I believe this is now supported in some form - is that correct?

**Comment by boakley** [comment]
@davidmreed that is correct, [Open Test Browser](https://cumulusci.readthedocs.io/en/stable/Keywords.html#Salesforce.robot.Open%20Test%20Browser) accepts a useralias that lets you reference a different user.

**Comment by davidmreed** [comment]
Fantastic. Closing this issue as solved.
