### ISSUE TITLE
Add an if condition to Click Related List Button to handle special cases

### ISSUE THREAD

**Issue by skristem** [SFDO-Tooling/CumulusCI#957]
Click Related List Button is waiting for a modal to open but in some cases, clicking on the button opens a different page(example: manage allocations, schedule payments buttons). Need an if condition for exceptional cases.

As a temporary workaround for this, I have created a Click Special Related List Button in npsp.py file

**Comment by davidmreed** [comment]
Closing issue as outdated - please feel free to open a new issue with current details if this issue is still impactful.
