### ISSUE TITLE
"cci task run invalid_task" should not give a stack trace

### ISSUE THREAD

**Issue by boakley** [SFDO-Tooling/CumulusCI#960]
If I try to run a task that hasn't been defined (or maybe I spelled it wrong), I get a stack trace on stderr instead of a more human-friendly response.

At the very least, it should just print out something like `cannot find task 'foobar'` or `invalid task: 'foobar'`, possibly followed by a list of valid tasks. Even better might be to try to do a fuzzy match to existing tasks, so we could display something like "cannot find task 'foobor'. Did you mean 'foobar'?".

**Comment by davisagli** [comment]
Fixed in cumulusci 2.5.3
