### ISSUE TITLE
Allow cci service * commands when not in a git repo

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#963]
It should be possible to use commands like `cci service connect github` or `cci service list` from just the global config without requiring you to be in a local git repo configured for CumulusCI.  We'd probably want to make sure you couldn't do `cci service connect github --project True` outside a git repo though.

**Comment by davisagli** [comment]
Looks like this will require refactoring keychains which currently are written assuming they have access to a project_config.
