### ISSUE TITLE
Remove dependency on a local git repo where possible

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#966]
A lot of CumulusCI could run using the global config without requiring being in a local git repo.  For example, you should be able to run most of the globally defined tasks against a global org in the keychain without ever having to be in a project repo.  This would involve refactoring all classes which currently accept a project config in their init to instead accept the runtime (`cumulusci.core.runtime.BaseCumulusCI` or a subclass).

**Comment by davisagli** [comment]
I don't think we want to do this as worded above, but we should make it possible to run commands in a directory that doesn't have a `.git` subfolder as long as the project config has been initialized with sufficient `repo_info` to be able to know its git context without consulting the filesystem. This would allow us to remove code that creates an empty `.git` folder in most of our apps that embed CumulusCI.
