### ISSUE TITLE
Improve error when github requires 2FA token

### ISSUE THREAD

**Issue by davisagli** [SFDO-Tooling/CumulusCI#998]
If a github repo requires 2FA but the user configured the github service with their password, they get a somewhat obtuse exception: github3.exceptions.AuthenticationFailed: 401 Must specify two-factor authentication OTP code.

We can catch this and provide a link to more helpful instructions.

**Comment by davisagli** [comment]
**lurch: add

**Comment by davidmreed** [comment]
Tracking as W-8887593 (not Lurch!)

**Comment by davisagli** [comment]
GitHub no longer supports password authentication for the API
